#!/bin/sh
#
# install.sh - Install the unified DTS + TrueHD/MLP audio restore on a rooted
#              LG webOS 25 TV (C5 class). PROVEN working on a real LG C5.
#
# Run as root ON THE TV, from this restore/ directory (copied via scp), which
# must contain:
#     out/libgstdtsdec.so        patched dtsdec (S32LE, accepts A_DTS)   [build.sh]
#     out/libdca.so.0            DTS decode library (armel)              [build.sh]
#     truehd-out/libgstlibav.so  gst-libav with avdec_truehd/avdec_mlp   [build-truehd.sh]
#     truehd-out/libav*.so*      minimal ffmpeg n4.4.4 libs (+symlinks)  [build-truehd.sh]
#     truehd-out/libsw*.so*      libswresample (+symlinks)               [build-truehd.sh]
#     demux-out/libgstisomp4.so       mp4 demux, DTS re-enabled (OPTIONAL) [build-demux.sh]
#     demux-out/libgstmpegtsdemux.so  ts/m2ts demux, DTS re-enabled (OPT.) [build-demux.sh]
#   (the boot/apply script is EMBEDDED in this installer - no sibling file needed)
#
# out/ and truehd-out/ are the CORE payload and are required. demux-out/ is
# optional: without it the boot hook simply skips the demuxer binds and DTS still
# works in MKV (see step 2c).
#
# All binaries are PREBUILT and bundled; you do NOT need Docker or to build
# anything. Just: copy this folder to the TV, then run (as root):
#
#   sh install.sh
#
# What it does (idempotent, guarded, logged to /tmp/dts25.log, always exit 0):
#   1. Stages the DTS payload  -> /var/lib/webosbrew/dts25/{,libs/}
#   2. Stages the TrueHD payload-> /var/lib/webosbrew/truehd/{,libs/}
#   2c. Stages the container demuxers (if demux-out/ present)
#        -> /var/lib/webosbrew/demux25/ (mp4/ts/m2ts DTS; boot hook binds them)
#   3. GENERATES two config overrides by EDITING the TV's own live /etc files
#      (no LG config file is shipped):
#        a. /etc/umediaserver/device_codec_capability_config.json
#           -> insert TRUEHD + MLP audio-codec objects after the DTSE entry
#        b. /etc/gst/gstcool.conf
#           -> insert avdec_truehd=310 + avdec_mlp=310 after [sw_decoder]
#      Both are written to /var/lib/webosbrew/truehd/ and bind-mounted by the
#      boot hook (originals are never modified in place - fully reversible).
#   4. Installs the canonical init_dts25.sh, then runs its READ-ONLY compatibility
#      preflight (W25_CHECK=1). Only if that says verified/forced does it symlink
#      the boot hook /var/lib/webosbrew/init.d/restore_dts25 -> it. On any other
#      verdict it prints the reason and changes nothing on this TV.
#   5. Applies everything now (runs the init script) + restarts the media pipe.
#
# COMPATIBILITY GATE. Our .so are bind-mounted over LG's system-wide (they
# propagate into every app jail), so this installer refuses to bind on a TV whose
# stock plugin fingerprints are not in init_dts25.sh's verified-sets table. To
# opt in anyway on an unverified TV:
#
#   FORCE=1 sh install.sh
#
# which is recorded as forced=1 in /var/lib/webosbrew/dts25/stock.fp so later
# boots honour the choice. FORCE=1 NEVER overrides a drift verdict (the stock
# plugins changed under an existing install) or the GStreamer ABI guard or the
# loader gate. To re-opt-in after a firmware change, run uninstall.sh (which
# clears the recorded baseline) and then install.sh, which puts the TV back in
# the unverified flow where the opt-in applies.
#
# A REFUSED RUN LEAVES THE STAGED FILES UNDER /var/lib/webosbrew IN PLACE, on
# purpose: no boot hook is linked, so they are inert, and stock.fp among them is
# what lets a later run distinguish a firmware change from an unverified TV. Use
# uninstall.sh to remove them.
#
set -u

# Explicit opt-in on a TV that is not in the verified-sets table. Author-read
# only: the value is compared, never interpolated into a command.
FORCE=${FORCE:-0}

LOG=/tmp/dts25.log
DTS_DEST=/var/lib/webosbrew/dts25
DTS_LIBS=$DTS_DEST/libs
THD_DEST=/var/lib/webosbrew/truehd
THD_LIBS=$THD_DEST/libs
INITD=/var/lib/webosbrew/init.d
HOOK=$INITD/restore_dts25
INIT_SCRIPT=$DTS_DEST/init_dts25.sh
# Marker that says "an SSH/CLI install owns this state", so the boot script's
# self-heal does not mistake a CLI-only install for an orphaned one.
CLI_MARKER=$DTS_DEST/.cli-install

# Live LG config files we derive our (bind-mounted) overrides from.
CFG_LIVE=/etc/umediaserver/device_codec_capability_config.json
CFG_OVR=$THD_DEST/codec_capability.json
GC_LIVE=/etc/gst/gstcool.conf
GC_OVR=$THD_DEST/gstcool.conf

# Bind targets the boot hook manages (unmount here so we read pristine originals).
LGLIBAV=/usr/lib/gstreamer-1.0/libgstlibav.so
REG_TARGET=/mnt/flash/data/gst_1_0_registry.arm.bin

SELF_DIR=$(cd "$(dirname "$0")" && pwd)

log() { echo "[dts25-install $(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG" 2>&1; }

# Unmount one bind target, falling back to a LAZY detach when it is busy.
# Measured on a real C5: umount of /usr/lib/gstreamer-1.0/libgstlibav.so fails
# with "target is busy" because WebAppMgr has the .so mapped, while `umount -l`
# succeeds -- so without this fallback a stale override survives the "regenerate
# from pristine originals" step and we would derive our overrides from OUR OWN
# files. Same semantics as w25_umount() in init_dts25.sh.
w25_umount() {
  grep -q " $1 " /proc/mounts 2>/dev/null || return 0
  if umount "$1" 2>>"$LOG"; then log "unmounted stale bind $1"; return 0; fi
  if umount -l "$1" 2>>"$LOG"; then log "lazy-detached busy stale bind $1 (a live mapping held it)"; return 0; fi
  log "WARN could not unmount $1, even lazily"
  return 1
}

log "=== unified DTS+TrueHD install start ==="

# --- 1. Stage DTS payload --------------------------------------------------
mkdir -p "$DTS_LIBS" || { log "FATAL: cannot create $DTS_LIBS"; exit 0; }

# Mark this as an SSH/CLI install BEFORE anything can run the boot script: its
# self-heal reverts an install that no longer has an owner (app dir gone), and
# without this marker a CLI-only install would look exactly like that and be
# healed away on the next boot.
: > "$CLI_MARKER" && log "marked CLI install ($CLI_MARKER)" || log "WARN: could not write $CLI_MARKER"

if [ -f "$SELF_DIR/out/libgstdtsdec.so" ]; then
  cp -f "$SELF_DIR/out/libgstdtsdec.so" "$DTS_DEST/libgstdtsdec.so" \
    && log "installed libgstdtsdec.so -> $DTS_DEST/" || log "WARN: copy libgstdtsdec.so failed"
else
  log "WARN: $SELF_DIR/out/libgstdtsdec.so not found (run build.sh first)"
fi
if [ -f "$SELF_DIR/out/libdca.so.0" ]; then
  cp -f "$SELF_DIR/out/libdca.so.0" "$DTS_LIBS/libdca.so.0" \
    && log "installed libdca.so.0 -> $DTS_LIBS/" || log "WARN: copy libdca.so.0 failed"
else
  log "WARN: $SELF_DIR/out/libdca.so.0 not found (run build.sh first)"
fi

# --- 2. Stage TrueHD payload (preserve the .so version symlinks) -----------
mkdir -p "$THD_LIBS" || { log "FATAL: cannot create $THD_LIBS"; exit 0; }

if [ -f "$SELF_DIR/truehd-out/libgstlibav.so" ]; then
  cp -f "$SELF_DIR/truehd-out/libgstlibav.so" "$THD_DEST/libgstlibav.so" \
    && log "installed libgstlibav.so -> $THD_DEST/" || log "WARN: copy libgstlibav.so failed"
else
  log "WARN: $SELF_DIR/truehd-out/libgstlibav.so not found (run build-truehd.sh first)"
fi

n=0
for f in "$SELF_DIR"/truehd-out/libav*.so* "$SELF_DIR"/truehd-out/libsw*.so*; do
  [ -e "$f" ] || continue
  # cp -P preserves the soname symlinks (libavcodec.so.58 -> libavcodec.so.58.x.y).
  cp -Pf "$f" "$THD_LIBS/" && n=$((n+1))
done
log "staged $n ffmpeg lib entries -> $THD_LIBS/"

# --- 2c. Stage container-demuxer payload (mp4/ts/m2ts DTS re-enabled) -------
# Patched isomp4/mpegtsdemux (dts_support default TRUE). Optional: if demux-out/
# is absent the boot hook simply skips the demuxer binds (MKV DTS still works).
DMX_DEST=/var/lib/webosbrew/demux25
DMX_ISO=/usr/lib/gstreamer-1.0/libgstisomp4.so
DMX_TSD=/usr/lib/gstreamer-1.0/libgstmpegtsdemux.so
mkdir -p "$DMX_DEST" || log "WARN: cannot create $DMX_DEST"
for so in libgstisomp4.so libgstmpegtsdemux.so; do
  if [ -f "$SELF_DIR/demux-out/$so" ]; then
    cp -f "$SELF_DIR/demux-out/$so" "$DMX_DEST/$so" \
      && log "installed $so -> $DMX_DEST/" || log "WARN: copy $so failed"
  else
    log "note: $SELF_DIR/demux-out/$so not found; container DTS (mp4/ts/m2ts) will be skipped"
  fi
done

# --- 2d. Seed first-run audio defaults (make-up gain + DRC) -----------------
# Gain and DRC shipped OPT-IN while the DSP was still unproven: no config file
# meant fully inert (0.0 dB, DRC off), so an install could not change anyone's
# sound. Now that the curve is validated on-device, that caution costs more
# than it buys - an untouched install leaves DTS/TrueHD quieter and
# un-managed next to native AAC/AC-3, which is what the feature exists to fix.
# So seed a starting point and let users tune down instead of discovering they
# have to tune up.
# Written ONLY when absent: after the first install the file belongs to the
# user (the app's Save owns it), and re-running install.sh must never
# clobber their settings. Retune from the app or per TUNING-RUNBOOK.md.
# NOTE: keep in sync with the app's w25GainConfSeedScript() (CLAUDE.md rule 3).
# The +5.0 dB is not a guess: it is the value the maintainer arrived at BY EAR
# on a real C5, with this same DRC line 100/100 preset active, and has been
# running as a hand-set config. Prefer that over a theoretical figure.
seed_gain_conf() {
  if [ -f "$1" ]; then
    log "note: $1 exists; keeping saved audio settings"
  elif printf '%s\n%s\n%s\n%s\n%s\n' \
      "5.0" "drc=line" "drc_boost=100" "drc_cut=100" "center=0.0" \
      > "$1.tmp" && mv -f "$1.tmp" "$1"; then
    log "seeded first-run audio defaults -> $1 (+5.0 dB, DRC line 100/100)"
  else
    log "WARN: could not seed $1"
  fi
}
seed_gain_conf "$DTS_DEST/gain.conf"
seed_gain_conf "$THD_DEST/gain.conf"

# --- 3. Unmount any existing binds so we regenerate from PRISTINE originals -
# This also has to leave the three stock plugins unshadowed, because the
# compatibility preflight in step 4b fingerprints them straight after.
for T in "$CFG_LIVE" "$GC_LIVE" "$LGLIBAV" "$DMX_ISO" "$DMX_TSD" "$REG_TARGET"; do
  w25_umount "$T"
done

# --- 3a. Generate the codec-capability override (insert TRUEHD+MLP after DTSE)
# awk is idempotent: it only injects when the DTSE object is seen and, guarded
# below, only when TRUEHD is not already present in the source.
if [ -f "$CFG_LIVE" ]; then
  if grep -q '"TRUEHD"' "$CFG_LIVE"; then
    log "note: live capability config already has TRUEHD; copying as-is"
    cp -f "$CFG_LIVE" "$CFG_OVR"
  else
    awk '
      /"name" : "DTSE"/ { indts=1 }
      { print }
      indts && /^ *},/ {
        print "    {";
        print "      \"name\" : \"TRUEHD\",";
        print "      \"channels\" : 8";
        print "    },";
        print "";
        print "    {";
        print "      \"name\" : \"MLP\",";
        print "      \"channels\" : 8";
        print "    },";
        indts=0
      }
    ' "$CFG_LIVE" > "$CFG_OVR" && log "generated capability override $CFG_OVR (TRUEHD+MLP after DTSE)" \
      || log "WARN: capability override generation failed"
  fi
else
  log "WARN: $CFG_LIVE not present; cannot generate capability override"
fi

# --- 3b. Generate the gstcool.conf override (avdec_truehd/mlp=310 rank lever)
if [ -f "$GC_LIVE" ]; then
  if grep -q '^avdec_truehd=' "$GC_LIVE"; then
    log "note: live gstcool.conf already has avdec_truehd; copying as-is"
    cp -f "$GC_LIVE" "$GC_OVR"
  else
    awk '
      { print }
      /^\[sw_decoder\]/ { print "avdec_truehd=310"; print "avdec_mlp=310" }
    ' "$GC_LIVE" > "$GC_OVR" && log "generated gstcool override $GC_OVR (avdec_truehd/mlp=310)" \
      || log "WARN: gstcool override generation failed"
  fi
else
  log "WARN: $GC_LIVE not present; cannot generate gstcool override"
fi

# --- 4. Install the canonical boot/apply script (embedded) + hook ----------
# The boot/apply logic is embedded here as base64 so this installer is a single
# self-contained script (no sibling init file needed). Decodes verbatim to the
# proven init_dts25.sh.
base64 -d > "$INIT_SCRIPT" <<'INIT_B64'
IyEvYmluL3NoCiMgd2ViT1MyNSBEVFMgKyBUcnVlSEQgcmVzdG9yZS4gUnVucyBhdCBib290IHZpYSAvdmFyL2xpYi93ZWJvc2JyZXcvaW5pdC5kL3Jlc3RvcmVfZHRzMjUuCiMKIyBUSFJFRSBCWVRFLUlERU5USUNBTCBDT1BJRVMgKENMQVVERS5tZCBydWxlIDMpOiB0aGlzIGZpbGUsIHRoZSBiYXNlNjQgSU5JVF9CNjQKIyBibG9iIGluIHJlc3RvcmUvaW5zdGFsbC5zaCwgYW5kIHcyNUluaXRTY3JpcHRCb2R5KCkgaW4gYXBwL3NlcnZpY2Uvc2VydmljZS5qcy4KIyBUaGUgYmxvY2sgYmV0d2VlbiB0aGUgVzI1LUNPTVBBVCBtYXJrZXJzIGlzIGFkZGl0aW9uYWxseSBzaGFyZWQgdmVyYmF0aW0gd2l0aAojIHRoZSBhcHAncyByZWFkLW9ubHkgREVURUNUX1BST0JFLCBzbyB0aGUgdmVyZGljdCB0aGUgVUkgc2hvd3MgaXMgdGhlIHZlcmRpY3QKIyB0aGlzIHNjcmlwdCBlbmZvcmNlcy4gQ2hhbmdlIG9uZSBjb3B5IC0+IGNoYW5nZSBhbGwgdGhyZWUuCiMKIyBNT0RFUwojICAgKGRlZmF1bHQpICAgICBhcHBseTogc2VsZi1oZWFsIGNoZWNrICh1bm93bmVkIC0+IHJldmVydCt1bmxpbms7IG93bmVkIGJ1dCB0aGUKIyAgICAgICAgICAgICAgICAgY29yZSBwYXlsb2FkIGlzIGluY29tcGxldGUgLT4gcmVmdXNlLCBkZWxldGUgbm90aGluZykgLT4gdmVyc2lvbgojICAgICAgICAgICAgICAgICBndWFyZCAtPiBpZGVudGl0eSBnYXRlIC0+IGxvYWRlciBnYXRlIC0+IGJpbmRzIC0+IHBvc3QtYmluZAojICAgICAgICAgICAgICAgICBwcm9vZiAtPiByZWdpc3RyeSBjb21taXQuCiMgICBXMjVfQ0hFQ0s9MSAgIHJlYWQtb25seSBwcmVmbGlnaHQgZm9yIGluc3RhbGwuc2ggLyB0aGUgYXBwJ3MgRW5hYmxlOiBwcmludHMKIyAgICAgICAgICAgICAgICAgVkVSRElDVC9SRUFTT04vTEFCRUwvQ0FORk9SQ0UvTE9BREVSIGFuZCBleGl0cy4gQmluZHMgbm90aGluZywKIyAgICAgICAgICAgICAgICAgd3JpdGVzIG5vdGhpbmcsIHRvYXN0cyBub3RoaW5nLgojICAgVzI1X1NUQU5EX0RPV049MQojICAgICAgICAgICAgICAgICBwdXQgdGhpcyBUViBiYWNrIG9uIHN0b2NrIGFuZCBleGl0OiBkcm9wIG91ciBiaW5kcyBhbmQgcmVidWlsZAojICAgICAgICAgICAgICAgICBMRydzIHJlZ2lzdHJ5IGlmIG9uZSBvZiBvdXJzIGlzIGxpdmUuIE5vIGdhdGUsIG5vIGJpbmRzLCBubwojICAgICAgICAgICAgICAgICB0b2FzdCwgYW5kIGl0IGNhbiBuZXZlciBhcHBseSBhbnl0aGluZy4gVGhpcyBpcyB3aGF0IHRoZSB0d28KIyAgICAgICAgICAgICAgICAgaW5zdGFsbGVycyBjYWxsIHdoZW4gdGhlaXIgcHJlZmxpZ2h0IHJlZnVzZXMgQUZURVIgdGhleSBoYXZlCiMgICAgICAgICAgICAgICAgIGFscmVhZHkgZGV0YWNoZWQgdGhlIGJpbmRzLCBzbyAibm90aGluZyBpcyBhcHBsaWVkIiBpcyB0cnVlCiMgICAgICAgICAgICAgICAgIHJhdGhlciB0aGFuIG1lcmVseSBpbnRlbmRlZC4KIyAgIEZPUkNFPTEgICAgICAgZXhwbGljaXQgb3B0LWluIG9uIGEgVFYgdGhhdCBpcyBub3QgaW4gdGhlIHZlcmlmaWVkIHRhYmxlLgojCiMgQWx3YXlzIGV4aXRzIDA6IGEgbm9uLXplcm8gd2Vib3NicmV3IGluaXQgc2NyaXB0IHRyaXBzIHRoZSBmYWlsc2FmZSB0aGF0CiMgZGlzYWJsZXMgQUxMIHJvb3QgY3VzdG9taXNhdGlvbnMgb24gdGhlIG5leHQgYm9vdC4gRXZlcnkgcmVmdXNhbCBwYXRoIGJpbmRzCiMgbm90aGluZyAtLSB0aGUgb3ZlcnJpZGVzIGFyZSBzeXN0ZW0td2lkZSAodGhleSBwcm9wYWdhdGUgaW50byBldmVyeSBhcHAgamFpbCksCiMgc28gIm5vdCBzdXJlIiBtdXN0IG1lYW4gImRvIG5vdCB0b3VjaCB0aGlzIFRWIi4gVGhlIHR3byBjb250YWluZXIgZGVtdXhlcnMgYXJlCiMgT1BUSU9OQUw6IHdpdGhvdXQgdGhlbSBEVFMgc3RpbGwgd29ya3MgaW4gTUtWLCB3aGljaCBpcyBob3cgdGhpcyBzaGlwcGVkIGJlZm9yZQojIHRoZSBnYXRlIGV4aXN0ZWQsIHNvIGVhY2ggaXMgYm91bmQgb25seSB3aGVuIHN0YWdlZC4KIwojIEEgcmVmdXNhbCBhbHNvIFJFUEFJUlM6IGl0IGRyb3BzIHRoZSBiaW5kcyBhbmQsIGlmIGEgbWVkaWEgcmVnaXN0cnkgd2Ugd3JvdGUgaXMKIyBzdGlsbCBsaXZlLCByZWdlbmVyYXRlcyBMRydzLiBUaGF0IHNlY29uZCBoYWxmIGlzIG5vdCBvcHRpb25hbCAtLSB0aGUgcmVnaXN0cnkKIyBpcyBjb21taXR0ZWQgd2l0aCBgY3AgLWZgIHJhdGhlciB0aGFuIGJpbmQtbW91bnRlZCwgc28gYW4gdW5yZXBhaXJlZCBvbmUga2VlcHMKIyBvdXIgZHRzZGVjIHJlZ2lzdGVyZWQgYnkgYWJzb2x1dGUgcGF0aCBldmVuIHdpdGggZXZlcnkgYmluZCBnb25lLgojCiMgU1RBR0VEIEZJTEVTIEFSRSBMRUZUIElOIFBMQUNFIE9OIEEgUkVGVVNBTCwgREVMSUJFUkFURUxZLiBBIHJlZnVzZWQgaW5zdGFsbAojIGxpbmtzIG5vIGJvb3QgaG9vaywgc28gbm90aGluZyBvZiBvdXJzIGV2ZXIgcnVucyBhZ2FpbiBvbiB0aGF0IFRWOyB0aGUgZmlsZXMKIyB1bmRlciAvdmFyL2xpYi93ZWJvc2JyZXcgYXJlIGluZXJ0IHdpdGhvdXQgdGhlIGJpbmRzLiBUaGV5IGFyZSBrZXB0IGJlY2F1c2UKIyBzdG9jay5mcCBpcyBhbW9uZyB0aGVtLCBhbmQgdGhhdCByZWNvcmRlZCBiYXNlbGluZSBpcyB0aGUgb25seSB3YXkgYSBsYXRlciBib290CiMgY2FuIHRlbGwgInRoZSBmaXJtd2FyZSBjaGFuZ2VkIiBmcm9tICJ0aGlzIFRWIHdhcyBuZXZlciB2ZXJpZmllZCIgLS0gZGVsZXRpbmcgaXQKIyB3b3VsZCBkb3duZ3JhZGUgZXZlcnkgZnV0dXJlIGRyaWZ0IGludG8gYSBiYXJlICJ1bnZlcmlmaWVkIi4gVGhlIGFwcCdzIFVuaW5zdGFsbAojIHJlbW92ZXMgdGhlbSBvbiBkZW1hbmQuCnNldCAtdQpMT0c9L3RtcC9kdHMyNS5sb2cKVzI1X0xPRz0kTE9HCnRvYXN0KCkgeyBsdW5hLXNlbmQgLW4gMSBsdW5hOi8vY29tLndlYm9zLm5vdGlmaWNhdGlvbi9jcmVhdGVUb2FzdCAie1wic291cmNlSWRcIjpcImlvLmdpdGh1Yi5qb3NpcHBhcGV6LmR0c2VuYWJsZXJcIixcIm1lc3NhZ2VcIjpcIiQxXCJ9IiA+L2Rldi9udWxsIDI+JjE7IH0KZWNobyAiLS0tIGR0czI1K3RydWVoZCAkKGRhdGUpIC0tLSIgPj4gJExPRyAyPiYxCiMgPj4+IFcyNS1DT01QQVQtQkVHSU4KIyBDb21wYXRpYmlsaXR5IGdhdGUgKyByZXZlcnNpYmlsaXR5IGhlbHBlcnMgLS0gdGhlIFNJTkdMRSBBVVRIT1JFRCBDT1BZLgojIEV2ZXJ5dGhpbmcgaGVyZSBpcyBlaXRoZXIgYSBwdXJlIG1lYXN1cmVtZW50IG9yIGFuIGV4cGxpY2l0bHktY2FsbGVkIGFjdGlvbjsKIyBtZXJlbHkgc291cmNpbmcgdGhpcyBibG9jayBtb3VudHMsIGRlbGV0ZXMgYW5kIHdyaXRlcyBub3RoaW5nLCB3aGljaCBpcyB3aGF0CiMgbGV0cyB0aGUgYXBwJ3MgcmVhZC1vbmx5IHByb2JlIHJldXNlIGl0IGFzLWlzLgpFWFBFQ1RfR1NUPTEuMjQKIyBTdGFtcCBpZGVudGlmeWluZyB0aGUgR0FURSB0aGlzIHNjcmlwdCBlbmZvcmNlcy4gVGhlIGluc3RhbGxlZCBjb3B5IG9uIGEgVFYgaXMKIyBvbmx5IHJld3JpdHRlbiBieSBFbmFibGUgLyBpbnN0YWxsLnNoLCBzbyBhIFRWIGVuYWJsZWQgdW5kZXIgYW4gb2xkZXIgYXBwIGtlZXBzCiMgcnVubmluZyB0aGF0IG9sZGVyIHNjcmlwdCAtLSB3aGlsZSB0aGUgYXBwJ3Mgb3duIHByb2JlIGp1ZGdlcyB3aXRoIHRoZSBjb21wYXQKIyBibG9jayBlbWJlZGRlZCBpbiB0aGUgTkVXIGJ1aWxkLiBUaGUgYXBwIGNvbXBhcmVzIHRoaXMgdmFsdWUgKHdoaWNoIGl0IHJlYWRzCiMgZnJvbSBpdHMgb3duIGVtYmVkZGVkIGNvcHkgb2YgdGhpcyBibG9jaykgYWdhaW5zdCB0aGUgb25lIGl0IGZpbmRzIGluIHRoZQojIGluc3RhbGxlZCBzY3JpcHQsIGFuZCByZXBvcnRzIHRoZSBob29rIGFzIHN0YWxlIGluc3RlYWQgb2Ygc2lsZW50bHkgcmV3cml0aW5nIGEKIyBwcml2aWxlZ2VkIGZpbGUgYmVoaW5kIHRoZSB1c2VyJ3MgYmFjay4KIwojIEJVTVAgVEhJUyB3aGVuZXZlciB0aGUgYmVoYXZpb3VyIG9mIHRoaXMgc2NyaXB0IGNoYW5nZXMuIEl0IGlzIGRlbGliZXJhdGVseQojIGluZGVwZW5kZW50IG9mIHRoZSBhcHAgdmVyc2lvbjogYSBjb3NtZXRpYyBhcHAgcmVsZWFzZSBtdXN0IG5vdCBpbnZhbGlkYXRlIGEKIyBwZXJmZWN0bHkgY3VycmVudCBob29rLCBhbmQgYSBnYXRlIGNoYW5nZSBtdXN0IG5vdCBoaWRlIGJlaGluZCBhbiB1bmNoYW5nZWQgYXBwCiMgdmVyc2lvbi4gY2hlY2staW5pdC1zeW5jLnNoIHByb3ZlcyB0aGUgdGhyZWUgSU4tUkVQTyBjb3BpZXMgbWF0Y2g7IHRoaXMgcHJvdmVzCiMgdGhlIE9OLVRWIGNvcHkgbWF0Y2hlcyB0aGUgYXBwIHRoYXQgaXMgYXNraW5nLCBhbmQgc3luYy1pbml0LnNoIHJlZnVzZXMgdG8KIyByZWdlbmVyYXRlIHRoZSBkZXJpdmVkIGNvcGllcyBpZiB0aGUgYm9keSBtb3ZlZCB3aGlsZSB0aGlzIGRpZCBub3QuCiMgICAxICBmaXJzdCBnYXRlOiB2ZXJpZmllZC1zZXRzIHRhYmxlLCBsb2FkZXIgZ2F0ZSwgcG9zdC1iaW5kIHByb29mLCBzZWxmLWhlYWwsCiMgICAgICBzdGFuZC1kb3duIG9uIGV2ZXJ5IHJlZnVzYWwsIC9ldGMgZmluZ2VycHJpbnRzLCBob29rIHN0YW1wLgojICAgMiAgdzI1X3N0b2NrX3JlZ2lzdHJ5IHJlZnVzZXMgd2hpbGUgYSBwbHVnaW4gYmluZCBvZiBvdXJzIHN1cnZpdmVzOyB0aGUgdHdvCiMgICAgICBpbnN0YWxsZXJzIHN0YW5kIHRoZSBUViBkb3duIG9uIGEgcmVmdXNhbCBpbnN0ZWFkIG9mIGxlYXZpbmcgaXQgaGFsZi13YXkuCiMgICAzICB0aGUgdmVyaWZpZWQtc2V0cyB0YWJsZSBhbHNvIGtleXMgb24gYSBwcm9kdWN0LWlkIGdsb2IuIFBsdWdpbiBoYXNoZXMgYXJlCiMgICAgICBub3QgbW9kZWwtdW5pcXVlIC0tIGEgRzUvTTUgc2hpcHMgYnl0ZS1pZGVudGljYWwgY29waWVzIG9mIGFsbCB0aHJlZSAtLSBzbwojICAgICAgYSBoYXNoLW9ubHkgbWF0Y2ggdXNlZCB0byByZXBvcnQgYHZlcmlmaWVkYCB3aXRoIHRoZSBDNSdzIGxhYmVsIG9uIGhhcmR3YXJlCiMgICAgICBub2JvZHkgaGFkIHRlc3RlZC4gQSBoYXNoIG1hdGNoIG9uIGEgZGlmZmVyZW50IG1vZGVsIGlzIG5vdyBgdW52ZXJpZmllZGAKIyAgICAgIHdpdGggQ0FORk9SQ0U9MSBhbmQgYSByZWFzb24gdGhhdCBzYXlzIHRoZSBhcnRpZmFjdHMgYXJlIGlkZW50aWNhbCBidXQgdGhlCiMgICAgICBtb2RlbCBpcyB1bnRlc3RlZCwgd2hpY2ggcm91dGVzIGl0IHRocm91Z2ggdGhlIGV4aXN0aW5nIGV4cGxpY2l0IG9wdC1pbgojICAgICAgaW5zdGVhZCBvZiBhdXRvLWFwcGx5aW5nLgojICAgNCAgZml4ZXMgYSByZWdyZXNzaW9uIGluIDM6IHRoZSBuZWFyLW1hdGNoIGVhcmx5LXJldHVybiBza2lwcGVkIHRoZSBGT1JDRT0xCiMgICAgICBoYW5kbGluZywgc28gIlRyeSBhbnl3YXkiIHJlcG9ydGVkIHRoZSBzYW1lIHJlZnVzYWwgYXMgRW5hYmxlIC0tIHRoZSBtZXNzYWdlCiMgICAgICB0b2xkIHRoZSB1c2VyIHRvIG9wdCBpbiBhbmQgdGhlbiBpZ25vcmVkIHRoZW0uIFJlcG9ydGVkIGJ5IGEgRzUgb3duZXIuIEFsc28KIyAgICAgIGFkZHMgdGhlIEc1IHJvdywgd2hpY2ggaXMgbm93IG93bmVyLXZlcmlmaWVkIG9uIGZpcm13YXJlIDMzLjMwLjk3LgpXMjVfR0FURV9WRVJTSU9OPTQKRlA9L3Zhci9saWIvd2Vib3NicmV3L2R0czI1L3N0b2NrLmZwCiMgV2hlcmUgdGhlIGluc3RhbGxlZCBjb3B5IG9mIFRISVMgc2NyaXB0IGxpdmVzLCBhbmQgdGhlIGJvb3QgaG9vayB0aGF0IHN5bWxpbmtzCiMgdG8gaXQuIE5hbWVkIGhlcmUsIGluIHRoZSBzaGFyZWQgYmxvY2ssIHNvIHRoZSByZWFkLW9ubHkgcHJvYmUgY2FuIGZpbmdlcnByaW50CiMgdGhlIHNjcmlwdCBhbmQgc2VlIHdoZXRoZXIgdGhlIGhvb2sgaXMgbGlua2VkIHdpdGhvdXQgZHVwbGljYXRpbmcgZWl0aGVyIHBhdGguCklOSVRfU0VMRj0vdmFyL2xpYi93ZWJvc2JyZXcvZHRzMjUvaW5pdF9kdHMyNS5zaApIT09LPS92YXIvbGliL3dlYm9zYnJldy9pbml0LmQvcmVzdG9yZV9kdHMyNQpSRUc9L21udC9mbGFzaC9kYXRhL2dzdF8xXzBfcmVnaXN0cnkuYXJtLmJpbgpDRkc9L2V0Yy91bWVkaWFzZXJ2ZXIvZGV2aWNlX2NvZGVjX2NhcGFiaWxpdHlfY29uZmlnLmpzb24KR0M9L2V0Yy9nc3QvZ3N0Y29vbC5jb25mCkxHTElCQVY9L3Vzci9saWIvZ3N0cmVhbWVyLTEuMC9saWJnc3RsaWJhdi5zbwpMR0lTTz0vdXNyL2xpYi9nc3RyZWFtZXItMS4wL2xpYmdzdGlzb21wNC5zbwpMR1RTRD0vdXNyL2xpYi9nc3RyZWFtZXItMS4wL2xpYmdzdG1wZWd0c2RlbXV4LnNvCiMgQ09SRSBwYXlsb2FkIC0tIHdpdGhvdXQgZWl0aGVyIG9mIHRoZXNlIHRoZXJlIGlzIG5vIERUUyBhbmQgbm8gVHJ1ZUhELCBzbyBhCiMgbWlzc2luZyBvbmUgbWVhbnMgImRvIG5vdCBiaW5kIGFueXRoaW5nIi4KTVlEVFM9L3Zhci9saWIvd2Vib3NicmV3L2R0czI1L2xpYmdzdGR0c2RlYy5zbwpNWUxJQkFWPS92YXIvbGliL3dlYm9zYnJldy90cnVlaGQvbGliZ3N0bGliYXYuc28KIyBPUFRJT05BTCBwYXlsb2FkOiB0aGUgcGF0Y2hlZCBjb250YWluZXIgZGVtdXhlcnMuIEFic2VudCwgRFRTIHN0aWxsIHdvcmtzIGluCiMgTUtWIC0tIHdoaWNoIGlzIGV4YWN0bHkgaG93IHRoaXMgc2hpcHBlZCBiZWZvcmUgdGhlIGdhdGUgZXhpc3RlZCAtLSBzbyBlYWNoIGlzCiMgYm91bmQgb25seSB3aGVuIHN0YWdlZCBhbmQgaXMgbmV2ZXIgYSByZWFzb24gdG8gcmVmdXNlIG9yIHRvIGRlbGV0ZSBhbnl0aGluZy4KTVlJU089L3Zhci9saWIvd2Vib3NicmV3L2RlbXV4MjUvbGliZ3N0aXNvbXA0LnNvCk1ZVFNEPS92YXIvbGliL3dlYm9zYnJldy9kZW11eDI1L2xpYmdzdG1wZWd0c2RlbXV4LnNvCk1ZQ0ZHPS92YXIvbGliL3dlYm9zYnJldy90cnVlaGQvY29kZWNfY2FwYWJpbGl0eS5qc29uCk1ZR0M9L3Zhci9saWIvd2Vib3NicmV3L3RydWVoZC9nc3Rjb29sLmNvbmYKTVlMSUJTPS92YXIvbGliL3dlYm9zYnJldy90cnVlaGQvbGliczovdmFyL2xpYi93ZWJvc2JyZXcvZHRzMjUvbGlicwp3MjVfbG9nKCkgeyBbIC1uICIke1cyNV9MT0c6LX0iIF0gfHwgcmV0dXJuIDA7IGVjaG8gIltkdHMyNS1nYXRlICQoZGF0ZSAnKyVZLSVtLSVkICVIOiVNOiVTJyldICQqIiA+PiAiJHtXMjVfTE9HOi19IiAyPiYxOyB9CiMgVW5tb3VudCBPTkUgYmluZCB0YXJnZXQsIGZhbGxpbmcgYmFjayB0byBhIExBWlkgZGV0YWNoIHdoZW4gaXQgaXMgYnVzeS4KIyBNZWFzdXJlZCBvbiBhIHJlYWwgQzU6IHVtb3VudCBvZiAvdXNyL2xpYi9nc3RyZWFtZXItMS4wL2xpYmdzdGxpYmF2LnNvIGZhaWxzCiMgd2l0aCAidGFyZ2V0IGlzIGJ1c3kiIGJlY2F1c2UgV2ViQXBwTWdyIGhhcyB0aGUgLnNvIG1hcHBlZCwgd2hpbGUgYHVtb3VudCAtbGAKIyBzdWNjZWVkcy4gV2l0aG91dCB0aGlzIGZhbGxiYWNrIERpc2FibGUgb25seSBsb2dzIGEgV0FSTiBhbmQgc2lsZW50bHkgbGVhdmVzCiMgdGhlIG92ZXJyaWRlIGFwcGxpZWQuCncyNV91bW91bnQoKSB7CiAgZ3JlcCAtcSAiICQxICIgL3Byb2MvbW91bnRzIDI+L2Rldi9udWxsIHx8IHsgdzI1X2xvZyAibm8gYmluZCBvdmVyICQxIjsgcmV0dXJuIDA7IH0KICBpZiB1bW91bnQgIiQxIiAyPi9kZXYvbnVsbDsgdGhlbiB3MjVfbG9nICJ1bm1vdW50ZWQgYmluZCBvdmVyICQxIjsgcmV0dXJuIDA7IGZpCiAgaWYgdW1vdW50IC1sICIkMSIgMj4vZGV2L251bGw7IHRoZW4gdzI1X2xvZyAibGF6eS1kZXRhY2hlZCBidXN5IGJpbmQgb3ZlciAkMSAoYSBsaXZlIG1hcHBpbmcgaGVsZCBpdCkiOyByZXR1cm4gMDsgZmkKICB3MjVfbG9nICJXQVJOIGNvdWxkIG5vdCB1bm1vdW50ICQxLCBldmVuIGxhemlseSIKICByZXR1cm4gMQp9CiMgRHJvcCBldmVyeSBvdmVycmlkZSBXRSBhcHBsaWVkIC0tIHJvb3RmcyBwYXRocyBvbmx5LiBUaGUgc2FtZSBiaW5kcyBwcm9wYWdhdGUKIyBpbnRvIGVhY2ggYXBwIGphaWwgKDI3IGphaWwtc2lkZSBjb3BpZXMgcGVyIGxpYnJhcnkgb24gYSByZWFsIEM1KTsgdGhvc2UgYXJlCiMgbGVmdCBhbG9uZSBkZWxpYmVyYXRlbHksIGJlY2F1c2UgZGV0YWNoaW5nIGEgamFpbCdzIG93biB2aWV3IHdvdWxkIGJyZWFrIHRoYXQKIyBqYWlsLiAkUkVHIGlzIGluY2x1ZGVkIGJlY2F1c2Ugb2xkZXIgYnVpbGRzIGJpbmQtbW91bnRlZCBpdC4KIwojIEEgdGFyZ2V0IHRoYXQgc3Vydml2ZXMgZXZlbiBhIGxhenkgZGV0YWNoIGlzIFJFUE9SVEVELCBub3Qgc3dhbGxvd2VkOiBpdCBtZWFucwojIHRoZSByZXZlcnQgZGlkIG5vdCBhY3R1YWxseSBoYXBwZW4sIGFuZCBzaWxlbnRseSBjbGFpbWluZyBzdWNjZXNzIGlzIHByZWNpc2VseQojIHRoZSBjbGFzcyBvZiBmYWlsdXJlIHRoaXMgd2hvbGUgY2hhbmdlIGV4aXN0cyB0byByZW1vdmUuIFJldHVybnMgMSBhbmQgcHJpbnRzCiMgV0FSTl9VTk1PVU5UPTx0YXJnZXRzPiBzbyBldmVyeSBjYWxsZXIgLS0gYm9vdCBzY3JpcHQgYW5kIGFwcCBhbGlrZSAtLSBjYXJyaWVzCiMgdGhlIHdhcm5pbmcgdXAuCncyNV9kcm9wX2JpbmRzKCkgewogIFVOTU9VTlRfRkFJTEVEPQogIGZvciB0IGluICIkQ0ZHIiAiJEdDIiAiJExHTElCQVYiICIkTEdJU08iICIkTEdUU0QiICIkUkVHIjsgZG8KICAgIHcyNV91bW91bnQgIiR0IiB8fCBVTk1PVU5UX0ZBSUxFRD0iJHtVTk1PVU5UX0ZBSUxFRDorJFVOTU9VTlRfRkFJTEVEIH0kdCIKICBkb25lCiAgWyAteiAiJFVOTU9VTlRfRkFJTEVEIiBdICYmIHJldHVybiAwCiAgdzI1X2xvZyAiV0FSTiByZXZlcnQgaW5jb21wbGV0ZSAtLSBzdGlsbCBtb3VudGVkOiAkVU5NT1VOVF9GQUlMRUQiCiAgZWNobyAiV0FSTl9VTk1PVU5UPSRVTk1PVU5UX0ZBSUxFRCIKICByZXR1cm4gMQp9CiMgVEhFIHJlZnVzYWwgYWN0aW9uLiBTdGFuZGluZyBkb3duIGlzIG5vdCAic2tpcCB0aGUgYmluZHMiIC0tIGl0IGlzICJsZWF2ZSB0aGlzCiMgVFYgc3RvY2siLiBUaGUgYmluZHMgY2FuIGJlIHVuZG9uZSwgYnV0IHRoZSBtZWRpYSByZWdpc3RyeSBjYW5ub3Q6IGl0IGlzCiMgY29tbWl0dGVkIHdpdGggYGNwIC1mYCwgYW5kIGFueSByZWdpc3RyeSBXRSBnZW5lcmF0ZWQgd2FzIHNjYW5uZWQgd2l0aAojIC92YXIvbGliL3dlYm9zYnJldy9kdHMyNSBvbiB0aGUgcGx1Z2luIHBhdGgsIHNvIGl0IHJlZ2lzdGVycyBPVVIgZHRzZGVjIGJ5CiMgYWJzb2x1dGUgcGF0aCBhbmQga2VlcHMgZG9pbmcgc28gc3lzdGVtLXdpZGUgKGV2ZXJ5IG9uZSBvZiB0aGUgMjcgamFpbCB2aWV3cykKIyBsb25nIGFmdGVyIHRoZSBiaW5kcyBhcmUgZ29uZS4gRHJvcHBpbmcgYmluZHMgd2hpbGUgbGVhdmluZyB0aGF0IHJlZ2lzdHJ5IGxpdmUKIyBpcyBleGFjdGx5IHRoZSBzdGF0ZSB0aGUgZ2F0ZSBleGlzdHMgdG8gcHJldmVudCAtLSBhbmQgaXQgaXMgdGhlIHN0YXRlIGFuIE9UQQojIHRoYXQgY2hhbmdlcyB0aGUgc3RvY2sgcGx1Z2lucyB3aGlsZSBHU3RyZWFtZXIgc3RheXMgMS4yNCB3b3VsZCBsZWF2ZSBiZWhpbmQuCiMKIyBJZGVtcG90ZW50IGFuZCBzZWxmLWxpbWl0aW5nOiB3MjVfc3RvY2tfcmVnaXN0cnkgc2NhbnMgTEcncyBwbHVnaW4gZGlyZWN0b3JpZXMKIyBPTkxZLCBzbyB0aGUgcmVnaXN0cnkgaXQgd3JpdGVzIGRvZXMgbm90IG5hbWUgL3Zhci9saWIvd2Vib3NicmV3IGFuZCB0aGUgbmV4dAojIHcyNV9yZWdfaXNfb3VycyBpcyBmYWxzZSAtLSBubyByZXBlYXRlZCA2MHMgcmVnZW4gb24gZXZlcnkgYm9vdC4gSXQgYWxzbyB3b3JrcwojIHdoZW4gb3VyIGxpYnJhcmllcyBhcmUgYWxyZWFkeSBnb25lLCBmb3IgdGhlIHNhbWUgcmVhc29uLgp3MjVfc3RhbmRfZG93bigpIHsKICB3MjVfZHJvcF9iaW5kcwogIGlmIHcyNV9yZWdfaXNfb3VyczsgdGhlbgogICAgdzI1X2xvZyAiYSByZWdpc3RyeSBvZiBvdXJzIGlzIHN0aWxsIGxpdmU7IHJlZ2VuZXJhdGluZyB0aGUgc3RvY2sgcmVnaXN0cnkgc28gbm90aGluZyBvZiBvdXJzIHN0YXlzIHJlZ2lzdGVyZWQiCiAgICB3MjVfc3RvY2tfcmVnaXN0cnkKICBmaQogIHJldHVybiAwCn0KdzI1X21kNSgpIHsgWyAtZiAiJDEiIF0gfHwgcmV0dXJuIDA7IG1kNXN1bSAiJDEiIDI+L2Rldi9udWxsIHwgY3V0IC1kIiAiIC1mMTsgfQp3MjVfYm91bmQoKSB7IGlmIGdyZXAgLXEgIiAkMSAiIC9wcm9jL21vdW50cyAyPi9kZXYvbnVsbDsgdGhlbiBlY2hvIDE7IGVsc2UgZWNobyAwOyBmaTsgfQp3MjVfZnBfZ2V0KCkgeyBbIC1mICIkRlAiIF0gfHwgcmV0dXJuIDA7IHNlZCAtbiAicy9eJDE9Ly9wIiAiJEZQIiAyPi9kZXYvbnVsbCB8IGhlYWQgLW4xOyB9CncyNV9nc3RfbW0oKSB7IC91c3IvYmluL2dzdC1pbnNwZWN0LTEuMCAtLXZlcnNpb24gMj4vZGV2L251bGwgfCBzZWQgLW4gJ3MvXkdTdHJlYW1lciBcKFswLTldKlwuWzAtOV0qXCkuKi9cMS9wJyB8IGhlYWQgLW4xOyB9CncyNV9wcm9kdWN0X2lkKCkgeyBjb21tYW5kIC12IG55eC1jbWQgPi9kZXYvbnVsbCAyPiYxIHx8IHsgZWNobyB1bmtub3duOyByZXR1cm4gMDsgfTsgdj0kKG55eC1jbWQgRGV2aWNlSW5mbyBxdWVyeSBwcm9kdWN0X2lkIDI+L2Rldi9udWxsIHwgaGVhZCAtbjEpOyBbIC1uICIkdiIgXSB8fCB2PXVua25vd247IGVjaG8gIiR2IjsgfQp3MjVfd2Vib3NfcmVsZWFzZSgpIHsgY29tbWFuZCAtdiBueXgtY21kID4vZGV2L251bGwgMj4mMSB8fCB7IGVjaG8gdW5rbm93bjsgcmV0dXJuIDA7IH07IHY9JChueXgtY21kIE9TSW5mbyBxdWVyeSB3ZWJvc19yZWxlYXNlIDI+L2Rldi9udWxsIHwgaGVhZCAtbjEpOyBbIC1uICIkdiIgXSB8fCB2PXVua25vd247IGVjaG8gIiR2IjsgfQojIE1lYXN1cmUgdGhlIFNUT0NLIGZpbmdlcnByaW50cyBvZiBldmVyeXRoaW5nIHdlIHNoYWRvdywgcGx1cyB0aGUgbGl2ZSBHU3RyZWFtZXIKIyB2ZXJzaW9uLiBXaGlsZSB3ZSBhcmUgRU5BQkxFRCBhIGJpbmQgb2Ygb3VycyBzaGFkb3dzIHRoZSB0YXJnZXQsIHNvIGl0cyBsaXZlCiMgaGFzaCBpcyBPVVJTIGFuZCB0aGUgc3RvY2sgaGFzaCBpcyB1bm1lYXN1cmFibGUgLS0gZmFsbCBiYWNrIHRvIHdoYXQgc3RvY2suZnAKIyByZWNvcmRlZCB3aGVuIGl0IHN0aWxsIHdhcyBwcmlzdGluZS4gU18qID0gbWVhc3VyZWQgbGl2ZSAoZW1wdHkgd2hlbiBib3VuZCksCiMgTV8qID0gZWZmZWN0aXZlIHN0b2NrIGZpbmdlcnByaW50LCBCXyogPSAxIHdoZW4gb3VyIGJpbmQgaXMgcHJlc2VudC4KIwojIFRoZSB0d28gL2V0YyBmaWxlcyBtYXR0ZXIgYXMgbXVjaCBhcyB0aGUgcGx1Z2lucy4gJE1ZQ0ZHIGFuZCAkTVlHQyBhcmUKIyBTTkFQU0hPVFMsIGF3ay1kZXJpdmVkIGF0IGluc3RhbGwgdGltZSBmcm9tIHRoZSBUVidzIG93biBsaXZlCiMgZGV2aWNlX2NvZGVjX2NhcGFiaWxpdHlfY29uZmlnLmpzb24gYW5kIGdzdGNvb2wuY29uZiwgYW5kIHdlIGJpbmQgdGhlbSBvdmVyIHRoZQojIG9yaWdpbmFscyBpbmRlZmluaXRlbHkuIFRob3NlIG9yaWdpbmFscyBvbmx5IGV2ZXIgY2hhbmdlIHZpYSBhbiBPVEEgLS0gZXhhY3RseQojIHRoZSBldmVudCB0aGlzIGdhdGUgZXhpc3RzIHRvIGNhdGNoIC0tIHNvIGFuIHVwZGF0ZSB0aGF0IHJld3JpdGVzIGVpdGhlciBvbmUKIyB3aGlsZSBsZWF2aW5nIHRoZSB0aHJlZSBwbHVnaW5zIGFsb25lIG11c3Qgbm90IHJlYWQgYXMgInZlcmlmaWVkIjogdGhlIGhvb2sKIyB3b3VsZCBzaWxlbnRseSByZXZlcnQgTEcncyBvd24gY29uZmlnIGNoYW5nZSwgc3lzdGVtLXdpZGUsIGZvcmV2ZXIuCiMKIyBSZXNpZHVhbCB3ZSBhcmUgTk9UIGVuZ2luZWVyaW5nIGFyb3VuZDogbGliZ3N0bWF0cm9za2Euc28gaXMgbmVpdGhlciBzaGFkb3dlZAojIG5vciBmaW5nZXJwcmludGVkLCBzbyBhbiBPVEEgdGhhdCBjaGFuZ2VzIGl0cyBBX0RUUyByZXRhZyB3b3VsZCBzaWxlbnRseSBsb3NlCiMgTUtWIERUUy4gVGhhdCBmYWlscyBpbiB0aGUgYWNjZXB0YWJsZSBkaXJlY3Rpb24gLS0gaXQgY29zdHMgb3VyIGNvZGVjIGFuZCBoYXJtcwojIG5vdGhpbmcgZWxzZSAtLSBhbmQgdGhlIGZpdmUtZWxlbWVudCBwcm9vZiBzdGlsbCBwYXNzZXMsIGJlY2F1c2UgaXQgY2hlY2tzIHRoYXQKIyBtYXRyb3NrYWRlbXV4IFJFR0lTVEVSUywgbm90IHdoYXQgY2FwcyBpdCBlbWl0cy4KdzI1X21lYXN1cmUoKSB7CiAgQl9MSUJBVj0kKHcyNV9ib3VuZCAiJExHTElCQVYiKQogIEJfSVNPTVA0PSQodzI1X2JvdW5kICIkTEdJU08iKQogIEJfTVBFR1RTPSQodzI1X2JvdW5kICIkTEdUU0QiKQogIEJfQ0ZHPSQodzI1X2JvdW5kICIkQ0ZHIikKICBCX0dDPSQodzI1X2JvdW5kICIkR0MiKQogIFNfTElCQVY9CiAgU19JU09NUDQ9CiAgU19NUEVHVFM9CiAgU19DRkc9CiAgU19HQz0KICBbICIkQl9MSUJBViIgPSAwIF0gJiYgU19MSUJBVj0kKHcyNV9tZDUgIiRMR0xJQkFWIikKICBbICIkQl9JU09NUDQiID0gMCBdICYmIFNfSVNPTVA0PSQodzI1X21kNSAiJExHSVNPIikKICBbICIkQl9NUEVHVFMiID0gMCBdICYmIFNfTVBFR1RTPSQodzI1X21kNSAiJExHVFNEIikKICBbICIkQl9DRkciID0gMCBdICYmIFNfQ0ZHPSQodzI1X21kNSAiJENGRyIpCiAgWyAiJEJfR0MiID0gMCBdICYmIFNfR0M9JCh3MjVfbWQ1ICIkR0MiKQogIE1fTElCQVY9JFNfTElCQVYKICBNX0lTT01QND0kU19JU09NUDQKICBNX01QRUdUUz0kU19NUEVHVFMKICBNX0NGRz0kU19DRkcKICBNX0dDPSRTX0dDCiAgWyAtbiAiJE1fTElCQVYiIF0gfHwgTV9MSUJBVj0kKHcyNV9mcF9nZXQgbGliZ3N0bGliYXYpCiAgWyAtbiAiJE1fSVNPTVA0IiBdIHx8IE1fSVNPTVA0PSQodzI1X2ZwX2dldCBsaWJnc3Rpc29tcDQpCiAgWyAtbiAiJE1fTVBFR1RTIiBdIHx8IE1fTVBFR1RTPSQodzI1X2ZwX2dldCBsaWJnc3RtcGVndHNkZW11eCkKICBbIC1uICIkTV9DRkciIF0gfHwgTV9DRkc9JCh3MjVfZnBfZ2V0IGRldmljZV9jb2RlY19jYXBhYmlsaXR5X2NvbmZpZykKICBbIC1uICIkTV9HQyIgXSB8fCBNX0dDPSQodzI1X2ZwX2dldCBnc3Rjb29sKQogIEdTVF9NTV9OT1c9JCh3MjVfZ3N0X21tKQogIFsgLW4gIiRHU1RfTU1fTk9XIiBdIHx8IEdTVF9NTV9OT1c9dW5rbm93bgogIHJldHVybiAwCn0KIyBSZWNvcmRlZC12cy1tZWFzdXJlZCBjb21wYXJpc29uIHRoYXQgdHJlYXRzICJ3ZSBoYXZlIG5vIHJlY29yZGVkIHZhbHVlIiBhcwojIGFic2VuY2Ugb2YgZXZpZGVuY2UgcmF0aGVyIHRoYW4gYXMgZHJpZnQuIE5lZWRlZCBmb3IgdGhlIHR3byAvZXRjIGtleXMsIHdoaWNoIGEKIyBzdG9jay5mcCB3cml0dGVuIGJ5IGFuIGVhcmxpZXIgYnVpbGQgc2ltcGx5IGRvZXMgbm90IGNvbnRhaW4gLS0gY29tcGFyaW5nIGFuCiMgZW1wdHkgcmVjb3JkaW5nIGFnYWluc3QgYSByZWFsIGhhc2ggd291bGQgcmVwb3J0IGRyaWZ0IG9uIGV2ZXJ5IHVwZ3JhZGUuCncyNV9mcF9kaWZmZXJzKCkgeyBbIC1uICIkMSIgXSAmJiBbIC1uICIkMiIgXSAmJiBbICIkMSIgIT0gIiQyIiBdOyB9CiMgR3VhcmQgbGF5ZXIgMDogb3VyIGJpbmQtb3ZlciBsaWJzIGFyZSBhcm1lbCBHU3RyZWFtZXItMS4yNCBidWlsZHMuIEJpbmRpbmcKIyB0aGVtIG92ZXIgYSBkaWZmZXJlbnQtQUJJIExHIGxpYiBhZnRlciBhbiBPVEEgd291bGQgYnJlYWsgQUxMIG1wNC90cy9ta3YKIyBwbGF5YmFjaywgYW5kIG5vIG9wdC1pbiBtYXkgb3ZlcnJpZGUgdGhhdC4KdzI1X2dzdF9vaygpIHsgWyAiJEdTVF9NTV9OT1ciID0gIiRFWFBFQ1RfR1NUIiBdOyB9CiMgR2F0ZSBsYXllciAxIC0tIGlkZW50aXR5LiBTZXRzIFZFUkRJQ1QgUkVBU09OIExBQkVMIENBTkZPUkNFIGZyb20gdGhlIG1lYXN1cmVkCiMgc3RvY2sgZmluZ2VycHJpbnRzOgojICAgdmVyaWZpZWQgICB0aGUgbWQ1cyBhcmUgaW4gdGhlIHZlcmlmaWVkLXNldHMgdGFibGUgYmVsb3cKIyAgIGZvcmNlZCAgICAgbm8gdGFibGUgbWF0Y2gsIGJ1dCB0aGUgdXNlciBvcHRlZCBpbiBhbmQgbm90aGluZyBjaGFuZ2VkIHNpbmNlCiMgICBkcmlmdCAgICAgIHN0b2NrLmZwIHJlY29yZGVkIERJRkZFUkVOVCBtZDVzIC0+IGZpcm13YXJlIHVwZGF0ZSwgc3RhbmQgZG93bgojICAgICAgICAgICAgICBVTkNPTkRJVElPTkFMTFkgKEZPUkNFIGNhbm5vdCBvdmVycmlkZSBpdCwgYW5kIG5laXRoZXIgY2FuIHRoZQojICAgICAgICAgICAgICBBQkktY2hhbmdlIGRyaWZ0IHcyNV9nYXRlIHJlcG9ydHMpCiMgICB1bnZlcmlmaWVkIG5vIG1hdGNoIGFuZCBubyBvcHQtaW4gLT4gYmluZCBub3RoaW5nCiMgVGhlIG1kNSBvZiB0aGUgc3RvY2sgbGlicyBpcyB0aGUga2V5LCBub3QgdGhlIG1vZGVsIG5hbWU6IGlkZW50aWNhbCBoYXNoZXMKIyBtZWFuIHRoZXNlIGFyZSBsaXRlcmFsbHkgdGhlIGxpYnJhcmllcyB0aGUgcGF5bG9hZCB3YXMgdmVyaWZpZWQgYWdhaW5zdC4KdzI1X3ZlcmRpY3QoKSB7CiAgVkVSRElDVD11bnZlcmlmaWVkCiAgUkVBU09OPQogIExBQkVMPQogIENBTkZPUkNFPTAKICBpZiBbIC16ICIkTV9MSUJBViIgXSB8fCBbIC16ICIkTV9JU09NUDQiIF0gfHwgWyAteiAiJE1fTVBFR1RTIiBdOyB0aGVuCiAgICBSRUFTT049InRoZSBzdG9jayBHU3RyZWFtZXIgcGx1Z2luIGZpbmdlcnByaW50cyBjb3VsZCBub3QgYmUgcmVhZCBvbiB0aGlzIFRWIgogICAgcmV0dXJuIDAKICBmaQogICMgRFJJRlQgSVMgQ0hFQ0tFRCBCRUZPUkUgVEhFIFRBQkxFLCBhbmQgdGhhdCBvcmRlcmluZyBpcyBsb2FkLWJlYXJpbmcuIFRoZQogICMgdGFibGUgY2FuIG9ubHkga2V5IG9uIGdzdF9tbSArIHRoZSB0aHJlZSBwbHVnaW4gbWQ1cywgc28gaXQgY2Fubm90IGV4cHJlc3MgdGhlCiAgIyBzdGF0ZSBvZiB0aGUgdHdvIC9ldGMgZmlsZXMgLS0gd2hpY2ggbWVhbnMgYSB0YWJsZSBtYXRjaCB3b3VsZCByZXR1cm4KICAjIGB2ZXJpZmllZGAgYW5kIG1hc2sgYW4gT1RBIHRoYXQgcmV3cm90ZSBvbmx5IGdzdGNvb2wuY29uZiBvciB0aGUgY29kZWMKICAjIGNhcGFiaWxpdHkgSlNPTi4gIkhhcyB0aGlzIFRWIGNoYW5nZWQgc2luY2Ugd2UgcmVjb3JkZWQgaXQiIHRoZXJlZm9yZSBvdXRyYW5rcwogICMgImRvZXMgdGhpcyBUViBsb29rIGxpa2UgYSBrbm93bi1nb29kIG9uZSIuCiAgRlBfQVY9JCh3MjVfZnBfZ2V0IGxpYmdzdGxpYmF2KQogIEZQX0lTTz0kKHcyNV9mcF9nZXQgbGliZ3N0aXNvbXA0KQogIEZQX1RTRD0kKHcyNV9mcF9nZXQgbGliZ3N0bXBlZ3RzZGVtdXgpCiAgRlBfQ0ZHPSQodzI1X2ZwX2dldCBkZXZpY2VfY29kZWNfY2FwYWJpbGl0eV9jb25maWcpCiAgRlBfR0M9JCh3MjVfZnBfZ2V0IGdzdGNvb2wpCiAgIyBUaGUgdGhyZWUgcGx1Z2luIGhhc2hlcyBjb21wYXJlIHN0cmljdGx5ICh0aGV5IGhhdmUgYWx3YXlzIGJlZW4gcmVjb3JkZWQpLgogICMgVGhlIHR3byAvZXRjIGhhc2hlcyBnbyB0aHJvdWdoIHcyNV9mcF9kaWZmZXJzIHNvIGFuIG9sZGVyIHN0b2NrLmZwIHRoYXQgbmV2ZXIKICAjIHJlY29yZGVkIHRoZW0gZG9lcyBub3QgcmVhZCBhcyBkcmlmdC4KICBEUklGVF9XSEFUPQogIERSSUZUX1BMVUdJTlM9MAogIERSSUZUX0NPTkZJRz0wCiAgWyAiJEZQX0FWIiAhPSAiJE1fTElCQVYiIF0gJiYgeyBEUklGVF9XSEFUPSIke0RSSUZUX1dIQVQ6KyREUklGVF9XSEFUIH1saWJnc3RsaWJhdi5zbyI7IERSSUZUX1BMVUdJTlM9MTsgfQogIFsgIiRGUF9JU08iICE9ICIkTV9JU09NUDQiIF0gJiYgeyBEUklGVF9XSEFUPSIke0RSSUZUX1dIQVQ6KyREUklGVF9XSEFUIH1saWJnc3Rpc29tcDQuc28iOyBEUklGVF9QTFVHSU5TPTE7IH0KICBbICIkRlBfVFNEIiAhPSAiJE1fTVBFR1RTIiBdICYmIHsgRFJJRlRfV0hBVD0iJHtEUklGVF9XSEFUOiskRFJJRlRfV0hBVCB9bGliZ3N0bXBlZ3RzZGVtdXguc28iOyBEUklGVF9QTFVHSU5TPTE7IH0KICB3MjVfZnBfZGlmZmVycyAiJEZQX0NGRyIgIiRNX0NGRyIgJiYgeyBEUklGVF9XSEFUPSIke0RSSUZUX1dIQVQ6KyREUklGVF9XSEFUIH1kZXZpY2VfY29kZWNfY2FwYWJpbGl0eV9jb25maWcuanNvbiI7IERSSUZUX0NPTkZJRz0xOyB9CiAgdzI1X2ZwX2RpZmZlcnMgIiRGUF9HQyIgIiRNX0dDIiAmJiB7IERSSUZUX1dIQVQ9IiR7RFJJRlRfV0hBVDorJERSSUZUX1dIQVQgfWdzdGNvb2wuY29uZiI7IERSSUZUX0NPTkZJRz0xOyB9CiAgaWYgWyAtbiAiJEZQX0FWJEZQX0lTTyRGUF9UU0QiIF0gJiYgWyAtbiAiJERSSUZUX1dIQVQiIF07IHRoZW4KICAgICMgVU5DT05ESVRJT05BTCByZWZ1c2FsIC0tIEZPUkNFIGlzIGRlbGliZXJhdGVseSBub3QgY29uc3VsdGVkIGhlcmUsIGFuZAogICAgIyBDQU5GT1JDRT0wIHNvIG5vdGhpbmcgYWR2ZXJ0aXNlcyBhbiBlc2NhcGUgaGF0Y2ggdGhhdCBkb2VzIG5vdCBleGlzdC4KICAgICMgQSBkcmlmdC1zcGVjaWZpYyBvdmVycmlkZSB3b3VsZCBiZSByZWR1bmRhbnQ6IHVuaW5zdGFsbCByZW1vdmVzIHN0b2NrLmZwLAogICAgIyBzbyB1bmluc3RhbGwtdGhlbi1lbmFibGUgcHV0cyB0aGlzIFRWIGJhY2sgaW50byB0aGUgInVudmVyaWZpZWQiIGZsb3csIHdoaWNoCiAgICAjIGFscmVhZHkgaGFzIGFuIGV4cGxpY2l0LCBjb25zZW50ZWQgb3B0LWluLiBSZWZ1c2luZyBvdXRyaWdodCBrZWVwcyB0aGUgc3RhdGUKICAgICMgbWFjaGluZSBzbWFsbGVyIGFuZCB0aGUgcnVsZSBhYnNvbHV0ZTogYSBmaXJtd2FyZSBjaGFuZ2UgdGhhdCB0b3VjaGVzIHRoZQogICAgIyBwbHVnaW5zIHdlIHNoYWRvdyBzdGFuZHMgdXMgZG93biwgZnVsbCBzdG9wLgogICAgVkVSRElDVD1kcmlmdAogICAgQ0FORk9SQ0U9MAogICAgIyBUaGUgcmVtZWR5IGRlcGVuZHMgb24gV0hBVCBkcmlmdGVkLiBBIHBsdWdpbiBjaGFuZ2UgaXMgc29tZXRoaW5nIGEgdmVyaWZpZWQKICAgICMgc2V0IGNhbiBkZXNjcmliZSwgc28gdGhlIGZpbmdlcnByaW50cyBhcmUgd29ydGggcmVwb3J0aW5nLiBBIGNoYW5nZSB0byB0aGUKICAgICMgdHdvIC9ldGMgZmlsZXMgaXMgTk9UOiBubyB0YWJsZSByb3cgY2FuIGV2ZXIgY2xlYXIgaXQsIGJlY2F1c2UgdGhlIHRhYmxlCiAgICAjIGtleXMgb24gcGx1Z2lucyBvbmx5IC0tIHRoZSBzbmFwc2hvdHMgc2ltcGx5IGhhdmUgdG8gYmUgcmV0YWtlbiBmcm9tIHRoZQogICAgIyBUVidzIG5ldyBjb25maWcsIHdoaWNoIGlzIHdoYXQgRW5hYmxlIGRvZXMuCiAgICBpZiBbICIkRFJJRlRfUExVR0lOUyIgPSAxIF0gJiYgWyAiJERSSUZUX0NPTkZJRyIgPSAxIF07IHRoZW4KICAgICAgRFJJRlRfRklYPSJ1bmluc3RhbGwgdGhlbiBlbmFibGUgYWdhaW4gdG8gcmUtc25hcHNob3QgdGhpcyBUVidzIGNvbmZpZ3VyYXRpb24sIGFuZCByZXBvcnQgdGhlIG5ldyBwbHVnaW4gZmluZ2VycHJpbnRzIHNvIHRoaXMgVFYgY2FuIGJlIGFkZGVkIHRvIHRoZSB2ZXJpZmllZCB0YWJsZSIKICAgIGVsaWYgWyAiJERSSUZUX1BMVUdJTlMiID0gMSBdOyB0aGVuCiAgICAgIERSSUZUX0ZJWD0icmVwb3J0IHRoZSBuZXcgZmluZ2VycHJpbnRzIHNvIHRoaXMgVFYgY2FuIGJlIGFkZGVkIHRvIHRoZSB2ZXJpZmllZCB0YWJsZSwgb3IgdW5pbnN0YWxsIHRoZW4gZW5hYmxlIGFnYWluIHRvIG9wdCBpbiBleHBsaWNpdGx5IgogICAgZWxzZQogICAgICBEUklGVF9GSVg9InVuaW5zdGFsbCB0aGVuIGVuYWJsZSBhZ2FpbiB0byByZS1zbmFwc2hvdCB0aGlzIFRWJ3MgY29uZmlndXJhdGlvbiAobm8gdmVyaWZpZWQtc2V0IGVudHJ5IGNhbiBjb3ZlciBhIGNvbmZpZyBjaGFuZ2UpIgogICAgZmkKICAgIFJFQVNPTj0idGhpcyBUViBjaGFuZ2VkIHNpbmNlIGl0IHdhcyBsYXN0IHZlcmlmaWVkICgkRFJJRlRfV0hBVCksIHNvIG5vdGhpbmcgd2FzIGFwcGxpZWQ7ICREUklGVF9GSVgiCiAgICByZXR1cm4gMAogIGZpCiAgIyBUaGUgdGFibGUga2V5cyBvbiBwbHVnaW4gaGFzaGVzLCB3aGljaCBhcmUgTk9UIG1vZGVsLXVuaXF1ZTogYSBHNS9NNSBzaGlwcwogICMgYnl0ZS1pZGVudGljYWwgY29waWVzIG9mIGFsbCB0aHJlZSwgc28gYSBoYXNoLW9ubHkgbWF0Y2ggcmVwb3J0ZWQgYHZlcmlmaWVkYAogICMgd2l0aCB0aGUgQzUncyBsYWJlbCBvbiBoYXJkd2FyZSBub2JvZHkgaGFkIGV2ZXIgdGVzdGVkLiBUaGF0IGlzIGEgZmFsc2UKICAjIGhhcmR3YXJlLXZlcmlmaWNhdGlvbiBjbGFpbSwgc28gdGhlIHJvdyBub3cgYWxzbyBjYXJyaWVzIGEgcHJvZHVjdC1pZCBnbG9iIGFuZAogICMgdGhlIHR3byBjYXNlcyBhcmUga2VwdCBhcGFydDoKICAjICAgaGFzaGVzIG1hdGNoIEFORCBwcm9kdWN0IG1hdGNoZXMgLT4gdmVyaWZpZWQgICAodGhpcyBtb2RlbCByZWFsbHkgd2FzIHRlc3RlZCkKICAjICAgaGFzaGVzIG1hdGNoLCBwcm9kdWN0IGRvZXMgbm90ICAgLT4gdW52ZXJpZmllZCArIENBTkZPUkNFIChiaW5hcnktc2V0IG1hdGNoCiAgIyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgb25seTsgc3Ryb25nZXN0IHBvc3NpYmxlIG5vbi1oYXJkd2FyZQogICMgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGV2aWRlbmNlLCBzbyB0aGUgZXhpc3RpbmcgZXhwbGljaXQgb3B0LWluCiAgIyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgaXMgdGhlIHJpZ2h0IGdhdGUgcmF0aGVyIHRoYW4gYXV0by1hcHBseSkKICBQUk9EVUNUX05PVz0kKHcyNV9wcm9kdWN0X2lkKQogIHdoaWxlIElGUz0nfCcgcmVhZCAtciB0X21tIHRfYXYgdF9pc28gdF90c2QgdF9wcm9kdWN0IHRfbGFiZWw7IGRvCiAgICBjYXNlICIkdF9tbSIgaW4gJyd8XCMqKSBjb250aW51ZSA7OyBlc2FjCiAgICBpZiBbICIkdF9tbSIgPSAiJEdTVF9NTV9OT1ciIF0gJiYgWyAiJHRfYXYiID0gIiRNX0xJQkFWIiBdICYmIFsgIiR0X2lzbyIgPSAiJE1fSVNPTVA0IiBdICYmIFsgIiR0X3RzZCIgPSAiJE1fTVBFR1RTIiBdOyB0aGVuCiAgICAgICMgUm93cyBjYW4gc2hhcmUgaGFzaGVzIC0tIGEgQzUgYW5kIGEgRzUgYXJlIGJ5dGUtaWRlbnRpY2FsIG9uIGFsbCB0aHJlZSAtLSBzbwogICAgICAjIGRvIE5PVCBzdG9wIGF0IHRoZSBmaXJzdCBoYXNoIG1hdGNoLiBLZWVwIHNjYW5uaW5nIGZvciBhIHJvdyB3aG9zZSBwcm9kdWN0CiAgICAgICMgZ2xvYiBhbHNvIG1hdGNoZXMsIGFuZCBvbmx5IHJlbWVtYmVyIHRoZSBoYXNoLW9ubHkgbWF0Y2ggYXMgYSBmYWxsYmFjay4KICAgICAgIyBCcmVha2luZyBlYXJseSBoZXJlIG1hZGUgdGhlIGZpcnN0IG1hdGNoaW5nIHJvdyB3aW4sIHNvIGEgRzUgY291bGQgbmV2ZXIKICAgICAgIyByZWFjaCBpdHMgb3duIHJvdyBhbmQgd2FzIHJlcG9ydGVkIHVudGVzdGVkIGRlc3BpdGUgYmVpbmcgbGlzdGVkLgogICAgICBjYXNlICIkUFJPRFVDVF9OT1ciIGluCiAgICAgICAgJHRfcHJvZHVjdCkKICAgICAgICAgIExBQkVMPSR0X2xhYmVsCiAgICAgICAgICBWRVJESUNUPXZlcmlmaWVkCiAgICAgICAgICBSRUFTT049InN0b2NrIHBsdWdpbiBmaW5nZXJwcmludHMgbWF0Y2ggYSBUViB0aGlzIHBheWxvYWQgd2FzIHZlcmlmaWVkIG9uIgogICAgICAgICAgYnJlYWsKICAgICAgICAgIDs7CiAgICAgICAgKikKICAgICAgICAgIGlmIFsgIiRWRVJESUNUIiAhPSB1bnZlcmlmaWVkIF0gfHwgWyAiJENBTkZPUkNFIiAhPSAxIF07IHRoZW4KICAgICAgICAgICAgTEFCRUw9JHRfbGFiZWwKICAgICAgICAgICAgVkVSRElDVD11bnZlcmlmaWVkCiAgICAgICAgICAgIENBTkZPUkNFPTEKICAgICAgICAgICAgUkVBU09OPSJ0aGlzIFRWJ3Mgc3RvY2sgcGx1Z2lucyBhcmUgYnl0ZS1pZGVudGljYWwgdG8gJHRfbGFiZWwsIHNvIHRoZSBwYXlsb2FkIGlzIHZlcnkgbGlrZWx5IGNvbXBhdGlibGUgLS0gYnV0IFRISVMgbW9kZWwgKCRQUk9EVUNUX05PVykgaGFzIG5ldmVyIGJlZW4gdGVzdGVkIG9uIGhhcmR3YXJlLCBzbyBpdCBpcyBub3QgcmVwb3J0ZWQgYXMgdmVyaWZpZWQuIE9wdCBpbiBleHBsaWNpdGx5IHRvIHRyeSBpdCwgYW5kIHBsZWFzZSByZXBvcnQgdGhlIHJlc3VsdCBzbyBpdCBjYW4gYmUgYWRkZWQgcHJvcGVybHkiCiAgICAgICAgICBmaQogICAgICAgICAgOzsKICAgICAgZXNhYwogICAgZmkKICBkb25lIDw8J1cyNV9TRVRTJwojIGdzdF9tbXxsaWJnc3RsaWJhdnxsaWJnc3Rpc29tcDR8bGliZ3N0bXBlZ3RzZGVtdXh8cHJvZHVjdF9pZF9nbG9ifGxhYmVsCiMgcHJvZHVjdF9pZF9nbG9iIG11c3QgYmUgYSBzaGVsbCBnbG9iIG1hdGNoZWQgYWdhaW5zdCBueXgtY21kIHByb2R1Y3RfaWQuIE9ubHkgYWRkCiMgYSByb3cgd2l0aCBhIHJlYWwgcHJvZHVjdCBnbG9iIGFmdGVyIERUUyBhbmQgVHJ1ZUhEIGhhdmUgYWN0dWFsbHkgcGxheWVkIG9uIHRoYXQKIyBtb2RlbCAtLSBhIGJ5dGUtaWRlbnRpY2FsIGFydGlmYWN0IHNldCBpcyBOT1QgaGFyZHdhcmUgdmVyaWZpY2F0aW9uLgoxLjI0fDBmZDZkNjVhYzllM2E3OGIzOTNhNjE1ZWFmZjhhYzBifDU3ZmU1NzA2MDc3NGYyNDhjMDVhZjVhNDExZmM5YThmfDliODRhOTVjZjI5YmMwMjU1NTNjN2RlZTgyOWI3Y2MxfE9MRUQqQzUqfExHIEM1IE9MRUQ3N0M1MUxBICh3ZWJPUyAxMC4zLjEsIEdTdHJlYW1lciAxLjI0LjApCiMgRzU6IG93bmVyLXJlcG9ydGVkIHdvcmtpbmcgb24gZmlybXdhcmUgMzMuMzAuOTcgLS0gRFRTIHBsYXllZCBpbiBNS1YsIE1QNCBhbmQgVFMKIyBhZnRlciBlbmFibGluZy4gSXRzIDMzLjMxLjY4IHBsdWdpbiBoYXNoZXMgYXJlIGJ5dGUtaWRlbnRpY2FsIHRvIHRoZSBDNSByb3cgYWJvdmUsCiMgc28gdGhlIHNhbWUgcm93IG5vdyBjb3ZlcnMgYm90aCBtb2RlbHMuIFRydWVIRCBvbiB0aGUgRzUgd2FzIHJlcG9ydGVkIGFzIHBsYXlpbmcKIyB3aXRoIGludGVycnVwdGlvbnM7IERUUyB3YXMgY2xlYW4uCjEuMjR8MGZkNmQ2NWFjOWUzYTc4YjM5M2E2MTVlYWZmOGFjMGJ8NTdmZTU3MDYwNzc0ZjI0OGMwNWFmNWE0MTFmYzlhOGZ8OWI4NGE5NWNmMjliYzAyNTU1M2M3ZGVlODI5YjdjYzF8T0xFRCpHNSp8TEcgRzUgT0xFRDc3RzU1TFcgKHdlYk9TIDEwLjMuMSwgR1N0cmVhbWVyIDEuMjQuMCkKVzI1X1NFVFMKICBbICIkVkVSRElDVCIgPSB2ZXJpZmllZCBdICYmIHJldHVybiAwCiAgIyBBIGhhc2ggbWF0Y2ggb24gYW4gdW50ZXN0ZWQgbW9kZWwgbGVhdmVzIFZFUkRJQ1Q9dW52ZXJpZmllZCArIENBTkZPUkNFPTEgYW5kIG11c3QKICAjIHN0aWxsIGZhbGwgdGhyb3VnaCB0byB0aGUgb3B0LWluIGhhbmRsaW5nIGJlbG93LiBSZXR1cm5pbmcgaGVyZSBpbnN0ZWFkIG1hZGUKICAjIEZPUkNFPTEgdW5yZWFjaGFibGUsIHNvICJUcnkgYW55d2F5IiByZXBvcnRlZCB0aGUgc2FtZSByZWZ1c2FsIGFzIEVuYWJsZSAtLSB0aGUKICAjIG1lc3NhZ2UgdG9sZCB0aGUgdXNlciB0byBvcHQgaW4gYW5kIHRoZW4gaWdub3JlZCB0aGVtLiBLZWVwIHRoZSByZWFzb24vbGFiZWwgZnJvbQogICMgdGhlIHRhYmxlICh0aGV5IGFyZSBtb3JlIHNwZWNpZmljIHRoYW4gdGhlIGdlbmVyaWMgbm8tbWF0Y2ggdGV4dCkgYW5kIG9ubHkgc2tpcAogICMgdGhlIGNsb3NpbmcgZ2VuZXJpYyBhc3NpZ25tZW50LgogIFRBQkxFX05FQVJfTUFUQ0g9MAogIFsgIiRWRVJESUNUIiA9IHVudmVyaWZpZWQgXSAmJiBbICIkQ0FORk9SQ0UiID0gMSBdICYmIFRBQkxFX05FQVJfTUFUQ0g9MQogIGlmIFsgIiQodzI1X2ZwX2dldCBmb3JjZWQpIiA9IDEgXSAmJiBbIC1uICIkRlBfQVYiIF07IHRoZW4KICAgIFZFUkRJQ1Q9Zm9yY2VkCiAgICBDQU5GT1JDRT0xCiAgICBSRUFTT049Im5vdCBhIHZlcmlmaWVkIFRWLCBidXQgeW91IG9wdGVkIGluIGFuZCBub3RoaW5nIGhhcyBjaGFuZ2VkIHNpbmNlIgogICAgcmV0dXJuIDAKICBmaQogIGlmIFsgIiR7Rk9SQ0U6LTB9IiA9IDEgXTsgdGhlbgogICAgVkVSRElDVD1mb3JjZWQKICAgIENBTkZPUkNFPTEKICAgIFJFQVNPTj0ibm90IGEgdmVyaWZpZWQgVFY7IGFwcGx5aW5nIGJlY2F1c2UgeW91IGV4cGxpY2l0bHkgb3B0ZWQgaW4iCiAgICByZXR1cm4gMAogIGZpCiAgQ0FORk9SQ0U9MQogIFsgIiRUQUJMRV9ORUFSX01BVENIIiA9IDEgXSB8fCBSRUFTT049InRoaXMgVFYncyBzdG9jayBHU3RyZWFtZXIgcGx1Z2lucyBtYXRjaCBubyBUViB0aGlzIHBheWxvYWQgd2FzIHZlcmlmaWVkIG9uIgogIHJldHVybiAwCn0KIyBWZXJzaW9uIGd1YXJkICsgaWRlbnRpdHkgZ2F0ZSBhcyBvbmUgY2FsbCwgZm9yIHRoZSByZWFkLW9ubHkgY2FsbGVycyAodGhlCiMgYXBwJ3MgcHJvYmUgYW5kIFcyNV9DSEVDSz0xKS4gVGhlIGFwcGx5IHBhdGggYmVsb3cgcnVucyB0aGUgdHdvIGFzIHNlcGFyYXRlCiMgb3JkZXJlZCBzdGVwcyBzbyBlYWNoIGdldHMgaXRzIG93biBsb2cgbGluZSBhbmQgdG9hc3QuCncyNV9nYXRlKCkgewogIHcyNV9nc3Rfb2sgJiYgeyB3MjVfdmVyZGljdDsgcmV0dXJuIDA7IH0KICBWRVJESUNUPWRyaWZ0CiAgQ0FORk9SQ0U9MAogIExBQkVMPQogIFJFQVNPTj0iR1N0cmVhbWVyICRHU1RfTU1fTk9XIGlzIG5vdCB0aGUgJEVYUEVDVF9HU1QgdGhpcyBwYXlsb2FkIHdhcyBidWlsdCBmb3I7IGEgZmlybXdhcmUgdXBkYXRlIGNoYW5nZWQgdGhlIHBsdWdpbiBBQkkiCiAgcmV0dXJuIDAKfQp3MjVfbG9hZGVyKCkgewogIGZvciBmIGluIC9saWIvbGQtbGludXguc28uMyAvbGliL2xkLWxpbnV4LWFybWhmLnNvLjMgL2xpYi9sZC1saW51eC5zby4yIC9saWIvbGQtbGludXgqLnNvLiogL2xpYi9sZC0qLnNvLio7IGRvCiAgICBbIC14ICIkZiIgXSAmJiB7IHByaW50ZiAnJXNcbicgIiRmIjsgcmV0dXJuIDA7IH0KICBkb25lCiAgcmV0dXJuIDEKfQojIEdhdGUgbGF5ZXIgMmEgLS0gbG9hZGVyIHJlc29sdXRpb24uIEV2ZXJ5IHBheWxvYWQgb2JqZWN0IHdlIGFyZSBhYm91dCB0byBiaW5kCiMgb3IgcmVnaXN0ZXIgbXVzdCBoYXZlIEFMTCBpdHMgZHluYW1pYyBkZXBlbmRlbmNpZXMgcmVzb2x2YWJsZSBvbiBUSElTIFRWLgojIFRoZSBhc3NlcnRpb24gaXMgdGhhdCBPVVIgZGVwcyByZXNvbHZlLCBOT1QgdGhhdCBvdXIgc29uYW1lcyBtYXRjaCBMRydzOgojIHN0b2NrIGxpYmF2IG9uIHRoZSB2ZXJpZmllZCBDNSBpcyBmZm1wZWcgNS54IChsaWJhdmNvZGVjLnNvLjU5LAojIGxpYmF2Zm9ybWF0LnNvLjU5LCBsaWJhdnV0aWwuc28uNTcsIGxpYmF2ZmlsdGVyLnNvLjgpIHdoaWxlIG91cnMgaXMgZmZtcGVnIDQuNAojICguNTgvLjU4Ly41Ni8uNyksIHNvIGEgc29uYW1lLWVxdWFsaXR5IGNoZWNrIGFnYWluc3Qgc3RvY2sgd291bGQgcmVmdXNlIGEgVFYKIyB3aGVyZSB0aGUgcGF5bG9hZCBkZW1vbnN0cmFibHkgd29ya3MuIE91ciBvYmplY3RzIGNhcnJ5CiMgUlVOUEFUSD0vdmFyL2xpYi93ZWJvc2JyZXcvdHJ1ZWhkL2xpYnM7ICRNWUxJQlMgaXMga2VwdCBmb3IgdGhlIGR0czI1L2xpYnMgY2FzZS4KIyBMT0FERVJfU1RBR0VEIGRpc3Rpbmd1aXNoZXMgInRoZXNlIGxpYnJhcmllcyBjYW5ub3QgbG9hZCBvbiB0aGlzIFRWIiAoYSByZWFsCiMgcmVmdXNhbCwgYW5kIGZvcmNpbmcgd291bGQgbm90IGhlbHApIGZyb20gInRoZSBjb3JlIHBheWxvYWQgaXMgbm90IHN0YWdlZCIgKHRoZQojIHN0YXRlIGJlZm9yZSB0aGUgZmlyc3QgRW5hYmxlLCB3aGVyZSB0aGUgYW5zd2VyIGlzIHNpbXBseSBub3Qga25vd24pLiBUaGUgYXBwCiMgdXNlcyB0aGF0IHRvIGRlY2lkZSB3aGV0aGVyIG9mZmVyaW5nICJUcnkgYW55d2F5IiB3b3VsZCBiZSBob25lc3QuCiMKIyBPbmx5IHRoZSBDT1JFIG9iamVjdHMgYXJlIHJlcXVpcmVkLiBUaGUgb3B0aW9uYWwgZGVtdXhlcnMgYXJlIGNoZWNrZWQgd2hlbiB0aGV5CiMgYXJlIHN0YWdlZCBhbmQgc2tpcHBlZCB3aGVuIHRoZXkgYXJlIG5vdCwgc28gYSBjb3JlLW9ubHkgaW5zdGFsbCBpcyBhIGZpcnN0CiMgY2xhc3MgY29uZmlndXJhdGlvbiByYXRoZXIgdGhhbiBhIGZhaWx1cmUuCncyNV9jb3JlX3N0YWdlZCgpIHsgWyAtZiAiJE1ZRFRTIiBdICYmIFsgLWYgIiRNWUxJQkFWIiBdOyB9CncyNV9sb2FkZXJfb2soKSB7CiAgTE9BREVSX01JU1M9CiAgTE9BREVSX1NUQUdFRD0xCiAgTERfU089JCh3MjVfbG9hZGVyKQogIGlmIFsgLXogIiR7TERfU086LX0iIF07IHRoZW4gTE9BREVSX01JU1M9Im5vIGR5bmFtaWMgbG9hZGVyIGZvdW5kIG9uIHRoaXMgVFYiOyByZXR1cm4gMTsgZmkKICBpZiAhIHcyNV9jb3JlX3N0YWdlZDsgdGhlbgogICAgTE9BREVSX1NUQUdFRD0wCiAgICBMT0FERVJfTUlTUz0idGhlIGNvcmUgcGF5bG9hZCBpcyBub3Qgc3RhZ2VkICgkTVlEVFMgLyAkTVlMSUJBVikiCiAgICByZXR1cm4gMQogIGZpCiAgZm9yIHNvIGluICIkTVlEVFMiICIkTVlMSUJBViIgIiRNWUlTTyIgIiRNWVRTRCI7IGRvCiAgICBbIC1mICIkc28iIF0gfHwgY29udGludWUKICAgIG49JChMRF9MSUJSQVJZX1BBVEg9IiRNWUxJQlMiIExEX1RSQUNFX0xPQURFRF9PQkpFQ1RTPTEgIiRMRF9TTyIgIiRzbyIgMj4mMSB8IGdyZXAgLWMgIm5vdCBmb3VuZCIpCiAgICBpZiBbICIkbiIgIT0gMCBdOyB0aGVuIExPQURFUl9NSVNTPSIkc28gaGFzICRuIHVucmVzb2x2ZWQgZGVwZW5kZW5jaWVzIG9uIHRoaXMgVFYiOyByZXR1cm4gMTsgZmkKICBkb25lCiAgcmV0dXJuIDAKfQojIElzIHRoZSBsaXZlIG1lZGlhIHJlZ2lzdHJ5IG9uZSBXRSB3cm90ZT8gSXQgaXMgY29tbWl0dGVkIHdpdGggYGNwIC1mYCwgbm90CiMgYmluZC1tb3VudGVkLCBzbyB0aGVyZSBpcyBubyBtb3VudCB0byBsb29rIGZvciAtLSBidXQgYSByZWdpc3RyeSB3ZSBnZW5lcmF0ZWQKIyBuYW1lcyBvdXIgcGx1Z2luIGRpcmVjdG9yaWVzLCBhbmQgYSBzdG9jayBvbmUgbmV2ZXIgZG9lcy4gVGhpcyBpcyB0aGUgc2lnbmFsCiMgZm9yICJhIHJlZ2lzdHJ5IG9mIG91cnMgaXMgbGl2ZSIsIHdoaWNoIG1hdHRlcnMgd2hlbiBvdXIgbGlicmFyaWVzIGhhdmUgZ29uZQojIG1pc3NpbmcgdW5kZXJuZWF0aCBpdC4KdzI1X3JlZ19pc19vdXJzKCkgeyBbIC1mICIkUkVHIiBdICYmIGdyZXAgLXEgIi92YXIvbGliL3dlYm9zYnJldyIgIiRSRUciIDI+L2Rldi9udWxsOyB9CiMgR2F0ZSBsYXllciAyYiAtLSBwb3N0LWJpbmQgcGlwZWxpbmUgcHJvb2YuIFRoZSByZWdlbmVyYXRlZCByZWdpc3RyeSBtdXN0IGNhcnJ5CiMgQUxMIEZJVkUgZWxlbWVudHMgdGhlIERUUy9UcnVlSEQgcGF0aCBuZWVkczogb3VyIHR3byBkZWNvZGVycyBBTkQgdGhlIHRocmVlCiMgZGVtdXhlcnMgd2Ugc2hhZG93IChhbGwgdGhyZWUgYXJlIHByZXNlbnQgaW4gdGhlIG1lZGlhIHJlZ2lzdHJ5IHRvZGF5KS4KIyBBIG1pc3NpbmcgZGVtdXhlciBtZWFucyBvdXIgb3ZlcnJpZGUgcHJvZHVjZWQgYSBwbHVnaW4gdGhlIHJlZ2lzdHJ5IGNhbm5vdAojIHVzZSwgaS5lLiBhIGJyb2tlbiBtcDQvdHMvbWt2IHBpcGVsaW5lIC0tIHNvIHRoZSBjYWxsZXIgcmVmdXNlcyB0aGUgY29tbWl0IGFuZAojIGRyb3BzIHRoZSBiaW5kcywgd2hpY2ggdHVybnMgInRoZSBvdmVycmlkZSBkaWRuJ3QgbWF0Y2giIGludG8gYSBwbGFpbiBuby1vcC4KdzI1X3JlZ19oYXNfYWxsKCkgewogIFJFR19NSVNTPQogIGZvciBlIGluIGR0c2RlYyBhdmRlY190cnVlaGQgcXRkZW11eCB0c2RlbXV4IG1hdHJvc2thZGVtdXg7IGRvCiAgICBHU1RfUkVHSVNUUllfMV8wPSIkMSIgR1NUX1JFR0lTVFJZX1VQREFURT1ubyBHU1RfUkVHSVNUUllfRk9SSz1ubyAvdXNyL2Jpbi9nc3QtaW5zcGVjdC0xLjAgIiRlIiA+L2Rldi9udWxsIDI+JjEgfHwgeyBSRUdfTUlTUz0kZTsgcmV0dXJuIDE7IH0KICBkb25lCiAgcmV0dXJuIDAKfQojIFJlZ2VuZXJhdGUgYSBjbGVhbiBTVE9DSyByZWdpc3RyeSBmcm9tIHRoZSBwcmlzdGluZSBvbi1kaXNrIHBsdWdpbnMgYW5kIHdyaXRlCiMgaXQgb3ZlciB0aGUgbWVkaWEgcmVnaXN0cnkuIFRoZSByZWdpc3RyeSBpcyBjb21taXR0ZWQgd2l0aCBgY3AgLWZgIChhCiMgUEVSU0lTVEVOVCBvdmVyd3JpdGUpLCBub3QgYSBiaW5kLW1vdW50LCBzbyBubyB1bW91bnQgY2FuIHJldmVydCBpdDsgbGVmdAojIGFsb25lIGl0IGtlZXBzIHJlZmVyZW5jaW5nIHJlbW92ZWQgL3Zhci9saWIvd2Vib3NicmV3IHBsdWdpbnMgYW5kIGJyZWFrcwojIG1lZGlhLXBpcGVsaW5lIGFwcCBhdWRpbyAocm9vdC1jYXVzZWQgb24gYSByZWFsIEM1LCAyMDI2LTA3LTIzKS4gQ2FsbCBvbmx5CiMgQUZURVIgdGhlIGJpbmRzIGFyZSBkcm9wcGVkLiBTYW1lIHJvdXRpbmUgYXMgdW5pbnN0YWxsLnNoIHN0ZXAgMmIuCiMKIyBSRVRVUk5TIDAgT05MWSBJRiBMRydTIFJFR0lTVFJZIElTIEFDVFVBTExZIEJBQ0sgSU4gUExBQ0UuIFRoaXMgaXMgYSBjb2xkLWNhY2hlCiMgZnVsbCBwbHVnaW4gc2NhbiB1bmRlciBgdGltZW91dGAsIGFuZCBhdCBib290IGl0IHJ1bnMgYXQgdGhlIGJ1c2llc3QgbW9tZW50IG9uCiMgdGhlIGJveCwgc28gaXQgZ2VudWluZWx5IGNhbiBmYWlsIC0tIGNhbGxlcnMgdGhhdCBnbyBvbiB0byBERUxFVEUgb3VyIHBsdWdpbnMKIyBtdXN0IGJyYW5jaCBvbiB0aGlzLCBuZXZlciBhc3N1bWUgaXQgd29ya2VkLiBUaGUgc2NhbidzIG93biBleGl0IHN0YXR1cyBpcyBub3QKIyBzdWZmaWNpZW50IGV2aWRlbmNlIGVpdGhlcjogYSB0cnVuY2F0ZWQgcmVnaXN0cnkgd291bGQgYmUgd29yc2UgdGhhbiBub25lLCBzbwojIHRoZSBmaWxlIGhhcyB0byBiZSBub24tZW1wdHkgYmVmb3JlIGl0IGlzIGNvbW1pdHRlZC4KIyBBcmUgYW55IG9mIHRoZSBwbHVnaW4gYmluZHMgd2UgbWFuYWdlIHN0aWxsIG1vdW50ZWQ/IHcyNV9zdG9ja19yZWdpc3RyeSBoYXMgdG8KIyByZWZ1c2Ugd2hpbGUgb25lIGlzLiBUaGUgc2NhbiB3b3VsZCB0aGVuIGxvYWQgT1VSIGxpYmdzdGxpYmF2LnNvIGZyb20gdGhlIHN0b2NrCiMgcGF0aCAoaXRzIFJVTlBBVEggcmVzb2x2ZXMgZmluZSksIHByb2R1Y2UgYSBzeW50YWN0aWNhbGx5IHZhbGlkIHJlZ2lzdHJ5IHRoYXQKIyBoYXBwZW5zIHRvIG5hbWUgbm8gL3Zhci9saWIvd2Vib3NicmV3IHBhdGggYXQgYWxsIC0tIHdoaWNoIENMRUFSUwojIHcyNV9yZWdfaXNfb3VycywgdGhlIHZlcnkgc2lnbmFsIGNhbGxlcnMgdXNlIHRvIGRlY2lkZSBhIHJlcGFpciBpcyBuZWVkZWQgLS0gYW5kCiMgcmVwb3J0IHN1Y2Nlc3MuIEEgY2FsbGVyIHdvdWxkIHRha2UgdGhhdCBhcyBwcm9vZiB0aGUgVFYgaXMgYmFjayBvbiBzdG9jayBhbmQKIyBkZWxldGUgdGhlIHBheWxvYWQgb3V0IGZyb20gdW5kZXIgdGhlIHN1cnZpdmluZyBiaW5kLiBSZWZ1c2luZyBoZXJlIG1ha2VzIHRoaXMKIyBmdW5jdGlvbidzIHBvc3Rjb25kaXRpb24gKCIkUkVHIGlzIGEgc3RvY2sgcmVnaXN0cnkiKSB0cnVlIGJ5IGNvbnN0cnVjdGlvbiwgYW5kCiMgZXZlcnkgY2FsbGVyIGFscmVhZHkgaGFuZGxlcyBhIHJldHVybiBvZiAxIGJ5IGRlZmVycmluZyBpbnN0ZWFkIG9mIGRlbGV0aW5nLgp3MjVfcGx1Z2luX2JpbmRzX3ByZXNlbnQoKSB7CiAgZ3JlcCAtcSAiICRMR0xJQkFWICIgL3Byb2MvbW91bnRzIDI+L2Rldi9udWxsICYmIHJldHVybiAwCiAgZ3JlcCAtcSAiICRMR0lTTyAiIC9wcm9jL21vdW50cyAyPi9kZXYvbnVsbCAmJiByZXR1cm4gMAogIGdyZXAgLXEgIiAkTEdUU0QgIiAvcHJvYy9tb3VudHMgMj4vZGV2L251bGwgJiYgcmV0dXJuIDAKICByZXR1cm4gMQp9CncyNV9zdG9ja19yZWdpc3RyeSgpIHsKICBpZiB3MjVfcGx1Z2luX2JpbmRzX3ByZXNlbnQ7IHRoZW4KICAgIHcyNV9sb2cgIldBUk4gcmVmdXNpbmcgdG8gcmVidWlsZCB0aGUgc3RvY2sgcmVnaXN0cnk6IGEgcGx1Z2luIGJpbmQgb2Ygb3VycyBpcyBzdGlsbCBtb3VudGVkLCBzbyB0aGUgc2NhbiB3b3VsZCBub3QgYmUgcmVhZGluZyBzdG9jayBwbHVnaW5zIgogICAgcmV0dXJuIDEKICBmaQogIENMRUFOX1JFRz0vdG1wL2dzdF9jbGVhbl9yZWcuYmluCiAgcm0gLWYgIiRDTEVBTl9SRUciIDI+L2Rldi9udWxsCiAgaWYgR1NUX1JFR0lTVFJZXzFfMD0iJENMRUFOX1JFRyIgR1NUX1BMVUdJTl9QQVRIXzFfMD0vdXNyL2xpYi9nc3RyZWFtZXItMS4wOi9tbnQvbGcvcmVzL2xnbGliL2dzdHJlYW1lci0xLjAgR1NUX1JFR0lTVFJZX0ZPUks9bm8gR1NUX1JFR0lTVFJZX1VQREFURT15ZXMgdGltZW91dCA2MCAvdXNyL2Jpbi9nc3QtaW5zcGVjdC0xLjAgPi9kZXYvbnVsbCAyPiYxICYmIFsgLXMgIiRDTEVBTl9SRUciIF07IHRoZW4KICAgIGlmIGNwIC1mICIkQ0xFQU5fUkVHIiAiJFJFRyIgMj4vZGV2L251bGw7IHRoZW4KICAgICAgdzI1X2xvZyAicmVnZW5lcmF0ZWQgY2xlYW4gc3RvY2sgcmVnaXN0cnkgb3ZlciAkUkVHIgogICAgICBybSAtZiAiJENMRUFOX1JFRyIgMj4vZGV2L251bGwKICAgICAgcmV0dXJuIDAKICAgIGZpCiAgICB3MjVfbG9nICJXQVJOIGNvdWxkIG5vdCB3cml0ZSB0aGUgY2xlYW4gc3RvY2sgcmVnaXN0cnkgdG8gJFJFRyIKICBlbHNlCiAgICB3MjVfbG9nICJXQVJOIGNsZWFuIHN0b2NrIHJlZ2lzdHJ5IHJlZ2VuIGZhaWxlZCAoc2NhbiB0aW1lZCBvdXQsIGVycm9yZWQsIG9yIHByb2R1Y2VkIG5vdGhpbmcpOyBsZWF2aW5nICRSRUcgdW50b3VjaGVkIgogIGZpCiAgcm0gLWYgIiRDTEVBTl9SRUciIDI+L2Rldi9udWxsCiAgcmV0dXJuIDEKfQojIFJlY29yZCB0aGUgUFJJU1RJTkUgc3RvY2sgZmluZ2VycHJpbnRzICsgVFYgaWRlbnRpdHkuICQxPXZlcmlmaWVkLCAkMj1mb3JjZWQuCiMgV3JpdHRlbiBvbmx5IHdoZW4gdGhlIGdhdGUgYWxsb3dzIGFwcGx5aW5nLCBhbmQgb25seSBmcm9tIGhhc2hlcyB0YWtlbiB3aGlsZQojIG5vIGJpbmQgb2Ygb3VycyBzaGFkb3dlZCB0aGUgcGx1Z2lucyAtLSB0aGF0IGlzIHdoYXQgbGF0ZXIgbGV0cyBhIGJvb3QgdGVsbAojICJ0aGUgZmlybXdhcmUgY2hhbmdlZCIgYXBhcnQgZnJvbSAid2UgYXJlIHNpbXBseSBlbmFibGVkIi4KdzI1X2ZwX3dyaXRlKCkgewogIG1rZGlyIC1wIC92YXIvbGliL3dlYm9zYnJldy9kdHMyNSAyPi9kZXYvbnVsbAogIHsgZWNobyAiZ3N0X21tPSRHU1RfTU1fTk9XIgogICAgZWNobyAicHJvZHVjdF9pZD0kKHcyNV9wcm9kdWN0X2lkKSIKICAgIGVjaG8gIndlYm9zX3JlbGVhc2U9JCh3MjVfd2Vib3NfcmVsZWFzZSkiCiAgICBlY2hvICJsaWJnc3RsaWJhdj0kTV9MSUJBViIKICAgIGVjaG8gImxpYmdzdGlzb21wND0kTV9JU09NUDQiCiAgICBlY2hvICJsaWJnc3RtcGVndHNkZW11eD0kTV9NUEVHVFMiCiAgICBlY2hvICJkZXZpY2VfY29kZWNfY2FwYWJpbGl0eV9jb25maWc9JE1fQ0ZHIgogICAgZWNobyAiZ3N0Y29vbD0kTV9HQyIKICAgIGVjaG8gInZlcmlmaWVkPSQxIgogICAgZWNobyAiZm9yY2VkPSQyIgogICAgZWNobyAid3JpdHRlbj0kKGRhdGUgLXUgKyVZLSVtLSVkVCVIOiVNOiVTWikiCiAgfSA+ICIkRlAudG1wIiAyPi9kZXYvbnVsbCAmJiBtdiAtZiAiJEZQLnRtcCIgIiRGUCIgMj4vZGV2L251bGwgXAogICAgJiYgdzI1X2xvZyAid3JvdGUgJEZQICh2ZXJpZmllZD0kMSBmb3JjZWQ9JDIpIiB8fCB3MjVfbG9nICJXQVJOIGNvdWxkIG5vdCB3cml0ZSAkRlAiCiAgcmV0dXJuIDAKfQojIDw8PCBXMjUtQ09NUEFULUVORAojIFcyNV9DSEVDSz0xOiByZWFkLW9ubHkgcHJlZmxpZ2h0IHVzZWQgYnkgaW5zdGFsbC5zaCBhbmQgdGhlIGFwcCdzIEVuYWJsZSB0bwojIHJlZnVzZSB3aXRoIGEgcmVhZGFibGUgcmVhc29uIEJFRk9SRSB0aGV5IGxpbmsgdGhlIGJvb3QgaG9vay4gUHJpbnRzIG9ubHkuCmlmIFsgIiR7VzI1X0NIRUNLOi0wfSIgPSAxIF07IHRoZW4KICB3MjVfbWVhc3VyZQogIHcyNV9nYXRlCiAgZWNobyAiR1NUX01NPSRHU1RfTU1fTk9XIgogIGVjaG8gIlZFUkRJQ1Q9JFZFUkRJQ1QiCiAgZWNobyAiUkVBU09OPSRSRUFTT04iCiAgZWNobyAiTEFCRUw9JExBQkVMIgogIGVjaG8gIkNBTkZPUkNFPSRDQU5GT1JDRSIKICBpZiB3MjVfbG9hZGVyX29rOyB0aGVuIGVjaG8gIkxPQURFUj1vayI7IGVsc2UgZWNobyAiTE9BREVSPSRMT0FERVJfTUlTUyI7IGZpCiAgZWNobyAiTE9BREVSX1NUQUdFRD0ke0xPQURFUl9TVEFHRUQ6LTF9IgogICMgVGhlIHNpeCB2YWx1ZXMgYSBtYWludGFpbmVyIG5lZWRzIHRvIGFkZCB0aGlzIFRWIHRvIHRoZSB2ZXJpZmllZC1zZXRzIHRhYmxlLgogICMgRW1wdHkgbWQ1cyBtZWFuIHRoZSBwbHVnaW4gaXMgY3VycmVudGx5IHNoYWRvd2VkIGJ5IG9uZSBvZiBvdXIgYmluZHMsIHNvIHRoZQogICMgU1RPQ0sgaGFzaCBpcyB1bm1lYXN1cmFibGUgcmlnaHQgbm93IC0tIHJ1biB0aGlzIHdpdGggdGhlIG92ZXJyaWRlcyBkcm9wcGVkLgogIGVjaG8gIlBST0RVQ1RfSUQ9JCh3MjVfcHJvZHVjdF9pZCkiCiAgZWNobyAiV0VCT1NfUkVMRUFTRT0kKHcyNV93ZWJvc19yZWxlYXNlKSIKICBlY2hvICJNRDVfTElCR1NUTElCQVY9JFNfTElCQVYiCiAgZWNobyAiTUQ1X0xJQkdTVElTT01QND0kU19JU09NUDQiCiAgZWNobyAiTUQ1X0xJQkdTVE1QRUdUU0RFTVVYPSRTX01QRUdUUyIKICBlY2hvICJNRDVfREVWSUNFX0NPREVDX0NBUEFCSUxJVFlfQ09ORklHPSRTX0NGRyIKICBlY2hvICJNRDVfR1NUQ09PTD0kU19HQyIKICAjIFdoaWNoIGdhdGUgdGhpcyBzY3JpcHQgZW5mb3JjZXMsIGFuZCBpdHMgb3duIGZpbmdlcnByaW50LiAiJDAiIGlzIHRoZQogICMgaW5zdGFsbGVkIHBhdGgsIHNvIGEgY2FsbGVyIGNhbiB0ZWxsIHdoZXRoZXIgdGhlIHNjcmlwdCBpdCBqdXN0IHdyb3RlIGlzIHRoZQogICMgb25lIHRoYXQgcmFuLgogIFNFTEZfTUQ1PSQodzI1X21kNSAiJDAiKQogIGVjaG8gIkdBVEVfVkVSU0lPTj0kVzI1X0dBVEVfVkVSU0lPTiIKICBlY2hvICJTQ1JJUFRfTUQ1PSRTRUxGX01ENSIKICBleGl0IDAKZmkKIyBXMjVfU1RBTkRfRE9XTj0xOiByZXZlcnQgdG8gc3RvY2sgYW5kIGV4aXQuIERlbGliZXJhdGVseSBhIG1vZGUgb2YgaXRzIG93bgojIHJhdGhlciB0aGFuICJqdXN0IHJ1biB0aGUgc2NyaXB0IGFuZCBsZXQgaXQgcmVmdXNlIjogYSBtb2RlIGNhbm5vdCBhY2NpZGVudGFsbHkKIyBBUFBMWSBpZiB0aGUgZ2F0ZSdzIGlucHV0cyBjaGFuZ2VkIGJldHdlZW4gdGhlIGNhbGxlcidzIHByZWZsaWdodCBhbmQgdGhpcyBjYWxsLgppZiBbICIke1cyNV9TVEFORF9ET1dOOi0wfSIgPSAxIF07IHRoZW4KICBpZiB3MjVfcmVnX2lzX291cnM7IHRoZW4gV0FTX09VUlM9MTsgZWxzZSBXQVNfT1VSUz0wOyBmaQogIHcyNV9zdGFuZF9kb3duCiAgdzI1X2xvZyAic3RhbmQtZG93biByZXF1ZXN0ZWQgYnkgdGhlIGluc3RhbGxlciAoYSByZWdpc3RyeSBvZiBvdXJzIHdhcyBsaXZlOiAkV0FTX09VUlMpIgogIGVjaG8gIlNUT09EX0RPV049JFdBU19PVVJTIgogIGV4aXQgMApmaQojIC0tLSBHKSBzZWxmLWhlYWwgLyBzZWxmLXVubGluaywgZXZhbHVhdGVkIEZJUlNUIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiMgVFdPIERJRkZFUkVOVCBGQVVMVFMsIFRXTyBESUZGRVJFTlQgQU5TV0VSUy4gRGVsZXRpbmcgaXMgb25seSBldmVyIHJpZ2h0IHdoZW4KIyBub2JvZHkgb3ducyB0aGlzIGluc3RhbGwgYW55IG1vcmU7IGEgbWVyZWx5IGluY29tcGxldGUgaW5zdGFsbCBpcyByZWNvdmVyYWJsZSwKIyBhbmQgZGVzdHJveWluZyBpdCB3b3VsZCBiZSB3b3JzZSB0aGFuIHRoZSBoYXphcmQgdGhlIGd1YXJkIGV4aXN0cyBmb3IuCiMKIyAgIFVOT1dORUQgIHRoZSBhcHAgZGlyIGlzIGdvbmUgZnJvbSBCT1RIIGluc3RhbGwgdHJlZXMgQU5EIHRoZXJlIGlzIG5vIENMSQojICAgICAgICAgICAgbWFya2VyIC0+IG5vYm9keSBjYW4gbWFuYWdlIHRoZXNlIHN5c3RlbS13aWRlIG92ZXJyaWRlcyBhbnkgbW9yZS4KIyAgICAgICAgICAgIEZ1bGwgaGVhbDogZHJvcCB0aGUgYmluZHMsIHB1dCBhIGNsZWFuIHN0b2NrIHJlZ2lzdHJ5IGJhY2ssIHJlbW92ZQojICAgICAgICAgICAgb3VyIHN0YXRlLCB1bmxpbmsgb3Vyc2VsdmVzLgojICAgSU5DT01QTEVURSAoaGFuZGxlZCBpbiB0aGUgbmV4dCBibG9jaywgbm90IGhlcmUpIHRoZSBpbnN0YWxsIGlzIHN0aWxsIG93bmVkCiMgICAgICAgICAgICBidXQgYSBDT1JFIG9iamVjdCBpcyBtaXNzaW5nIC0+IGJpbmQgbm90aGluZywgZGVsZXRlIG5vdGhpbmcsIGtlZXAKIyAgICAgICAgICAgIHRoZSBob29rLCBhbmQgcmVwYWlyIHRoZSByZWdpc3RyeSBpZiBhIHN0YWxlIG9uZSBvZiBvdXJzIGlzIGxpdmUuCiMKIyBUaGUgaG9vayBzdGF5cyBhIHN5bWxpbmsgdG8gVEhJUyBmaWxlIHVuZGVyIC92YXIvbGliL3dlYm9zYnJldy9kdHMyNSByYXRoZXIKIyB0aGFuIGludG8gdGhlIGFwcCBkaXI6IGEgc3ltbGluayBpbnRvIGEgcmVtb3ZlZCBhcHAgZGlyIGlzIGRhbmdsaW5nIGFuZAojIGV4ZWN1dGVzIG5vdGhpbmcsIHNvIGl0IGNvdWxkIG5ldmVyIGhlYWwgYW55dGhpbmcuCkFQUERJUl9ERVY9L21lZGlhL2RldmVsb3Blci9hcHBzL3Vzci9wYWxtL2FwcGxpY2F0aW9ucy9pby5naXRodWIuam9zaXBwYXBlei5kdHNlbmFibGVyCkFQUERJUl9TWVM9L3Vzci9wYWxtL2FwcGxpY2F0aW9ucy9pby5naXRodWIuam9zaXBwYXBlei5kdHNlbmFibGVyCkNMSV9NQVJLRVI9L3Zhci9saWIvd2Vib3NicmV3L2R0czI1Ly5jbGktaW5zdGFsbAp3MjVfdW5vd25lZCgpIHsKICBIRUFMX1dIWT0KICBpZiBbICEgLWQgIiRBUFBESVJfREVWIiBdICYmIFsgISAtZCAiJEFQUERJUl9TWVMiIF0gJiYgWyAhIC1mICIkQ0xJX01BUktFUiIgXTsgdGhlbgogICAgSEVBTF9XSFk9InRoZSBEVFMgRW5hYmxlciBhcHAgaXMgZ29uZSBhbmQgdGhpcyB3YXMgbm90IGEgQ0xJIGluc3RhbGwiCiAgICByZXR1cm4gMAogIGZpCiAgcmV0dXJuIDEKfQojIE9SREVSIElTIFRIRSBXSE9MRSBQT0lOVCBIRVJFOiByZWdlbmVyYXRlIExHJ3MgcmVnaXN0cnkgRklSU1QgYW5kIGRlbGV0ZSBvdXIKIyBwbHVnaW5zIG9ubHkgb25jZSB0aGF0IGhhcyBhY3R1YWxseSBzdWNjZWVkZWQuCiMKIyBEZWxldGluZyBmaXJzdCB3b3VsZCBtZWFuIHRoYXQgYSByZWdlbiB3aGljaCB0aW1lcyBvdXQgLS0gYSBjb2xkLWNhY2hlIGZ1bGwKIyBwbHVnaW4gc2NhbiwgYXQgYm9vdCwgb24gdGhlIGJ1c2llc3QgbW9tZW50IHRoZSBib3ggaGFzIC0tIGxlYXZlcyB0aGUgbGl2ZQojIHJlZ2lzdHJ5IG5hbWluZyBwbHVnaW5zIHRoYXQgbm8gbG9uZ2VyIGV4aXN0IEFORCByZW1vdmVzIHRoZSBob29rIHRoYXQgY291bGQKIyByZXRyeS4gVGhhdCBpcyB0aGUgc3RhbGUtcmVnaXN0cnkgc3RhdGUgdGhhdCBicm9rZSBvdGhlciBhcHBzJyBhdWRpbyBvbiBhIHJlYWwKIyBDNSAoMjAyNi0wNy0yMyksIGFuZCBMRydzIHN0YWNrIGRvZXMgbm90IHJlY292ZXIgZnJvbSBpdCBieSBpdHNlbGYuCiMKIyBTbyBvbiBmYWlsdXJlOiBrZWVwIHRoZSBiaW5kcyBkcm9wcGVkLCBrZWVwIHRoZSBzdGF0ZSBkaXJzLCBrZWVwIHRoZSBob29rLCBhbmQKIyBsZXQgdGhlIG5leHQgYm9vdCB0cnkgYWdhaW4uIEEgaGVhbCB0aGF0IHJldHJpZXMgZm9yZXZlciBpcyBzdHJpY3RseSBiZXR0ZXIKIyB0aGFuIG9uZSB0aGF0IGJyZWFrcyBhdWRpbyBvbmNlLiBVbmNvbmRpdGlvbmFsIHJlZ2VuIChub3QgdzI1X3N0YW5kX2Rvd24ncwojIGNvbmRpdGlvbmFsIG9uZSkgYmVjYXVzZSB0aGlzIHBhdGggcmVtb3ZlcyBvdXIgcGx1Z2lucyBvdXRyaWdodCwgc28gYW55CiMgcmVnaXN0cnkgbmFtaW5nIHRoZW0gbXVzdCBiZSByZXBsYWNlZCB3aGV0aGVyIG9yIG5vdCBpdCBsb29rcyBsaWtlIG91cnMuCncyNV9zZWxmX2hlYWwoKSB7CiAgdzI1X2xvZyAiU0VMRi1IRUFMOiAkSEVBTF9XSFkgLS0gcmV2ZXJ0aW5nIGV2ZXJ5IG92ZXJyaWRlIgogIHcyNV9kcm9wX2JpbmRzCiAgaWYgISB3MjVfc3RvY2tfcmVnaXN0cnk7IHRoZW4KICAgIHcyNV9sb2cgIlNFTEYtSEVBTCBERUZFUlJFRDogTEcncyByZWdpc3RyeSBjb3VsZCBub3QgYmUgcmVidWlsdCwgc28gb3VyIHBsdWdpbnMgYW5kIHRoZSBib290IGhvb2sgYXJlIEtFUFQgKGRlbGV0aW5nIHRoZW0gbm93IHdvdWxkIGxlYXZlIHRoZSBsaXZlIHJlZ2lzdHJ5IHBvaW50aW5nIGF0IG1pc3NpbmcgcGx1Z2lucykuIFJldHJ5aW5nIGF0IHRoZSBuZXh0IGJvb3QuIgogICAgdG9hc3QgIkRUUyBFbmFibGVyIGNsZWFudXAgZGVmZXJyZWQ6IHRoZSBUViB3YXMgdG9vIGJ1c3kgdG8gcmVidWlsZCBpdHMgcGx1Z2luIGxpc3QuIEl0IHdpbGwgZmluaXNoIGF0IHRoZSBuZXh0IHJlc3RhcnQuIgogICAgcmV0dXJuIDEKICBmaQogIGZvciBkIGluIC92YXIvbGliL3dlYm9zYnJldy9kdHMyNSAvdmFyL2xpYi93ZWJvc2JyZXcvdHJ1ZWhkIC92YXIvbGliL3dlYm9zYnJldy9kZW11eDI1OyBkbwogICAgWyAtZCAiJGQiIF0gJiYgcm0gLXJmICIkZCIKICBkb25lCiAgcm0gLWYgIiRIT09LIgogIHRvYXN0ICJEVFMgRW5hYmxlciBpcyBnb25lOiBEVFMvVHJ1ZUhEIG92ZXJyaWRlcyByZXZlcnRlZCBhbmQgdGhlIGJvb3QgaG9vayByZW1vdmVkLiIKICByZXR1cm4gMAp9CiMgT25lIGNvbXBvdW5kIGNvbW1hbmQgb24gcHVycG9zZTogdGhlIHNoZWxsIGhhcyBmaW5pc2hlZCBwYXJzaW5nIHRoZSB3aG9sZQojIGBpZmAgKGFuZCBib3RoIGZ1bmN0aW9uIGJvZGllcykgYmVmb3JlIHcyNV9zZWxmX2hlYWwgZGVsZXRlcyB0aGUgZGlyZWN0b3J5CiMgdGhpcyB2ZXJ5IHNjcmlwdCBpcyBydW5uaW5nIGZyb20sIHNvIHRoZXJlIGlzIG5vdGhpbmcgbGVmdCB0byByZWFkIGFmdGVyd2FyZHMuCmlmIHcyNV91bm93bmVkOyB0aGVuCiAgaWYgdzI1X3NlbGZfaGVhbDsgdGhlbiBlY2hvICJIRUFMRUQ9JEhFQUxfV0hZIjsgZWxzZSBlY2hvICJIRUFMX0RFRkVSUkVEPSRIRUFMX1dIWSI7IGZpCiAgZXhpdCAwCmZpCiMgLS0tIEcyKSBvd25lZCwgYnV0IHRoZSBDT1JFIHBheWxvYWQgaXMgaW5jb21wbGV0ZSAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KIyBSZWNvdmVyYWJsZSwgc28gbm90aGluZyBpcyBkZWxldGVkIGFuZCB0aGUgaG9vayBzdGF5czogcmUtb3BlbmluZyB0aGUgYXBwIG9yCiMgcmUtcnVubmluZyBpbnN0YWxsLnNoIHJlc3RhZ2VzIHRoZSBwYXlsb2FkIGFuZCB0aGUgbmV4dCBib290IGFwcGxpZXMgbm9ybWFsbHkuCiMgV2hhdCBET0VTIG5lZWQgcmVwYWlyaW5nIGlzIHRoZSBtZWRpYSByZWdpc3RyeSAtLSBpdCBpcyBjb21taXR0ZWQgd2l0aCBgY3AgLWZgLAojIHNvIGEgcmVnaXN0cnkgd2Ugd3JvdGUgZWFybGllciBzdXJ2aXZlcyBpbmRlcGVuZGVudGx5IG9mIG91ciBmaWxlcywgYW5kIGlmIGl0CiMgaXMgc3RpbGwgbGl2ZSB3aGlsZSBvdXIgbGlicmFyaWVzIGFyZSBnb25lIGl0IG5hbWVzIHBsdWdpbnMgdGhhdCBubyBsb25nZXIKIyBleGlzdCAodGhhdCBpcyB0aGUgZmFpbHVyZSB0aGF0IGJyb2tlIG1lZGlhLXBpcGVsaW5lIGFwcCBhdWRpbyBvbiBhIHJlYWwgQzUsCiMgMjAyNi0wNy0yMykuIE9ubHkgdGhlIGRlbXV4ZXJzIGFyZSBvcHRpb25hbDsgbWlzc2luZyB0aG9zZSBpcyBhIG5vcm1hbAojIE1LVi1vbmx5IGluc3RhbGwsIG5vdCBhIGZhdWx0LgppZiAhIHcyNV9jb3JlX3N0YWdlZDsgdGhlbgogIHcyNV9sb2cgIlJFRlVTRUQ6IGNvcmUgcGF5bG9hZCBpbmNvbXBsZXRlIChkdHNkZWMgcHJlc2VudD0kKFsgLWYgIiRNWURUUyIgXSAmJiBlY2hvIDEgfHwgZWNobyAwKSwgbGliYXYgcHJlc2VudD0kKFsgLWYgIiRNWUxJQkFWIiBdICYmIGVjaG8gMSB8fCBlY2hvIDApKTsgYmluZGluZyBub3RoaW5nLCBpbnN0YWxsIGxlZnQgaW50YWN0IgogIHcyNV9zdGFuZF9kb3duCiAgdG9hc3QgIkRUUyBFbmFibGVyOiB0aGUgaW5zdGFsbGVkIGZpbGVzIGFyZSBpbmNvbXBsZXRlLCBzbyBub3RoaW5nIHdhcyBhcHBsaWVkLiBSZS1vcGVuIERUUyBFbmFibGVyIChvciByZS1ydW4gaW5zdGFsbC5zaCkgdG8gcmVwYWlyLiIKICBlY2hvICJSRUZVU0VEPXBheWxvYWQiCiAgZWNobyAiUkVBU09OPXRoZSBzdGFnZWQgRFRTL1RydWVIRCBjb3JlIHBheWxvYWQgaXMgaW5jb21wbGV0ZTsgbm90aGluZyB3YXMgYm91bmQgYW5kIG5vdGhpbmcgd2FzIHJlbW92ZWQiCiAgZXhpdCAwCmZpCiMgLS0tIG1lYXN1cmUgdGhlIHByaXN0aW5lIHN0b2NrIGZpbmdlcnByaW50cyAocmVhZC1vbmx5KSAtLS0tLS0tLS0tLS0tLS0tLS0tLQp3MjVfbWVhc3VyZQojIC0tLSBHQVRFIDApIGZpcm13YXJlLXVwZGF0ZSAvIEFCSSBndWFyZCAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KaWYgISB3MjVfZ3N0X29rOyB0aGVuCiAgdzI1X2xvZyAiQUJPUlQ6IEdTdHJlYW1lciAnJEdTVF9NTV9OT1cnICE9IGV4cGVjdGVkICRFWFBFQ1RfR1NUIChmaXJtd2FyZSB1cGRhdGU/KTsgc3RhbmRpbmcgZG93biIKICAjIFRoZSBsaWtlbGllc3QgcmVmdXNhbCBpbiB0aGUgd2lsZCwgYW5kIHRoZSBvbmUgd2hlcmUgbGVhdmluZyBhIHJlZ2lzdHJ5IG9mCiAgIyBvdXJzIGxpdmUgd291bGQgYmUgd29yc3Q6IG91ciBwbHVnaW5zIG1heSBub3QgZXZlbiBleGlzdCBhbnkgbW9yZSBhZnRlciBhCiAgIyBtYWpvciBmaXJtd2FyZSBjaGFuZ2UuIHcyNV9zdGFuZF9kb3duIGhhbmRsZXMgdGhhdCAtLSBpdCByZWJ1aWxkcyBmcm9tIExHJ3MKICAjIHBsdWdpbiBkaXJlY3RvcmllcyBvbmx5LgogIHcyNV9zdGFuZF9kb3duCiAgdG9hc3QgIkRUUy9UcnVlSEQgcGF1c2VkOiBUViBmaXJtd2FyZSBjaGFuZ2VkIChHU3RyZWFtZXIgJEdTVF9NTV9OT1cpLiBSZS1vcGVuIERUUyBFbmFibGVyIHRvIHVwZGF0ZS4iCiAgZWNobyAiUkVGVVNFRD1kcmlmdCIKICBlY2hvICJSRUFTT049R1N0cmVhbWVyICRHU1RfTU1fTk9XIGlzIG5vdCB0aGUgJEVYUEVDVF9HU1QgdGhpcyBwYXlsb2FkIHdhcyBidWlsdCBmb3I7IGEgZmlybXdhcmUgdXBkYXRlIGNoYW5nZWQgdGhlIHBsdWdpbiBBQkkiCiAgZXhpdCAwCmZpCiMgLS0tIEdBVEUgMSkgaWRlbnRpdHkgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQp3MjVfdmVyZGljdApjYXNlICIkVkVSRElDVCIgaW4KICB2ZXJpZmllZHxmb3JjZWQpIHcyNV9sb2cgImdhdGU6ICRWRVJESUNUIC0tICRSRUFTT04ke0xBQkVMOisgWyRMQUJFTF19IiA7OwogIGRyaWZ0KQogICAgdzI1X2xvZyAiUkVGVVNFRDogZHJpZnQgLS0gJFJFQVNPTiIKICAgIHcyNV9zdGFuZF9kb3duCiAgICB0b2FzdCAiRFRTL1RydWVIRCBzdG9wcGVkOiB0aGlzIFRWIGNoYW5nZWQgc2luY2UgaXQgd2FzIGxhc3QgdmVyaWZpZWQsIHNvIG5vdGhpbmcgd2FzIGFwcGxpZWQuIFVuaW5zdGFsbCB0aGVuIEVuYWJsZSBpbiBEVFMgRW5hYmxlciB0byBvcHQgaW4gYWdhaW4uIgogICAgZWNobyAiUkVGVVNFRD1kcmlmdCIKICAgIGVjaG8gIlJFQVNPTj0kUkVBU09OIgogICAgZXhpdCAwIDs7CiAgKikKICAgIHcyNV9sb2cgIlJFRlVTRUQ6ICRWRVJESUNUIC0tICRSRUFTT04iCiAgICB3MjVfc3RhbmRfZG93bgogICAgdG9hc3QgIkRUUyBFbmFibGVyOiB0aGlzIFRWIGlzIG5vdCBvbiB0aGUgdmVyaWZpZWQgbGlzdCwgc28gbm90aGluZyB3YXMgY2hhbmdlZC4gT3BlbiBEVFMgRW5hYmxlciB0byB0cnkgYW55d2F5LiIKICAgIGVjaG8gIlJFRlVTRUQ9JFZFUkRJQ1QiCiAgICBlY2hvICJSRUFTT049JFJFQVNPTiIKICAgIGV4aXQgMCA7Owplc2FjCiMgLS0tIEdBVEUgMmEpIGxvYWRlciByZXNvbHV0aW9uIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQppZiAhIHcyNV9sb2FkZXJfb2s7IHRoZW4KICB3MjVfbG9nICJSRUZVU0VEOiBsb2FkZXIgLS0gJExPQURFUl9NSVNTIgogIHcyNV9zdGFuZF9kb3duCiAgdG9hc3QgIkRUUyBFbmFibGVyOiB0aGUgcGF5bG9hZCBjYW5ub3QgbG9hZCBvbiB0aGlzIFRWICgkTE9BREVSX01JU1MpOyBub3RoaW5nIHdhcyBjaGFuZ2VkLiIKICBlY2hvICJSRUZVU0VEPWxvYWRlciIKICBlY2hvICJSRUFTT049JExPQURFUl9NSVNTIgogIGV4aXQgMApmaQojIC0tLSByZWNvcmQgdGhlIHByaXN0aW5lIGZpbmdlcnByaW50cyBiZWZvcmUgYW55dGhpbmcgb2Ygb3VycyBpcyBib3VuZCAtLS0tLS0KY2FzZSAiJFZFUkRJQ1QiIGluCiAgdmVyaWZpZWQpIEZQX0ZPUkNFRD0kKHcyNV9mcF9nZXQgZm9yY2VkKTsgWyAtbiAiJEZQX0ZPUkNFRCIgXSB8fCBGUF9GT1JDRUQ9MDsgdzI1X2ZwX3dyaXRlIDEgIiRGUF9GT1JDRUQiIDs7CiAgKikgICAgICAgIHcyNV9mcF93cml0ZSAwIDEgOzsKZXNhYwojIC0tLSBBUFBMWSAxKSBjb2RlYy1jYXBhYmlsaXR5IG92ZXJyaWRlIChhZGRzIFRSVUVIRC9NTFAgc28gdW1lZGlhc2VydmVyIGFsbG9jYXRlcyBhIGRlY29kZXIgcmVzb3VyY2UpClsgLWYgIiRNWUNGRyIgXSAmJiAhIGdyZXAgLXEgIiAkQ0ZHICIgL3Byb2MvbW91bnRzIDI+L2Rldi9udWxsICYmIG1vdW50IC1uIC0tYmluZCAiJE1ZQ0ZHIiAiJENGRyIgMj4+JExPRwojIC0tLSBBUFBMWSAyKSByZXBsYWNlIExHLnMgdHJ1ZWhkLWxlc3MgbGliYXYgd2l0aCBvdXJzIChoYXMgYXZkZWNfdHJ1ZWhkL2F2ZGVjX21scCkKWyAtZiAiJE1ZTElCQVYiIF0gJiYgISBncmVwIC1xICIgJExHTElCQVYgIiAvcHJvYy9tb3VudHMgMj4vZGV2L251bGwgJiYgbW91bnQgLW4gLS1iaW5kIC1vIHJvICIkTVlMSUJBViIgIiRMR0xJQkFWIiAyPj4kTE9HCiMgLS0tIEFQUExZIDJiKSBnc3Rjb29sLmNvbmY6IGdpdmUgYXZkZWNfdHJ1ZWhkIGEgaGlnaCBTVyByYW5rIHNvIExHIGF1dG9wbHVncyBpdCAobm90IHRoZSBIVyBwYXRoKQpbIC1mICIkTVlHQyIgXSAmJiAhIGdyZXAgLXEgIiAkR0MgIiAvcHJvYy9tb3VudHMgMj4vZGV2L251bGwgJiYgbW91bnQgLW4gLS1iaW5kICIkTVlHQyIgIiRHQyIgMj4+JExPRwojIC0tLSBBUFBMWSAyYykgY29udGFpbmVyIGRlbXV4ZXJzIHdpdGggRFRTIHJlLWVuYWJsZWQgKG1wNC90cy9tMnRzIERUUyAtPiBhdWRpby94LWR0cykuCiMgICAgICAgICBQYXRjaGVkIGlzb21wNC9tcGVndHNkZW11eCBkZWZhdWx0IGR0c19zdXBwb3J0PVRSVUUuIEJvdW5kIEJFRk9SRSB0aGUKIyAgICAgICAgIHJlZ2VuIGJlbG93IHNvIHRoZSByZWdpc3RyeSBwaWNrcyB0aGVtIHVwIGF0IHRoZWlyIG5vcm1hbCBwYXRoLgpbIC1mICIkTVlJU08iIF0gJiYgISBncmVwIC1xICIgJExHSVNPICIgL3Byb2MvbW91bnRzIDI+L2Rldi9udWxsICYmIG1vdW50IC1uIC0tYmluZCAtbyBybyAiJE1ZSVNPIiAiJExHSVNPIiAyPj4kTE9HClsgLWYgIiRNWVRTRCIgXSAmJiAhIGdyZXAgLXEgIiAkTEdUU0QgIiAvcHJvYy9tb3VudHMgMj4vZGV2L251bGwgJiYgbW91bnQgLW4gLS1iaW5kIC1vIHJvICIkTVlUU0QiICIkTEdUU0QiIDI+PiRMT0cKIyAtLS0gQVBQTFkgMykgcmVnZW5lcmF0ZSB0aGUgbWVkaWEgcmVnaXN0cnkgKGZyZXNoKSB3aXRoIGR0c2RlYyArIG91ciBsaWJhdiwgdGhlbiB3cml0ZSBpdCB0byB0aGUgbWVkaWEgcGF0aC4KIyAgICBCb3VuZGVkIGJ5IGB0aW1lb3V0YCBhbmQgc2Nhbm5lZCBpbi1wcm9jZXNzIChHU1RfUkVHSVNUUllfRk9SSz1ubykgc28gYSBoYW5nIGNhbid0IHRyaXAgSEJDCiMgICAgZmFpbHNhZmUgYW5kIG5vIGdzdC1wbHVnaW4tc2Nhbm5lciBjaGlsZCBsaW5nZXJzIHBhc3QgdGhlIHRpbWVvdXQuClJFR19UTVA9L3RtcC9nc3RfZHRzX3JlZy5iaW4Kcm0gLWYgIiRSRUdfVE1QIgpMRF9MSUJSQVJZX1BBVEg9L3Zhci9saWIvd2Vib3NicmV3L3RydWVoZC9saWJzIFwKR1NUX1JFR0lTVFJZXzFfMD0iJFJFR19UTVAiIFwKR1NUX1BMVUdJTl9QQVRIXzFfMD0vdXNyL2xpYi9nc3RyZWFtZXItMS4wOi9tbnQvbGcvcmVzL2xnbGliL2dzdHJlYW1lci0xLjA6L3Zhci9saWIvd2Vib3NicmV3L2R0czI1IFwKR1NUX1JFR0lTVFJZX0ZPUks9bm8gR1NUX1JFR0lTVFJZX1VQREFURT15ZXMgdGltZW91dCAzMCAvdXNyL2Jpbi9nc3QtaW5zcGVjdC0xLjAgPi9kZXYvbnVsbCAyPj4kTE9HCiMgLS0tIEdBVEUgMmIpIHBvc3QtYmluZCBwaXBlbGluZSBwcm9vZiwgdGhlbiBjb21taXQ6IG92ZXJ3cml0ZSB0aGUgbWVkaWEKIyAgICAgICAgIHJlZ2lzdHJ5IG9ubHkgaWYgdGhlIHJlZ2VuIHN1cnZpdmVkIHRoZSBiaW5kcyB3aXRoIGFsbCBmaXZlIGVsZW1lbnRzCiMgICAgICAgICBpbnRhY3QuIE90aGVyd2lzZSBkcm9wIG91ciBvd24gYmluZHMgLS0gdGhhdCBpcyB3aGF0IHR1cm5zICJ0aGUKIyAgICAgICAgIG92ZXJyaWRlIGRpZCBub3QgbWF0Y2giIGZyb20gYSBicm9rZW4gbWVkaWEgcGlwZWxpbmUgaW50byBhIG5vLW9wLgppZiB3MjVfcmVnX2hhc19hbGwgIiRSRUdfVE1QIjsgdGhlbgogIGNwIC1mICIkUkVHX1RNUCIgIiRSRUciIDI+PiRMT0cgJiYgZWNobyAicmVnaXN0cnkgdXBkYXRlZCAoZHRzZGVjK2F2ZGVjX3RydWVoZCtxdGRlbXV4K3RzZGVtdXgrbWF0cm9za2FkZW11eCkiID4+JExPRwogIGVjaG8gIkFQUExJRUQ9JFZFUkRJQ1QiCmVsc2UKICB3MjVfbG9nICJSRUZVU0VEOiByZWdlbiBpcyBtaXNzaW5nICRSRUdfTUlTUzsgbm90IGNvbW1pdHRpbmcgaXQsIGFuZCBzdGFuZGluZyBkb3duIgogIHcyNV9zdGFuZF9kb3duCiAgdG9hc3QgIkRUUyBFbmFibGVyOiB0aGUgcGx1Z2luIHJlZ2lzdHJ5IGRpZCBub3Qgc3Vydml2ZSB0aGUgb3ZlcnJpZGUgKCRSRUdfTUlTUyBtaXNzaW5nKSwgc28gbm90aGluZyB3YXMgY2hhbmdlZC4iCiAgZWNobyAiUkVGVVNFRD1waXBlbGluZSIKICBlY2hvICJSRUFTT049dGhlIHJlZ2VuZXJhdGVkIHBsdWdpbiByZWdpc3RyeSBpcyBtaXNzaW5nICRSRUdfTUlTUyIKZmkKZXhpdCAwCg==
INIT_B64
chmod 0755 "$INIT_SCRIPT" && log "installed embedded init_dts25.sh -> $INIT_SCRIPT" || log "WARN: writing init_dts25.sh failed"

# --- 4b. Compatibility preflight (READ-ONLY) -------------------------------
# Run the gate that init_dts25.sh enforces, in its check mode: it fingerprints
# the three stock plugins we shadow (pristine, thanks to step 3), matches them
# against the verified-sets table, and confirms every payload object's dynamic
# dependencies resolve on THIS TV. Only one authored copy of that gate exists --
# this asks the installed script rather than duplicating it here.
#
# Nothing is bound until this passes and the boot hook is not linked at all, so a
# refusal never APPLIES anything (the staged files under /var/lib/webosbrew are
# inert without the binds). It is not a no-op on a TV that was already enabled,
# though: step 3 above has already detached the binds, and our `cp -f` registry
# would still be live. Every refusal branch below therefore stands the TV down --
# W25_STAND_DOWN=1 rebuilds LG's registry if one of ours is in place -- so the TV
# ends up on stock rather than half-way.
CHECK=$(W25_CHECK=1 FORCE="$FORCE" sh "$INIT_SCRIPT" 2>/dev/null)
GATE_VERDICT=$(printf '%s\n' "$CHECK" | sed -n 's/^VERDICT=//p' | head -n1)
GATE_REASON=$(printf '%s\n' "$CHECK" | sed -n 's/^REASON=//p' | head -n1)
GATE_LABEL=$(printf '%s\n' "$CHECK" | sed -n 's/^LABEL=//p' | head -n1)
GATE_CANFORCE=$(printf '%s\n' "$CHECK" | sed -n 's/^CANFORCE=//p' | head -n1)
GATE_LOADER=$(printf '%s\n' "$CHECK" | sed -n 's/^LOADER=//p' | head -n1)
GATE_STAGED=$(printf '%s\n' "$CHECK" | sed -n 's/^LOADER_STAGED=//p' | head -n1)
log "preflight: verdict=$GATE_VERDICT canforce=$GATE_CANFORCE loader=$GATE_LOADER staged=$GATE_STAGED reason=$GATE_REASON"

# Put the TV back on stock before reporting a refusal. Step 3 already detached the
# binds, so on a previously-enabled TV the only thing left applied is the `cp -f`
# registry -- which W25_STAND_DOWN=1 rebuilds from LG's own plugins. Prints
# STOOD_DOWN=1 when a registry of ours was actually live.
stand_down_now() {
  SD=$(W25_STAND_DOWN=1 sh "$INIT_SCRIPT" 2>/dev/null)
  log "stand-down: $(printf '%s' "$SD" | tr '\n' ' ')"
  case "$SD" in
    *STOOD_DOWN=1*)
      echo "This TV was previously enabled, so the overrides have been REVERTED:"
      echo "the bind-mounts are detached and LG's plugin registry has been restored." ;;
    *)
      echo "Nothing of ours was applied on this TV, and nothing was changed." ;;
  esac
}

if [ "$GATE_LOADER" != "ok" ]; then
  # LOADER_STAGED=0 means the CORE payload is not staged (out/ or truehd-out/
  # missing or not copied) -- a packaging problem, not an incompatible TV. A
  # demux-less staging is NOT this case: the gate skips optional objects.
  if [ "$GATE_STAGED" = 0 ]; then
    log "REFUSED: core payload incomplete -- $GATE_LOADER"
    echo "DTS + TrueHD install REFUSED: the core payload is incomplete."
    echo "  $GATE_LOADER"
    echo "Check that out/ and truehd-out/ are populated (see the header of this script)."
  else
    log "REFUSED: loader gate -- $GATE_LOADER"
    echo "DTS + TrueHD install REFUSED: the payload cannot load on this TV."
    echo "  $GATE_LOADER"
  fi
  stand_down_now
  echo "See $LOG for details."
  exit 0
fi

case "$GATE_VERDICT" in
  verified)
    log "gate: verified TV -- $GATE_LABEL"
    echo "Verified TV: $GATE_LABEL"
    ;;
  forced)
    log "gate: forced apply on an unverified TV -- $GATE_REASON"
    echo "WARNING: this TV is not on the verified list; applying anyway (FORCE=1)."
    ;;
  drift)
    # A firmware change that touches the plugins we shadow stands us down, full
    # stop -- FORCE=1 does not apply here, so it is not offered. What DOES work is
    # clearing the recorded baseline (uninstall.sh) and opting in through the
    # unverified flow, or getting this TV added to the verified table.
    log "REFUSED: drift -- $GATE_REASON"
    echo "DTS + TrueHD install REFUSED: this TV changed since it was last verified."
    echo "  $GATE_REASON"
    echo ""
    stand_down_now
    echo "FORCE=1 does not override this."
    echo "To opt in again explicitly:  sh uninstall.sh  &&  FORCE=1 sh install.sh"
    echo "Or report these fingerprints so this TV can be added to the verified table:"
    printf '%s\n' "$CHECK" | sed -n 's/^PRODUCT_ID=/    product_id=/p;s/^WEBOS_RELEASE=/    webos_release=/p;s/^GST_MM=/    gst_mm=/p;s/^MD5_LIBGSTLIBAV=/    libgstlibav=/p;s/^MD5_LIBGSTISOMP4=/    libgstisomp4=/p;s/^MD5_LIBGSTMPEGTSDEMUX=/    libgstmpegtsdemux=/p;s/^MD5_DEVICE_CODEC_CAPABILITY_CONFIG=/    device_codec_capability_config=/p;s/^MD5_GSTCOOL=/    gstcool=/p'
    echo "See $LOG for details."
    exit 0
    ;;
  *)
    log "REFUSED: $GATE_VERDICT -- $GATE_REASON"
    echo "DTS + TrueHD install REFUSED: $GATE_REASON"
    if [ "$GATE_CANFORCE" = 1 ]; then
      # unverified only -- drift is handled above and reports CANFORCE=0.
      echo "The payload's libraries DO resolve on this TV. To opt in anyway:"
      echo "    FORCE=1 sh install.sh"
    fi
    stand_down_now
    echo "See $LOG for details."
    exit 0
    ;;
esac

# --- 4c. Link the boot hook (only now that the gate has passed) -------------
mkdir -p "$INITD"
if [ -L "$HOOK" ] || [ -e "$HOOK" ]; then rm -f "$HOOK"; fi
ln -s "$INIT_SCRIPT" "$HOOK" && log "linked boot hook $HOOK -> $INIT_SCRIPT"

# --- 5. Apply now ----------------------------------------------------------
# The init script re-runs the same gate, writes stock.fp from the pristine
# fingerprints, binds, and commits the registry only if all five elements
# (dtsdec, avdec_truehd, qtdemux, tsdemux, matroskademux) survive the binds.
log "applying now (running $INIT_SCRIPT)"
APPLY=$(FORCE="$FORCE" sh "$INIT_SCRIPT" 2>/dev/null)
log "apply result: $(printf '%s' "$APPLY" | tr '\n' ' ')"

case "$APPLY" in
  *REFUSED=*)
    echo "DTS + TrueHD install did NOT apply:"
    printf '%s\n' "$APPLY" | sed -n 's/^REASON=/  /p'
    echo "The boot hook has been left in place; it re-checks on every boot and"
    echo "binds nothing until the TV passes. See $LOG for details."
    ;;
  *)
    if killall starfish-media-pipeline 2>>"$LOG"; then
      log "restarted starfish-media-pipeline"
    else
      log "note: starfish-media-pipeline not running (starts fresh on next playback)"
    fi
    echo "DTS + TrueHD install complete. See $LOG for details."
    ;;
esac

log "=== unified DTS+TrueHD install done ==="
exit 0
