#!/bin/sh
#
# install.sh - Install the unified DTS + TrueHD/MLP audio restore on a rooted
#              LG webOS 25 TV (C5 class). PROVEN working on a real LG C5.
#
# Run as root ON THE TV, from this restore/ directory (copied via scp), which
# must contain:
#     out/libgstdtsdec.so        patched dtsdec (S32LE, accepts A_DTS)   [build.sh]
#     out/libdca.so.0            DTS decode library (armel)              [build.sh]
#     truehd-out/libgstlibav.so  gst-libav with avdec_truehd/avdec_mlp   [build-truehd.sh]
#     truehd-out/libav*.so*      minimal ffmpeg n4.4.4 libs (+symlinks)  [build-truehd.sh]
#     truehd-out/libsw*.so*      libswresample (+symlinks)               [build-truehd.sh]
#     demux-out/libgstisomp4.so       mp4 demux, DTS re-enabled (OPTIONAL) [build-demux.sh]
#     demux-out/libgstmpegtsdemux.so  ts/m2ts demux, DTS re-enabled (OPT.) [build-demux.sh]
#   (the boot/apply script is EMBEDDED in this installer - no sibling file needed)
#
# out/ and truehd-out/ are the CORE payload and are required. demux-out/ is
# optional: without it the boot hook simply skips the demuxer binds and DTS still
# works in MKV (see step 2c).
#
# All binaries are PREBUILT and bundled; you do NOT need Docker or to build
# anything. Just: copy this folder to the TV, then run (as root):
#
#   sh install.sh
#
# What it does (idempotent, guarded, logged to /tmp/dts25.log, always exit 0):
#   1. Stages the DTS payload  -> /var/lib/webosbrew/dts25/{,libs/}
#   2. Stages the TrueHD payload-> /var/lib/webosbrew/truehd/{,libs/}
#   2c. Stages the container demuxers (if demux-out/ present)
#        -> /var/lib/webosbrew/demux25/ (mp4/ts/m2ts DTS; boot hook binds them)
#   3. GENERATES two config overrides by EDITING the TV's own live /etc files
#      (no LG config file is shipped):
#        a. /etc/umediaserver/device_codec_capability_config.json
#           -> insert TRUEHD + MLP audio-codec objects after the DTSE entry
#        b. /etc/gst/gstcool.conf
#           -> insert avdec_truehd=310 + avdec_mlp=310 after [sw_decoder]
#      Both are written to /var/lib/webosbrew/truehd/ and bind-mounted by the
#      boot hook (originals are never modified in place - fully reversible).
#   4. Installs the canonical init_dts25.sh, then runs its READ-ONLY compatibility
#      preflight (W25_CHECK=1). Only if that says verified/forced does it symlink
#      the boot hook /var/lib/webosbrew/init.d/restore_dts25 -> it. On any other
#      verdict it prints the reason and changes nothing on this TV.
#   5. Applies everything now (runs the init script) + restarts the media pipe.
#
# COMPATIBILITY GATE. Our .so are bind-mounted over LG's system-wide (they
# propagate into every app jail), so this installer refuses to bind on a TV whose
# stock plugin fingerprints are not in init_dts25.sh's verified-sets table. To
# opt in anyway on an unverified TV:
#
#   FORCE=1 sh install.sh
#
# which is recorded as forced=1 in /var/lib/webosbrew/dts25/stock.fp so later
# boots honour the choice. FORCE=1 NEVER overrides a drift verdict (the stock
# plugins changed under an existing install) or the GStreamer ABI guard or the
# loader gate. To re-opt-in after a firmware change, run uninstall.sh (which
# clears the recorded baseline) and then install.sh, which puts the TV back in
# the unverified flow where the opt-in applies.
#
# A REFUSED RUN LEAVES THE STAGED FILES UNDER /var/lib/webosbrew IN PLACE, on
# purpose: no boot hook is linked, so they are inert, and stock.fp among them is
# what lets a later run distinguish a firmware change from an unverified TV. Use
# uninstall.sh to remove them.
#
set -u

# Explicit opt-in on a TV that is not in the verified-sets table. Author-read
# only: the value is compared, never interpolated into a command.
FORCE=${FORCE:-0}

LOG=/tmp/dts25.log
DTS_DEST=/var/lib/webosbrew/dts25
DTS_LIBS=$DTS_DEST/libs
THD_DEST=/var/lib/webosbrew/truehd
THD_LIBS=$THD_DEST/libs
INITD=/var/lib/webosbrew/init.d
HOOK=$INITD/restore_dts25
INIT_SCRIPT=$DTS_DEST/init_dts25.sh
# Marker that says "an SSH/CLI install owns this state", so the boot script's
# self-heal does not mistake a CLI-only install for an orphaned one.
CLI_MARKER=$DTS_DEST/.cli-install

# Live LG config files we derive our (bind-mounted) overrides from.
CFG_LIVE=/etc/umediaserver/device_codec_capability_config.json
CFG_OVR=$THD_DEST/codec_capability.json
GC_LIVE=/etc/gst/gstcool.conf
GC_OVR=$THD_DEST/gstcool.conf

# Bind targets the boot hook manages (unmount here so we read pristine originals).
LGLIBAV=/usr/lib/gstreamer-1.0/libgstlibav.so
REG_TARGET=/mnt/flash/data/gst_1_0_registry.arm.bin

SELF_DIR=$(cd "$(dirname "$0")" && pwd)

log() { echo "[dts25-install $(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG" 2>&1; }

# Unmount one bind target, falling back to a LAZY detach when it is busy.
# Measured on a real C5: umount of /usr/lib/gstreamer-1.0/libgstlibav.so fails
# with "target is busy" because WebAppMgr has the .so mapped, while `umount -l`
# succeeds -- so without this fallback a stale override survives the "regenerate
# from pristine originals" step and we would derive our overrides from OUR OWN
# files. Same semantics as w25_umount() in init_dts25.sh.
w25_umount() {
  grep -q " $1 " /proc/mounts 2>/dev/null || return 0
  if umount "$1" 2>>"$LOG"; then log "unmounted stale bind $1"; return 0; fi
  if umount -l "$1" 2>>"$LOG"; then log "lazy-detached busy stale bind $1 (a live mapping held it)"; return 0; fi
  log "WARN could not unmount $1, even lazily"
  return 1
}

log "=== unified DTS+TrueHD install start ==="

# --- 1. Stage DTS payload --------------------------------------------------
mkdir -p "$DTS_LIBS" || { log "FATAL: cannot create $DTS_LIBS"; exit 0; }

# Mark this as an SSH/CLI install BEFORE anything can run the boot script: its
# self-heal reverts an install that no longer has an owner (app dir gone), and
# without this marker a CLI-only install would look exactly like that and be
# healed away on the next boot.
: > "$CLI_MARKER" && log "marked CLI install ($CLI_MARKER)" || log "WARN: could not write $CLI_MARKER"

if [ -f "$SELF_DIR/out/libgstdtsdec.so" ]; then
  cp -f "$SELF_DIR/out/libgstdtsdec.so" "$DTS_DEST/libgstdtsdec.so" \
    && log "installed libgstdtsdec.so -> $DTS_DEST/" || log "WARN: copy libgstdtsdec.so failed"
else
  log "WARN: $SELF_DIR/out/libgstdtsdec.so not found (run build.sh first)"
fi
if [ -f "$SELF_DIR/out/libdca.so.0" ]; then
  cp -f "$SELF_DIR/out/libdca.so.0" "$DTS_LIBS/libdca.so.0" \
    && log "installed libdca.so.0 -> $DTS_LIBS/" || log "WARN: copy libdca.so.0 failed"
else
  log "WARN: $SELF_DIR/out/libdca.so.0 not found (run build.sh first)"
fi

# --- 2. Stage TrueHD payload (preserve the .so version symlinks) -----------
mkdir -p "$THD_LIBS" || { log "FATAL: cannot create $THD_LIBS"; exit 0; }

if [ -f "$SELF_DIR/truehd-out/libgstlibav.so" ]; then
  cp -f "$SELF_DIR/truehd-out/libgstlibav.so" "$THD_DEST/libgstlibav.so" \
    && log "installed libgstlibav.so -> $THD_DEST/" || log "WARN: copy libgstlibav.so failed"
else
  log "WARN: $SELF_DIR/truehd-out/libgstlibav.so not found (run build-truehd.sh first)"
fi

n=0
for f in "$SELF_DIR"/truehd-out/libav*.so* "$SELF_DIR"/truehd-out/libsw*.so*; do
  [ -e "$f" ] || continue
  # cp -P preserves the soname symlinks (libavcodec.so.58 -> libavcodec.so.58.x.y).
  cp -Pf "$f" "$THD_LIBS/" && n=$((n+1))
done
log "staged $n ffmpeg lib entries -> $THD_LIBS/"

# --- 2c. Stage container-demuxer payload (mp4/ts/m2ts DTS re-enabled) -------
# Patched isomp4/mpegtsdemux (dts_support default TRUE). Optional: if demux-out/
# is absent the boot hook simply skips the demuxer binds (MKV DTS still works).
DMX_DEST=/var/lib/webosbrew/demux25
DMX_ISO=/usr/lib/gstreamer-1.0/libgstisomp4.so
DMX_TSD=/usr/lib/gstreamer-1.0/libgstmpegtsdemux.so
mkdir -p "$DMX_DEST" || log "WARN: cannot create $DMX_DEST"
for so in libgstisomp4.so libgstmpegtsdemux.so; do
  if [ -f "$SELF_DIR/demux-out/$so" ]; then
    cp -f "$SELF_DIR/demux-out/$so" "$DMX_DEST/$so" \
      && log "installed $so -> $DMX_DEST/" || log "WARN: copy $so failed"
  else
    log "note: $SELF_DIR/demux-out/$so not found; container DTS (mp4/ts/m2ts) will be skipped"
  fi
done

# --- 2d. Seed first-run audio defaults (make-up gain + DRC) -----------------
# Gain and DRC shipped OPT-IN while the DSP was still unproven: no config file
# meant fully inert (0.0 dB, DRC off), so an install could not change anyone's
# sound. Now that the curve is validated on-device, that caution costs more
# than it buys - an untouched install leaves DTS/TrueHD quieter and
# un-managed next to native AAC/AC-3, which is what the feature exists to fix.
# So seed a starting point and let users tune down instead of discovering they
# have to tune up.
# Written ONLY when absent: after the first install the file belongs to the
# user (the app's Save owns it), and re-running install.sh must never
# clobber their settings. Retune from the app or per TUNING-RUNBOOK.md.
# NOTE: keep in sync with the app's w25GainConfSeedScript() (CLAUDE.md rule 3).
# The +5.0 dB is not a guess: it is the value the maintainer arrived at BY EAR
# on a real C5, with this same DRC line 100/100 preset active, and has been
# running as a hand-set config. Prefer that over a theoretical figure.
seed_gain_conf() {
  if [ -f "$1" ]; then
    log "note: $1 exists; keeping saved audio settings"
  elif printf '%s\n%s\n%s\n%s\n%s\n' \
      "5.0" "drc=line" "drc_boost=100" "drc_cut=100" "center=0.0" \
      > "$1.tmp" && mv -f "$1.tmp" "$1"; then
    log "seeded first-run audio defaults -> $1 (+5.0 dB, DRC line 100/100)"
  else
    log "WARN: could not seed $1"
  fi
}
seed_gain_conf "$DTS_DEST/gain.conf"
seed_gain_conf "$THD_DEST/gain.conf"

# --- 3. Unmount any existing binds so we regenerate from PRISTINE originals -
# This also has to leave the three stock plugins unshadowed, because the
# compatibility preflight in step 4b fingerprints them straight after.
for T in "$CFG_LIVE" "$GC_LIVE" "$LGLIBAV" "$DMX_ISO" "$DMX_TSD" "$REG_TARGET"; do
  w25_umount "$T"
done

# --- 3a. Generate the codec-capability override (insert TRUEHD+MLP after DTSE)
# awk is idempotent: it only injects when the DTSE object is seen and, guarded
# below, only when TRUEHD is not already present in the source.
if [ -f "$CFG_LIVE" ]; then
  if grep -q '"TRUEHD"' "$CFG_LIVE"; then
    log "note: live capability config already has TRUEHD; copying as-is"
    cp -f "$CFG_LIVE" "$CFG_OVR"
  else
    awk '
      /"name" : "DTSE"/ { indts=1 }
      { print }
      indts && /^ *},/ {
        print "    {";
        print "      \"name\" : \"TRUEHD\",";
        print "      \"channels\" : 8";
        print "    },";
        print "";
        print "    {";
        print "      \"name\" : \"MLP\",";
        print "      \"channels\" : 8";
        print "    },";
        indts=0
      }
    ' "$CFG_LIVE" > "$CFG_OVR" && log "generated capability override $CFG_OVR (TRUEHD+MLP after DTSE)" \
      || log "WARN: capability override generation failed"
  fi
else
  log "WARN: $CFG_LIVE not present; cannot generate capability override"
fi

# --- 3b. Generate the gstcool.conf override (avdec_truehd/mlp=310 rank lever)
if [ -f "$GC_LIVE" ]; then
  if grep -q '^avdec_truehd=' "$GC_LIVE"; then
    log "note: live gstcool.conf already has avdec_truehd; copying as-is"
    cp -f "$GC_LIVE" "$GC_OVR"
  else
    awk '
      { print }
      /^\[sw_decoder\]/ { print "avdec_truehd=310"; print "avdec_mlp=310" }
    ' "$GC_LIVE" > "$GC_OVR" && log "generated gstcool override $GC_OVR (avdec_truehd/mlp=310)" \
      || log "WARN: gstcool override generation failed"
  fi
else
  log "WARN: $GC_LIVE not present; cannot generate gstcool override"
fi

# --- 4. Install the canonical boot/apply script (embedded) + hook ----------
# The boot/apply logic is embedded here as base64 so this installer is a single
# self-contained script (no sibling init file needed). Decodes verbatim to the
# proven init_dts25.sh.
base64 -d > "$INIT_SCRIPT" <<'INIT_B64'
IyEvYmluL3NoCiMgd2ViT1MyNSBEVFMgKyBUcnVlSEQgcmVzdG9yZS4gUnVucyBhdCBib290IHZpYSAvdmFyL2xpYi93ZWJvc2JyZXcvaW5pdC5kL3Jlc3RvcmVfZHRzMjUuCiMKIyBUSFJFRSBCWVRFLUlERU5USUNBTCBDT1BJRVMgKENMQVVERS5tZCBydWxlIDMpOiB0aGlzIGZpbGUsIHRoZSBiYXNlNjQgSU5JVF9CNjQKIyBibG9iIGluIHJlc3RvcmUvaW5zdGFsbC5zaCwgYW5kIHcyNUluaXRTY3JpcHRCb2R5KCkgaW4gYXBwL3NlcnZpY2Uvc2VydmljZS5qcy4KIyBUaGUgYmxvY2sgYmV0d2VlbiB0aGUgVzI1LUNPTVBBVCBtYXJrZXJzIGlzIGFkZGl0aW9uYWxseSBzaGFyZWQgdmVyYmF0aW0gd2l0aAojIHRoZSBhcHAncyByZWFkLW9ubHkgREVURUNUX1BST0JFLCBzbyB0aGUgdmVyZGljdCB0aGUgVUkgc2hvd3MgaXMgdGhlIHZlcmRpY3QKIyB0aGlzIHNjcmlwdCBlbmZvcmNlcy4gQ2hhbmdlIG9uZSBjb3B5IC0+IGNoYW5nZSBhbGwgdGhyZWUuCiMKIyBNT0RFUwojICAgKGRlZmF1bHQpICAgICBhcHBseTogc2VsZi1oZWFsIGNoZWNrICh1bm93bmVkIC0+IHJldmVydCt1bmxpbms7IG93bmVkIGJ1dCB0aGUKIyAgICAgICAgICAgICAgICAgY29yZSBwYXlsb2FkIGlzIGluY29tcGxldGUgLT4gcmVmdXNlLCBkZWxldGUgbm90aGluZykgLT4gdmVyc2lvbgojICAgICAgICAgICAgICAgICBndWFyZCAtPiBpZGVudGl0eSBnYXRlIC0+IGxvYWRlciBnYXRlIC0+IGJpbmRzIC0+IHBvc3QtYmluZAojICAgICAgICAgICAgICAgICBwcm9vZiAtPiByZWdpc3RyeSBjb21taXQuCiMgICBXMjVfQ0hFQ0s9MSAgIHJlYWQtb25seSBwcmVmbGlnaHQgZm9yIGluc3RhbGwuc2ggLyB0aGUgYXBwJ3MgRW5hYmxlOiBwcmludHMKIyAgICAgICAgICAgICAgICAgVkVSRElDVC9SRUFTT04vTEFCRUwvQ0FORk9SQ0UvTE9BREVSIGFuZCBleGl0cy4gQmluZHMgbm90aGluZywKIyAgICAgICAgICAgICAgICAgd3JpdGVzIG5vdGhpbmcsIHRvYXN0cyBub3RoaW5nLgojICAgVzI1X1NUQU5EX0RPV049MQojICAgICAgICAgICAgICAgICBwdXQgdGhpcyBUViBiYWNrIG9uIHN0b2NrIGFuZCBleGl0OiBkcm9wIG91ciBiaW5kcyBhbmQgcmVidWlsZAojICAgICAgICAgICAgICAgICBMRydzIHJlZ2lzdHJ5IGlmIG9uZSBvZiBvdXJzIGlzIGxpdmUuIE5vIGdhdGUsIG5vIGJpbmRzLCBubwojICAgICAgICAgICAgICAgICB0b2FzdCwgYW5kIGl0IGNhbiBuZXZlciBhcHBseSBhbnl0aGluZy4gVGhpcyBpcyB3aGF0IHRoZSB0d28KIyAgICAgICAgICAgICAgICAgaW5zdGFsbGVycyBjYWxsIHdoZW4gdGhlaXIgcHJlZmxpZ2h0IHJlZnVzZXMgQUZURVIgdGhleSBoYXZlCiMgICAgICAgICAgICAgICAgIGFscmVhZHkgZGV0YWNoZWQgdGhlIGJpbmRzLCBzbyAibm90aGluZyBpcyBhcHBsaWVkIiBpcyB0cnVlCiMgICAgICAgICAgICAgICAgIHJhdGhlciB0aGFuIG1lcmVseSBpbnRlbmRlZC4KIyAgIEZPUkNFPTEgICAgICAgZXhwbGljaXQgb3B0LWluIG9uIGEgVFYgdGhhdCBpcyBub3QgaW4gdGhlIHZlcmlmaWVkIHRhYmxlLgojCiMgQWx3YXlzIGV4aXRzIDA6IGEgbm9uLXplcm8gd2Vib3NicmV3IGluaXQgc2NyaXB0IHRyaXBzIHRoZSBmYWlsc2FmZSB0aGF0CiMgZGlzYWJsZXMgQUxMIHJvb3QgY3VzdG9taXNhdGlvbnMgb24gdGhlIG5leHQgYm9vdC4gRXZlcnkgcmVmdXNhbCBwYXRoIGJpbmRzCiMgbm90aGluZyAtLSB0aGUgb3ZlcnJpZGVzIGFyZSBzeXN0ZW0td2lkZSAodGhleSBwcm9wYWdhdGUgaW50byBldmVyeSBhcHAgamFpbCksCiMgc28gIm5vdCBzdXJlIiBtdXN0IG1lYW4gImRvIG5vdCB0b3VjaCB0aGlzIFRWIi4gVGhlIHR3byBjb250YWluZXIgZGVtdXhlcnMgYXJlCiMgT1BUSU9OQUw6IHdpdGhvdXQgdGhlbSBEVFMgc3RpbGwgd29ya3MgaW4gTUtWLCB3aGljaCBpcyBob3cgdGhpcyBzaGlwcGVkIGJlZm9yZQojIHRoZSBnYXRlIGV4aXN0ZWQsIHNvIGVhY2ggaXMgYm91bmQgb25seSB3aGVuIHN0YWdlZC4KIwojIEEgcmVmdXNhbCBhbHNvIFJFUEFJUlM6IGl0IGRyb3BzIHRoZSBiaW5kcyBhbmQsIGlmIGEgbWVkaWEgcmVnaXN0cnkgd2Ugd3JvdGUgaXMKIyBzdGlsbCBsaXZlLCByZWdlbmVyYXRlcyBMRydzLiBUaGF0IHNlY29uZCBoYWxmIGlzIG5vdCBvcHRpb25hbCAtLSB0aGUgcmVnaXN0cnkKIyBpcyBjb21taXR0ZWQgd2l0aCBgY3AgLWZgIHJhdGhlciB0aGFuIGJpbmQtbW91bnRlZCwgc28gYW4gdW5yZXBhaXJlZCBvbmUga2VlcHMKIyBvdXIgZHRzZGVjIHJlZ2lzdGVyZWQgYnkgYWJzb2x1dGUgcGF0aCBldmVuIHdpdGggZXZlcnkgYmluZCBnb25lLgojCiMgU1RBR0VEIEZJTEVTIEFSRSBMRUZUIElOIFBMQUNFIE9OIEEgUkVGVVNBTCwgREVMSUJFUkFURUxZLiBBIHJlZnVzZWQgaW5zdGFsbAojIGxpbmtzIG5vIGJvb3QgaG9vaywgc28gbm90aGluZyBvZiBvdXJzIGV2ZXIgcnVucyBhZ2FpbiBvbiB0aGF0IFRWOyB0aGUgZmlsZXMKIyB1bmRlciAvdmFyL2xpYi93ZWJvc2JyZXcgYXJlIGluZXJ0IHdpdGhvdXQgdGhlIGJpbmRzLiBUaGV5IGFyZSBrZXB0IGJlY2F1c2UKIyBzdG9jay5mcCBpcyBhbW9uZyB0aGVtLCBhbmQgdGhhdCByZWNvcmRlZCBiYXNlbGluZSBpcyB0aGUgb25seSB3YXkgYSBsYXRlciBib290CiMgY2FuIHRlbGwgInRoZSBmaXJtd2FyZSBjaGFuZ2VkIiBmcm9tICJ0aGlzIFRWIHdhcyBuZXZlciB2ZXJpZmllZCIgLS0gZGVsZXRpbmcgaXQKIyB3b3VsZCBkb3duZ3JhZGUgZXZlcnkgZnV0dXJlIGRyaWZ0IGludG8gYSBiYXJlICJ1bnZlcmlmaWVkIi4gVGhlIGFwcCdzIFVuaW5zdGFsbAojIHJlbW92ZXMgdGhlbSBvbiBkZW1hbmQuCnNldCAtdQpMT0c9L3RtcC9kdHMyNS5sb2cKVzI1X0xPRz0kTE9HCnRvYXN0KCkgeyBsdW5hLXNlbmQgLW4gMSBsdW5hOi8vY29tLndlYm9zLm5vdGlmaWNhdGlvbi9jcmVhdGVUb2FzdCAie1wic291cmNlSWRcIjpcImlvLmdpdGh1Yi5qb3NpcHBhcGV6LmR0c2VuYWJsZXJcIixcIm1lc3NhZ2VcIjpcIiQxXCJ9IiA+L2Rldi9udWxsIDI+JjE7IH0KZWNobyAiLS0tIGR0czI1K3RydWVoZCAkKGRhdGUpIC0tLSIgPj4gJExPRyAyPiYxCiMgPj4+IFcyNS1DT01QQVQtQkVHSU4KIyBDb21wYXRpYmlsaXR5IGdhdGUgKyByZXZlcnNpYmlsaXR5IGhlbHBlcnMgLS0gdGhlIFNJTkdMRSBBVVRIT1JFRCBDT1BZLgojIEV2ZXJ5dGhpbmcgaGVyZSBpcyBlaXRoZXIgYSBwdXJlIG1lYXN1cmVtZW50IG9yIGFuIGV4cGxpY2l0bHktY2FsbGVkIGFjdGlvbjsKIyBtZXJlbHkgc291cmNpbmcgdGhpcyBibG9jayBtb3VudHMsIGRlbGV0ZXMgYW5kIHdyaXRlcyBub3RoaW5nLCB3aGljaCBpcyB3aGF0CiMgbGV0cyB0aGUgYXBwJ3MgcmVhZC1vbmx5IHByb2JlIHJldXNlIGl0IGFzLWlzLgpFWFBFQ1RfR1NUPTEuMjQKIyBTdGFtcCBpZGVudGlmeWluZyB0aGUgR0FURSB0aGlzIHNjcmlwdCBlbmZvcmNlcy4gVGhlIGluc3RhbGxlZCBjb3B5IG9uIGEgVFYgaXMKIyBvbmx5IHJld3JpdHRlbiBieSBFbmFibGUgLyBpbnN0YWxsLnNoLCBzbyBhIFRWIGVuYWJsZWQgdW5kZXIgYW4gb2xkZXIgYXBwIGtlZXBzCiMgcnVubmluZyB0aGF0IG9sZGVyIHNjcmlwdCAtLSB3aGlsZSB0aGUgYXBwJ3Mgb3duIHByb2JlIGp1ZGdlcyB3aXRoIHRoZSBjb21wYXQKIyBibG9jayBlbWJlZGRlZCBpbiB0aGUgTkVXIGJ1aWxkLiBUaGUgYXBwIGNvbXBhcmVzIHRoaXMgdmFsdWUgKHdoaWNoIGl0IHJlYWRzCiMgZnJvbSBpdHMgb3duIGVtYmVkZGVkIGNvcHkgb2YgdGhpcyBibG9jaykgYWdhaW5zdCB0aGUgb25lIGl0IGZpbmRzIGluIHRoZQojIGluc3RhbGxlZCBzY3JpcHQsIGFuZCByZXBvcnRzIHRoZSBob29rIGFzIHN0YWxlIGluc3RlYWQgb2Ygc2lsZW50bHkgcmV3cml0aW5nIGEKIyBwcml2aWxlZ2VkIGZpbGUgYmVoaW5kIHRoZSB1c2VyJ3MgYmFjay4KIwojIEJVTVAgVEhJUyB3aGVuZXZlciB0aGUgYmVoYXZpb3VyIG9mIHRoaXMgc2NyaXB0IGNoYW5nZXMuIEl0IGlzIGRlbGliZXJhdGVseQojIGluZGVwZW5kZW50IG9mIHRoZSBhcHAgdmVyc2lvbjogYSBjb3NtZXRpYyBhcHAgcmVsZWFzZSBtdXN0IG5vdCBpbnZhbGlkYXRlIGEKIyBwZXJmZWN0bHkgY3VycmVudCBob29rLCBhbmQgYSBnYXRlIGNoYW5nZSBtdXN0IG5vdCBoaWRlIGJlaGluZCBhbiB1bmNoYW5nZWQgYXBwCiMgdmVyc2lvbi4gY2hlY2staW5pdC1zeW5jLnNoIHByb3ZlcyB0aGUgdGhyZWUgSU4tUkVQTyBjb3BpZXMgbWF0Y2g7IHRoaXMgcHJvdmVzCiMgdGhlIE9OLVRWIGNvcHkgbWF0Y2hlcyB0aGUgYXBwIHRoYXQgaXMgYXNraW5nLCBhbmQgc3luYy1pbml0LnNoIHJlZnVzZXMgdG8KIyByZWdlbmVyYXRlIHRoZSBkZXJpdmVkIGNvcGllcyBpZiB0aGUgYm9keSBtb3ZlZCB3aGlsZSB0aGlzIGRpZCBub3QuCiMgICAxICBmaXJzdCBnYXRlOiB2ZXJpZmllZC1zZXRzIHRhYmxlLCBsb2FkZXIgZ2F0ZSwgcG9zdC1iaW5kIHByb29mLCBzZWxmLWhlYWwsCiMgICAgICBzdGFuZC1kb3duIG9uIGV2ZXJ5IHJlZnVzYWwsIC9ldGMgZmluZ2VycHJpbnRzLCBob29rIHN0YW1wLgojICAgMiAgdzI1X3N0b2NrX3JlZ2lzdHJ5IHJlZnVzZXMgd2hpbGUgYSBwbHVnaW4gYmluZCBvZiBvdXJzIHN1cnZpdmVzOyB0aGUgdHdvCiMgICAgICBpbnN0YWxsZXJzIHN0YW5kIHRoZSBUViBkb3duIG9uIGEgcmVmdXNhbCBpbnN0ZWFkIG9mIGxlYXZpbmcgaXQgaGFsZi13YXkuClcyNV9HQVRFX1ZFUlNJT049MgpGUD0vdmFyL2xpYi93ZWJvc2JyZXcvZHRzMjUvc3RvY2suZnAKIyBXaGVyZSB0aGUgaW5zdGFsbGVkIGNvcHkgb2YgVEhJUyBzY3JpcHQgbGl2ZXMsIGFuZCB0aGUgYm9vdCBob29rIHRoYXQgc3ltbGlua3MKIyB0byBpdC4gTmFtZWQgaGVyZSwgaW4gdGhlIHNoYXJlZCBibG9jaywgc28gdGhlIHJlYWQtb25seSBwcm9iZSBjYW4gZmluZ2VycHJpbnQKIyB0aGUgc2NyaXB0IGFuZCBzZWUgd2hldGhlciB0aGUgaG9vayBpcyBsaW5rZWQgd2l0aG91dCBkdXBsaWNhdGluZyBlaXRoZXIgcGF0aC4KSU5JVF9TRUxGPS92YXIvbGliL3dlYm9zYnJldy9kdHMyNS9pbml0X2R0czI1LnNoCkhPT0s9L3Zhci9saWIvd2Vib3NicmV3L2luaXQuZC9yZXN0b3JlX2R0czI1ClJFRz0vbW50L2ZsYXNoL2RhdGEvZ3N0XzFfMF9yZWdpc3RyeS5hcm0uYmluCkNGRz0vZXRjL3VtZWRpYXNlcnZlci9kZXZpY2VfY29kZWNfY2FwYWJpbGl0eV9jb25maWcuanNvbgpHQz0vZXRjL2dzdC9nc3Rjb29sLmNvbmYKTEdMSUJBVj0vdXNyL2xpYi9nc3RyZWFtZXItMS4wL2xpYmdzdGxpYmF2LnNvCkxHSVNPPS91c3IvbGliL2dzdHJlYW1lci0xLjAvbGliZ3N0aXNvbXA0LnNvCkxHVFNEPS91c3IvbGliL2dzdHJlYW1lci0xLjAvbGliZ3N0bXBlZ3RzZGVtdXguc28KIyBDT1JFIHBheWxvYWQgLS0gd2l0aG91dCBlaXRoZXIgb2YgdGhlc2UgdGhlcmUgaXMgbm8gRFRTIGFuZCBubyBUcnVlSEQsIHNvIGEKIyBtaXNzaW5nIG9uZSBtZWFucyAiZG8gbm90IGJpbmQgYW55dGhpbmciLgpNWURUUz0vdmFyL2xpYi93ZWJvc2JyZXcvZHRzMjUvbGliZ3N0ZHRzZGVjLnNvCk1ZTElCQVY9L3Zhci9saWIvd2Vib3NicmV3L3RydWVoZC9saWJnc3RsaWJhdi5zbwojIE9QVElPTkFMIHBheWxvYWQ6IHRoZSBwYXRjaGVkIGNvbnRhaW5lciBkZW11eGVycy4gQWJzZW50LCBEVFMgc3RpbGwgd29ya3MgaW4KIyBNS1YgLS0gd2hpY2ggaXMgZXhhY3RseSBob3cgdGhpcyBzaGlwcGVkIGJlZm9yZSB0aGUgZ2F0ZSBleGlzdGVkIC0tIHNvIGVhY2ggaXMKIyBib3VuZCBvbmx5IHdoZW4gc3RhZ2VkIGFuZCBpcyBuZXZlciBhIHJlYXNvbiB0byByZWZ1c2Ugb3IgdG8gZGVsZXRlIGFueXRoaW5nLgpNWUlTTz0vdmFyL2xpYi93ZWJvc2JyZXcvZGVtdXgyNS9saWJnc3Rpc29tcDQuc28KTVlUU0Q9L3Zhci9saWIvd2Vib3NicmV3L2RlbXV4MjUvbGliZ3N0bXBlZ3RzZGVtdXguc28KTVlDRkc9L3Zhci9saWIvd2Vib3NicmV3L3RydWVoZC9jb2RlY19jYXBhYmlsaXR5Lmpzb24KTVlHQz0vdmFyL2xpYi93ZWJvc2JyZXcvdHJ1ZWhkL2dzdGNvb2wuY29uZgpNWUxJQlM9L3Zhci9saWIvd2Vib3NicmV3L3RydWVoZC9saWJzOi92YXIvbGliL3dlYm9zYnJldy9kdHMyNS9saWJzCncyNV9sb2coKSB7IFsgLW4gIiR7VzI1X0xPRzotfSIgXSB8fCByZXR1cm4gMDsgZWNobyAiW2R0czI1LWdhdGUgJChkYXRlICcrJVktJW0tJWQgJUg6JU06JVMnKV0gJCoiID4+ICIke1cyNV9MT0c6LX0iIDI+JjE7IH0KIyBVbm1vdW50IE9ORSBiaW5kIHRhcmdldCwgZmFsbGluZyBiYWNrIHRvIGEgTEFaWSBkZXRhY2ggd2hlbiBpdCBpcyBidXN5LgojIE1lYXN1cmVkIG9uIGEgcmVhbCBDNTogdW1vdW50IG9mIC91c3IvbGliL2dzdHJlYW1lci0xLjAvbGliZ3N0bGliYXYuc28gZmFpbHMKIyB3aXRoICJ0YXJnZXQgaXMgYnVzeSIgYmVjYXVzZSBXZWJBcHBNZ3IgaGFzIHRoZSAuc28gbWFwcGVkLCB3aGlsZSBgdW1vdW50IC1sYAojIHN1Y2NlZWRzLiBXaXRob3V0IHRoaXMgZmFsbGJhY2sgRGlzYWJsZSBvbmx5IGxvZ3MgYSBXQVJOIGFuZCBzaWxlbnRseSBsZWF2ZXMKIyB0aGUgb3ZlcnJpZGUgYXBwbGllZC4KdzI1X3Vtb3VudCgpIHsKICBncmVwIC1xICIgJDEgIiAvcHJvYy9tb3VudHMgMj4vZGV2L251bGwgfHwgeyB3MjVfbG9nICJubyBiaW5kIG92ZXIgJDEiOyByZXR1cm4gMDsgfQogIGlmIHVtb3VudCAiJDEiIDI+L2Rldi9udWxsOyB0aGVuIHcyNV9sb2cgInVubW91bnRlZCBiaW5kIG92ZXIgJDEiOyByZXR1cm4gMDsgZmkKICBpZiB1bW91bnQgLWwgIiQxIiAyPi9kZXYvbnVsbDsgdGhlbiB3MjVfbG9nICJsYXp5LWRldGFjaGVkIGJ1c3kgYmluZCBvdmVyICQxIChhIGxpdmUgbWFwcGluZyBoZWxkIGl0KSI7IHJldHVybiAwOyBmaQogIHcyNV9sb2cgIldBUk4gY291bGQgbm90IHVubW91bnQgJDEsIGV2ZW4gbGF6aWx5IgogIHJldHVybiAxCn0KIyBEcm9wIGV2ZXJ5IG92ZXJyaWRlIFdFIGFwcGxpZWQgLS0gcm9vdGZzIHBhdGhzIG9ubHkuIFRoZSBzYW1lIGJpbmRzIHByb3BhZ2F0ZQojIGludG8gZWFjaCBhcHAgamFpbCAoMjcgamFpbC1zaWRlIGNvcGllcyBwZXIgbGlicmFyeSBvbiBhIHJlYWwgQzUpOyB0aG9zZSBhcmUKIyBsZWZ0IGFsb25lIGRlbGliZXJhdGVseSwgYmVjYXVzZSBkZXRhY2hpbmcgYSBqYWlsJ3Mgb3duIHZpZXcgd291bGQgYnJlYWsgdGhhdAojIGphaWwuICRSRUcgaXMgaW5jbHVkZWQgYmVjYXVzZSBvbGRlciBidWlsZHMgYmluZC1tb3VudGVkIGl0LgojCiMgQSB0YXJnZXQgdGhhdCBzdXJ2aXZlcyBldmVuIGEgbGF6eSBkZXRhY2ggaXMgUkVQT1JURUQsIG5vdCBzd2FsbG93ZWQ6IGl0IG1lYW5zCiMgdGhlIHJldmVydCBkaWQgbm90IGFjdHVhbGx5IGhhcHBlbiwgYW5kIHNpbGVudGx5IGNsYWltaW5nIHN1Y2Nlc3MgaXMgcHJlY2lzZWx5CiMgdGhlIGNsYXNzIG9mIGZhaWx1cmUgdGhpcyB3aG9sZSBjaGFuZ2UgZXhpc3RzIHRvIHJlbW92ZS4gUmV0dXJucyAxIGFuZCBwcmludHMKIyBXQVJOX1VOTU9VTlQ9PHRhcmdldHM+IHNvIGV2ZXJ5IGNhbGxlciAtLSBib290IHNjcmlwdCBhbmQgYXBwIGFsaWtlIC0tIGNhcnJpZXMKIyB0aGUgd2FybmluZyB1cC4KdzI1X2Ryb3BfYmluZHMoKSB7CiAgVU5NT1VOVF9GQUlMRUQ9CiAgZm9yIHQgaW4gIiRDRkciICIkR0MiICIkTEdMSUJBViIgIiRMR0lTTyIgIiRMR1RTRCIgIiRSRUciOyBkbwogICAgdzI1X3Vtb3VudCAiJHQiIHx8IFVOTU9VTlRfRkFJTEVEPSIke1VOTU9VTlRfRkFJTEVEOiskVU5NT1VOVF9GQUlMRUQgfSR0IgogIGRvbmUKICBbIC16ICIkVU5NT1VOVF9GQUlMRUQiIF0gJiYgcmV0dXJuIDAKICB3MjVfbG9nICJXQVJOIHJldmVydCBpbmNvbXBsZXRlIC0tIHN0aWxsIG1vdW50ZWQ6ICRVTk1PVU5UX0ZBSUxFRCIKICBlY2hvICJXQVJOX1VOTU9VTlQ9JFVOTU9VTlRfRkFJTEVEIgogIHJldHVybiAxCn0KIyBUSEUgcmVmdXNhbCBhY3Rpb24uIFN0YW5kaW5nIGRvd24gaXMgbm90ICJza2lwIHRoZSBiaW5kcyIgLS0gaXQgaXMgImxlYXZlIHRoaXMKIyBUViBzdG9jayIuIFRoZSBiaW5kcyBjYW4gYmUgdW5kb25lLCBidXQgdGhlIG1lZGlhIHJlZ2lzdHJ5IGNhbm5vdDogaXQgaXMKIyBjb21taXR0ZWQgd2l0aCBgY3AgLWZgLCBhbmQgYW55IHJlZ2lzdHJ5IFdFIGdlbmVyYXRlZCB3YXMgc2Nhbm5lZCB3aXRoCiMgL3Zhci9saWIvd2Vib3NicmV3L2R0czI1IG9uIHRoZSBwbHVnaW4gcGF0aCwgc28gaXQgcmVnaXN0ZXJzIE9VUiBkdHNkZWMgYnkKIyBhYnNvbHV0ZSBwYXRoIGFuZCBrZWVwcyBkb2luZyBzbyBzeXN0ZW0td2lkZSAoZXZlcnkgb25lIG9mIHRoZSAyNyBqYWlsIHZpZXdzKQojIGxvbmcgYWZ0ZXIgdGhlIGJpbmRzIGFyZSBnb25lLiBEcm9wcGluZyBiaW5kcyB3aGlsZSBsZWF2aW5nIHRoYXQgcmVnaXN0cnkgbGl2ZQojIGlzIGV4YWN0bHkgdGhlIHN0YXRlIHRoZSBnYXRlIGV4aXN0cyB0byBwcmV2ZW50IC0tIGFuZCBpdCBpcyB0aGUgc3RhdGUgYW4gT1RBCiMgdGhhdCBjaGFuZ2VzIHRoZSBzdG9jayBwbHVnaW5zIHdoaWxlIEdTdHJlYW1lciBzdGF5cyAxLjI0IHdvdWxkIGxlYXZlIGJlaGluZC4KIwojIElkZW1wb3RlbnQgYW5kIHNlbGYtbGltaXRpbmc6IHcyNV9zdG9ja19yZWdpc3RyeSBzY2FucyBMRydzIHBsdWdpbiBkaXJlY3RvcmllcwojIE9OTFksIHNvIHRoZSByZWdpc3RyeSBpdCB3cml0ZXMgZG9lcyBub3QgbmFtZSAvdmFyL2xpYi93ZWJvc2JyZXcgYW5kIHRoZSBuZXh0CiMgdzI1X3JlZ19pc19vdXJzIGlzIGZhbHNlIC0tIG5vIHJlcGVhdGVkIDYwcyByZWdlbiBvbiBldmVyeSBib290LiBJdCBhbHNvIHdvcmtzCiMgd2hlbiBvdXIgbGlicmFyaWVzIGFyZSBhbHJlYWR5IGdvbmUsIGZvciB0aGUgc2FtZSByZWFzb24uCncyNV9zdGFuZF9kb3duKCkgewogIHcyNV9kcm9wX2JpbmRzCiAgaWYgdzI1X3JlZ19pc19vdXJzOyB0aGVuCiAgICB3MjVfbG9nICJhIHJlZ2lzdHJ5IG9mIG91cnMgaXMgc3RpbGwgbGl2ZTsgcmVnZW5lcmF0aW5nIHRoZSBzdG9jayByZWdpc3RyeSBzbyBub3RoaW5nIG9mIG91cnMgc3RheXMgcmVnaXN0ZXJlZCIKICAgIHcyNV9zdG9ja19yZWdpc3RyeQogIGZpCiAgcmV0dXJuIDAKfQp3MjVfbWQ1KCkgeyBbIC1mICIkMSIgXSB8fCByZXR1cm4gMDsgbWQ1c3VtICIkMSIgMj4vZGV2L251bGwgfCBjdXQgLWQiICIgLWYxOyB9CncyNV9ib3VuZCgpIHsgaWYgZ3JlcCAtcSAiICQxICIgL3Byb2MvbW91bnRzIDI+L2Rldi9udWxsOyB0aGVuIGVjaG8gMTsgZWxzZSBlY2hvIDA7IGZpOyB9CncyNV9mcF9nZXQoKSB7IFsgLWYgIiRGUCIgXSB8fCByZXR1cm4gMDsgc2VkIC1uICJzL14kMT0vL3AiICIkRlAiIDI+L2Rldi9udWxsIHwgaGVhZCAtbjE7IH0KdzI1X2dzdF9tbSgpIHsgL3Vzci9iaW4vZ3N0LWluc3BlY3QtMS4wIC0tdmVyc2lvbiAyPi9kZXYvbnVsbCB8IHNlZCAtbiAncy9eR1N0cmVhbWVyIFwoWzAtOV0qXC5bMC05XSpcKS4qL1wxL3AnIHwgaGVhZCAtbjE7IH0KdzI1X3Byb2R1Y3RfaWQoKSB7IGNvbW1hbmQgLXYgbnl4LWNtZCA+L2Rldi9udWxsIDI+JjEgfHwgeyBlY2hvIHVua25vd247IHJldHVybiAwOyB9OyB2PSQobnl4LWNtZCBEZXZpY2VJbmZvIHF1ZXJ5IHByb2R1Y3RfaWQgMj4vZGV2L251bGwgfCBoZWFkIC1uMSk7IFsgLW4gIiR2IiBdIHx8IHY9dW5rbm93bjsgZWNobyAiJHYiOyB9CncyNV93ZWJvc19yZWxlYXNlKCkgeyBjb21tYW5kIC12IG55eC1jbWQgPi9kZXYvbnVsbCAyPiYxIHx8IHsgZWNobyB1bmtub3duOyByZXR1cm4gMDsgfTsgdj0kKG55eC1jbWQgT1NJbmZvIHF1ZXJ5IHdlYm9zX3JlbGVhc2UgMj4vZGV2L251bGwgfCBoZWFkIC1uMSk7IFsgLW4gIiR2IiBdIHx8IHY9dW5rbm93bjsgZWNobyAiJHYiOyB9CiMgTWVhc3VyZSB0aGUgU1RPQ0sgZmluZ2VycHJpbnRzIG9mIGV2ZXJ5dGhpbmcgd2Ugc2hhZG93LCBwbHVzIHRoZSBsaXZlIEdTdHJlYW1lcgojIHZlcnNpb24uIFdoaWxlIHdlIGFyZSBFTkFCTEVEIGEgYmluZCBvZiBvdXJzIHNoYWRvd3MgdGhlIHRhcmdldCwgc28gaXRzIGxpdmUKIyBoYXNoIGlzIE9VUlMgYW5kIHRoZSBzdG9jayBoYXNoIGlzIHVubWVhc3VyYWJsZSAtLSBmYWxsIGJhY2sgdG8gd2hhdCBzdG9jay5mcAojIHJlY29yZGVkIHdoZW4gaXQgc3RpbGwgd2FzIHByaXN0aW5lLiBTXyogPSBtZWFzdXJlZCBsaXZlIChlbXB0eSB3aGVuIGJvdW5kKSwKIyBNXyogPSBlZmZlY3RpdmUgc3RvY2sgZmluZ2VycHJpbnQsIEJfKiA9IDEgd2hlbiBvdXIgYmluZCBpcyBwcmVzZW50LgojCiMgVGhlIHR3byAvZXRjIGZpbGVzIG1hdHRlciBhcyBtdWNoIGFzIHRoZSBwbHVnaW5zLiAkTVlDRkcgYW5kICRNWUdDIGFyZQojIFNOQVBTSE9UUywgYXdrLWRlcml2ZWQgYXQgaW5zdGFsbCB0aW1lIGZyb20gdGhlIFRWJ3Mgb3duIGxpdmUKIyBkZXZpY2VfY29kZWNfY2FwYWJpbGl0eV9jb25maWcuanNvbiBhbmQgZ3N0Y29vbC5jb25mLCBhbmQgd2UgYmluZCB0aGVtIG92ZXIgdGhlCiMgb3JpZ2luYWxzIGluZGVmaW5pdGVseS4gVGhvc2Ugb3JpZ2luYWxzIG9ubHkgZXZlciBjaGFuZ2UgdmlhIGFuIE9UQSAtLSBleGFjdGx5CiMgdGhlIGV2ZW50IHRoaXMgZ2F0ZSBleGlzdHMgdG8gY2F0Y2ggLS0gc28gYW4gdXBkYXRlIHRoYXQgcmV3cml0ZXMgZWl0aGVyIG9uZQojIHdoaWxlIGxlYXZpbmcgdGhlIHRocmVlIHBsdWdpbnMgYWxvbmUgbXVzdCBub3QgcmVhZCBhcyAidmVyaWZpZWQiOiB0aGUgaG9vawojIHdvdWxkIHNpbGVudGx5IHJldmVydCBMRydzIG93biBjb25maWcgY2hhbmdlLCBzeXN0ZW0td2lkZSwgZm9yZXZlci4KIwojIFJlc2lkdWFsIHdlIGFyZSBOT1QgZW5naW5lZXJpbmcgYXJvdW5kOiBsaWJnc3RtYXRyb3NrYS5zbyBpcyBuZWl0aGVyIHNoYWRvd2VkCiMgbm9yIGZpbmdlcnByaW50ZWQsIHNvIGFuIE9UQSB0aGF0IGNoYW5nZXMgaXRzIEFfRFRTIHJldGFnIHdvdWxkIHNpbGVudGx5IGxvc2UKIyBNS1YgRFRTLiBUaGF0IGZhaWxzIGluIHRoZSBhY2NlcHRhYmxlIGRpcmVjdGlvbiAtLSBpdCBjb3N0cyBvdXIgY29kZWMgYW5kIGhhcm1zCiMgbm90aGluZyBlbHNlIC0tIGFuZCB0aGUgZml2ZS1lbGVtZW50IHByb29mIHN0aWxsIHBhc3NlcywgYmVjYXVzZSBpdCBjaGVja3MgdGhhdAojIG1hdHJvc2thZGVtdXggUkVHSVNURVJTLCBub3Qgd2hhdCBjYXBzIGl0IGVtaXRzLgp3MjVfbWVhc3VyZSgpIHsKICBCX0xJQkFWPSQodzI1X2JvdW5kICIkTEdMSUJBViIpCiAgQl9JU09NUDQ9JCh3MjVfYm91bmQgIiRMR0lTTyIpCiAgQl9NUEVHVFM9JCh3MjVfYm91bmQgIiRMR1RTRCIpCiAgQl9DRkc9JCh3MjVfYm91bmQgIiRDRkciKQogIEJfR0M9JCh3MjVfYm91bmQgIiRHQyIpCiAgU19MSUJBVj0KICBTX0lTT01QND0KICBTX01QRUdUUz0KICBTX0NGRz0KICBTX0dDPQogIFsgIiRCX0xJQkFWIiA9IDAgXSAmJiBTX0xJQkFWPSQodzI1X21kNSAiJExHTElCQVYiKQogIFsgIiRCX0lTT01QNCIgPSAwIF0gJiYgU19JU09NUDQ9JCh3MjVfbWQ1ICIkTEdJU08iKQogIFsgIiRCX01QRUdUUyIgPSAwIF0gJiYgU19NUEVHVFM9JCh3MjVfbWQ1ICIkTEdUU0QiKQogIFsgIiRCX0NGRyIgPSAwIF0gJiYgU19DRkc9JCh3MjVfbWQ1ICIkQ0ZHIikKICBbICIkQl9HQyIgPSAwIF0gJiYgU19HQz0kKHcyNV9tZDUgIiRHQyIpCiAgTV9MSUJBVj0kU19MSUJBVgogIE1fSVNPTVA0PSRTX0lTT01QNAogIE1fTVBFR1RTPSRTX01QRUdUUwogIE1fQ0ZHPSRTX0NGRwogIE1fR0M9JFNfR0MKICBbIC1uICIkTV9MSUJBViIgXSB8fCBNX0xJQkFWPSQodzI1X2ZwX2dldCBsaWJnc3RsaWJhdikKICBbIC1uICIkTV9JU09NUDQiIF0gfHwgTV9JU09NUDQ9JCh3MjVfZnBfZ2V0IGxpYmdzdGlzb21wNCkKICBbIC1uICIkTV9NUEVHVFMiIF0gfHwgTV9NUEVHVFM9JCh3MjVfZnBfZ2V0IGxpYmdzdG1wZWd0c2RlbXV4KQogIFsgLW4gIiRNX0NGRyIgXSB8fCBNX0NGRz0kKHcyNV9mcF9nZXQgZGV2aWNlX2NvZGVjX2NhcGFiaWxpdHlfY29uZmlnKQogIFsgLW4gIiRNX0dDIiBdIHx8IE1fR0M9JCh3MjVfZnBfZ2V0IGdzdGNvb2wpCiAgR1NUX01NX05PVz0kKHcyNV9nc3RfbW0pCiAgWyAtbiAiJEdTVF9NTV9OT1ciIF0gfHwgR1NUX01NX05PVz11bmtub3duCiAgcmV0dXJuIDAKfQojIFJlY29yZGVkLXZzLW1lYXN1cmVkIGNvbXBhcmlzb24gdGhhdCB0cmVhdHMgIndlIGhhdmUgbm8gcmVjb3JkZWQgdmFsdWUiIGFzCiMgYWJzZW5jZSBvZiBldmlkZW5jZSByYXRoZXIgdGhhbiBhcyBkcmlmdC4gTmVlZGVkIGZvciB0aGUgdHdvIC9ldGMga2V5cywgd2hpY2ggYQojIHN0b2NrLmZwIHdyaXR0ZW4gYnkgYW4gZWFybGllciBidWlsZCBzaW1wbHkgZG9lcyBub3QgY29udGFpbiAtLSBjb21wYXJpbmcgYW4KIyBlbXB0eSByZWNvcmRpbmcgYWdhaW5zdCBhIHJlYWwgaGFzaCB3b3VsZCByZXBvcnQgZHJpZnQgb24gZXZlcnkgdXBncmFkZS4KdzI1X2ZwX2RpZmZlcnMoKSB7IFsgLW4gIiQxIiBdICYmIFsgLW4gIiQyIiBdICYmIFsgIiQxIiAhPSAiJDIiIF07IH0KIyBHdWFyZCBsYXllciAwOiBvdXIgYmluZC1vdmVyIGxpYnMgYXJlIGFybWVsIEdTdHJlYW1lci0xLjI0IGJ1aWxkcy4gQmluZGluZwojIHRoZW0gb3ZlciBhIGRpZmZlcmVudC1BQkkgTEcgbGliIGFmdGVyIGFuIE9UQSB3b3VsZCBicmVhayBBTEwgbXA0L3RzL21rdgojIHBsYXliYWNrLCBhbmQgbm8gb3B0LWluIG1heSBvdmVycmlkZSB0aGF0Lgp3MjVfZ3N0X29rKCkgeyBbICIkR1NUX01NX05PVyIgPSAiJEVYUEVDVF9HU1QiIF07IH0KIyBHYXRlIGxheWVyIDEgLS0gaWRlbnRpdHkuIFNldHMgVkVSRElDVCBSRUFTT04gTEFCRUwgQ0FORk9SQ0UgZnJvbSB0aGUgbWVhc3VyZWQKIyBzdG9jayBmaW5nZXJwcmludHM6CiMgICB2ZXJpZmllZCAgIHRoZSBtZDVzIGFyZSBpbiB0aGUgdmVyaWZpZWQtc2V0cyB0YWJsZSBiZWxvdwojICAgZm9yY2VkICAgICBubyB0YWJsZSBtYXRjaCwgYnV0IHRoZSB1c2VyIG9wdGVkIGluIGFuZCBub3RoaW5nIGNoYW5nZWQgc2luY2UKIyAgIGRyaWZ0ICAgICAgc3RvY2suZnAgcmVjb3JkZWQgRElGRkVSRU5UIG1kNXMgLT4gZmlybXdhcmUgdXBkYXRlLCBzdGFuZCBkb3duCiMgICAgICAgICAgICAgIFVOQ09ORElUSU9OQUxMWSAoRk9SQ0UgY2Fubm90IG92ZXJyaWRlIGl0LCBhbmQgbmVpdGhlciBjYW4gdGhlCiMgICAgICAgICAgICAgIEFCSS1jaGFuZ2UgZHJpZnQgdzI1X2dhdGUgcmVwb3J0cykKIyAgIHVudmVyaWZpZWQgbm8gbWF0Y2ggYW5kIG5vIG9wdC1pbiAtPiBiaW5kIG5vdGhpbmcKIyBUaGUgbWQ1IG9mIHRoZSBzdG9jayBsaWJzIGlzIHRoZSBrZXksIG5vdCB0aGUgbW9kZWwgbmFtZTogaWRlbnRpY2FsIGhhc2hlcwojIG1lYW4gdGhlc2UgYXJlIGxpdGVyYWxseSB0aGUgbGlicmFyaWVzIHRoZSBwYXlsb2FkIHdhcyB2ZXJpZmllZCBhZ2FpbnN0Lgp3MjVfdmVyZGljdCgpIHsKICBWRVJESUNUPXVudmVyaWZpZWQKICBSRUFTT049CiAgTEFCRUw9CiAgQ0FORk9SQ0U9MAogIGlmIFsgLXogIiRNX0xJQkFWIiBdIHx8IFsgLXogIiRNX0lTT01QNCIgXSB8fCBbIC16ICIkTV9NUEVHVFMiIF07IHRoZW4KICAgIFJFQVNPTj0idGhlIHN0b2NrIEdTdHJlYW1lciBwbHVnaW4gZmluZ2VycHJpbnRzIGNvdWxkIG5vdCBiZSByZWFkIG9uIHRoaXMgVFYiCiAgICByZXR1cm4gMAogIGZpCiAgIyBEUklGVCBJUyBDSEVDS0VEIEJFRk9SRSBUSEUgVEFCTEUsIGFuZCB0aGF0IG9yZGVyaW5nIGlzIGxvYWQtYmVhcmluZy4gVGhlCiAgIyB0YWJsZSBjYW4gb25seSBrZXkgb24gZ3N0X21tICsgdGhlIHRocmVlIHBsdWdpbiBtZDVzLCBzbyBpdCBjYW5ub3QgZXhwcmVzcyB0aGUKICAjIHN0YXRlIG9mIHRoZSB0d28gL2V0YyBmaWxlcyAtLSB3aGljaCBtZWFucyBhIHRhYmxlIG1hdGNoIHdvdWxkIHJldHVybgogICMgYHZlcmlmaWVkYCBhbmQgbWFzayBhbiBPVEEgdGhhdCByZXdyb3RlIG9ubHkgZ3N0Y29vbC5jb25mIG9yIHRoZSBjb2RlYwogICMgY2FwYWJpbGl0eSBKU09OLiAiSGFzIHRoaXMgVFYgY2hhbmdlZCBzaW5jZSB3ZSByZWNvcmRlZCBpdCIgdGhlcmVmb3JlIG91dHJhbmtzCiAgIyAiZG9lcyB0aGlzIFRWIGxvb2sgbGlrZSBhIGtub3duLWdvb2Qgb25lIi4KICBGUF9BVj0kKHcyNV9mcF9nZXQgbGliZ3N0bGliYXYpCiAgRlBfSVNPPSQodzI1X2ZwX2dldCBsaWJnc3Rpc29tcDQpCiAgRlBfVFNEPSQodzI1X2ZwX2dldCBsaWJnc3RtcGVndHNkZW11eCkKICBGUF9DRkc9JCh3MjVfZnBfZ2V0IGRldmljZV9jb2RlY19jYXBhYmlsaXR5X2NvbmZpZykKICBGUF9HQz0kKHcyNV9mcF9nZXQgZ3N0Y29vbCkKICAjIFRoZSB0aHJlZSBwbHVnaW4gaGFzaGVzIGNvbXBhcmUgc3RyaWN0bHkgKHRoZXkgaGF2ZSBhbHdheXMgYmVlbiByZWNvcmRlZCkuCiAgIyBUaGUgdHdvIC9ldGMgaGFzaGVzIGdvIHRocm91Z2ggdzI1X2ZwX2RpZmZlcnMgc28gYW4gb2xkZXIgc3RvY2suZnAgdGhhdCBuZXZlcgogICMgcmVjb3JkZWQgdGhlbSBkb2VzIG5vdCByZWFkIGFzIGRyaWZ0LgogIERSSUZUX1dIQVQ9CiAgRFJJRlRfUExVR0lOUz0wCiAgRFJJRlRfQ09ORklHPTAKICBbICIkRlBfQVYiICE9ICIkTV9MSUJBViIgXSAmJiB7IERSSUZUX1dIQVQ9IiR7RFJJRlRfV0hBVDorJERSSUZUX1dIQVQgfWxpYmdzdGxpYmF2LnNvIjsgRFJJRlRfUExVR0lOUz0xOyB9CiAgWyAiJEZQX0lTTyIgIT0gIiRNX0lTT01QNCIgXSAmJiB7IERSSUZUX1dIQVQ9IiR7RFJJRlRfV0hBVDorJERSSUZUX1dIQVQgfWxpYmdzdGlzb21wNC5zbyI7IERSSUZUX1BMVUdJTlM9MTsgfQogIFsgIiRGUF9UU0QiICE9ICIkTV9NUEVHVFMiIF0gJiYgeyBEUklGVF9XSEFUPSIke0RSSUZUX1dIQVQ6KyREUklGVF9XSEFUIH1saWJnc3RtcGVndHNkZW11eC5zbyI7IERSSUZUX1BMVUdJTlM9MTsgfQogIHcyNV9mcF9kaWZmZXJzICIkRlBfQ0ZHIiAiJE1fQ0ZHIiAmJiB7IERSSUZUX1dIQVQ9IiR7RFJJRlRfV0hBVDorJERSSUZUX1dIQVQgfWRldmljZV9jb2RlY19jYXBhYmlsaXR5X2NvbmZpZy5qc29uIjsgRFJJRlRfQ09ORklHPTE7IH0KICB3MjVfZnBfZGlmZmVycyAiJEZQX0dDIiAiJE1fR0MiICYmIHsgRFJJRlRfV0hBVD0iJHtEUklGVF9XSEFUOiskRFJJRlRfV0hBVCB9Z3N0Y29vbC5jb25mIjsgRFJJRlRfQ09ORklHPTE7IH0KICBpZiBbIC1uICIkRlBfQVYkRlBfSVNPJEZQX1RTRCIgXSAmJiBbIC1uICIkRFJJRlRfV0hBVCIgXTsgdGhlbgogICAgIyBVTkNPTkRJVElPTkFMIHJlZnVzYWwgLS0gRk9SQ0UgaXMgZGVsaWJlcmF0ZWx5IG5vdCBjb25zdWx0ZWQgaGVyZSwgYW5kCiAgICAjIENBTkZPUkNFPTAgc28gbm90aGluZyBhZHZlcnRpc2VzIGFuIGVzY2FwZSBoYXRjaCB0aGF0IGRvZXMgbm90IGV4aXN0LgogICAgIyBBIGRyaWZ0LXNwZWNpZmljIG92ZXJyaWRlIHdvdWxkIGJlIHJlZHVuZGFudDogdW5pbnN0YWxsIHJlbW92ZXMgc3RvY2suZnAsCiAgICAjIHNvIHVuaW5zdGFsbC10aGVuLWVuYWJsZSBwdXRzIHRoaXMgVFYgYmFjayBpbnRvIHRoZSAidW52ZXJpZmllZCIgZmxvdywgd2hpY2gKICAgICMgYWxyZWFkeSBoYXMgYW4gZXhwbGljaXQsIGNvbnNlbnRlZCBvcHQtaW4uIFJlZnVzaW5nIG91dHJpZ2h0IGtlZXBzIHRoZSBzdGF0ZQogICAgIyBtYWNoaW5lIHNtYWxsZXIgYW5kIHRoZSBydWxlIGFic29sdXRlOiBhIGZpcm13YXJlIGNoYW5nZSB0aGF0IHRvdWNoZXMgdGhlCiAgICAjIHBsdWdpbnMgd2Ugc2hhZG93IHN0YW5kcyB1cyBkb3duLCBmdWxsIHN0b3AuCiAgICBWRVJESUNUPWRyaWZ0CiAgICBDQU5GT1JDRT0wCiAgICAjIFRoZSByZW1lZHkgZGVwZW5kcyBvbiBXSEFUIGRyaWZ0ZWQuIEEgcGx1Z2luIGNoYW5nZSBpcyBzb21ldGhpbmcgYSB2ZXJpZmllZAogICAgIyBzZXQgY2FuIGRlc2NyaWJlLCBzbyB0aGUgZmluZ2VycHJpbnRzIGFyZSB3b3J0aCByZXBvcnRpbmcuIEEgY2hhbmdlIHRvIHRoZQogICAgIyB0d28gL2V0YyBmaWxlcyBpcyBOT1Q6IG5vIHRhYmxlIHJvdyBjYW4gZXZlciBjbGVhciBpdCwgYmVjYXVzZSB0aGUgdGFibGUKICAgICMga2V5cyBvbiBwbHVnaW5zIG9ubHkgLS0gdGhlIHNuYXBzaG90cyBzaW1wbHkgaGF2ZSB0byBiZSByZXRha2VuIGZyb20gdGhlCiAgICAjIFRWJ3MgbmV3IGNvbmZpZywgd2hpY2ggaXMgd2hhdCBFbmFibGUgZG9lcy4KICAgIGlmIFsgIiREUklGVF9QTFVHSU5TIiA9IDEgXSAmJiBbICIkRFJJRlRfQ09ORklHIiA9IDEgXTsgdGhlbgogICAgICBEUklGVF9GSVg9InVuaW5zdGFsbCB0aGVuIGVuYWJsZSBhZ2FpbiB0byByZS1zbmFwc2hvdCB0aGlzIFRWJ3MgY29uZmlndXJhdGlvbiwgYW5kIHJlcG9ydCB0aGUgbmV3IHBsdWdpbiBmaW5nZXJwcmludHMgc28gdGhpcyBUViBjYW4gYmUgYWRkZWQgdG8gdGhlIHZlcmlmaWVkIHRhYmxlIgogICAgZWxpZiBbICIkRFJJRlRfUExVR0lOUyIgPSAxIF07IHRoZW4KICAgICAgRFJJRlRfRklYPSJyZXBvcnQgdGhlIG5ldyBmaW5nZXJwcmludHMgc28gdGhpcyBUViBjYW4gYmUgYWRkZWQgdG8gdGhlIHZlcmlmaWVkIHRhYmxlLCBvciB1bmluc3RhbGwgdGhlbiBlbmFibGUgYWdhaW4gdG8gb3B0IGluIGV4cGxpY2l0bHkiCiAgICBlbHNlCiAgICAgIERSSUZUX0ZJWD0idW5pbnN0YWxsIHRoZW4gZW5hYmxlIGFnYWluIHRvIHJlLXNuYXBzaG90IHRoaXMgVFYncyBjb25maWd1cmF0aW9uIChubyB2ZXJpZmllZC1zZXQgZW50cnkgY2FuIGNvdmVyIGEgY29uZmlnIGNoYW5nZSkiCiAgICBmaQogICAgUkVBU09OPSJ0aGlzIFRWIGNoYW5nZWQgc2luY2UgaXQgd2FzIGxhc3QgdmVyaWZpZWQgKCREUklGVF9XSEFUKSwgc28gbm90aGluZyB3YXMgYXBwbGllZDsgJERSSUZUX0ZJWCIKICAgIHJldHVybiAwCiAgZmkKICB3aGlsZSBJRlM9J3wnIHJlYWQgLXIgdF9tbSB0X2F2IHRfaXNvIHRfdHNkIHRfbGFiZWw7IGRvCiAgICBjYXNlICIkdF9tbSIgaW4gJyd8XCMqKSBjb250aW51ZSA7OyBlc2FjCiAgICBpZiBbICIkdF9tbSIgPSAiJEdTVF9NTV9OT1ciIF0gJiYgWyAiJHRfYXYiID0gIiRNX0xJQkFWIiBdICYmIFsgIiR0X2lzbyIgPSAiJE1fSVNPTVA0IiBdICYmIFsgIiR0X3RzZCIgPSAiJE1fTVBFR1RTIiBdOyB0aGVuCiAgICAgIFZFUkRJQ1Q9dmVyaWZpZWQKICAgICAgTEFCRUw9JHRfbGFiZWwKICAgICAgUkVBU09OPSJzdG9jayBwbHVnaW4gZmluZ2VycHJpbnRzIG1hdGNoIGEgVFYgdGhpcyBwYXlsb2FkIHdhcyB2ZXJpZmllZCBvbiIKICAgICAgYnJlYWsKICAgIGZpCiAgZG9uZSA8PCdXMjVfU0VUUycKIyBnc3RfbW18bGliZ3N0bGliYXZ8bGliZ3N0aXNvbXA0fGxpYmdzdG1wZWd0c2RlbXV4fGxhYmVsCjEuMjR8MGZkNmQ2NWFjOWUzYTc4YjM5M2E2MTVlYWZmOGFjMGJ8NTdmZTU3MDYwNzc0ZjI0OGMwNWFmNWE0MTFmYzlhOGZ8OWI4NGE5NWNmMjliYzAyNTU1M2M3ZGVlODI5YjdjYzF8TEcgQzUgT0xFRDc3QzUxTEEgKHdlYk9TIDEwLjMuMSwgR1N0cmVhbWVyIDEuMjQuMCkKVzI1X1NFVFMKICBbICIkVkVSRElDVCIgPSB2ZXJpZmllZCBdICYmIHJldHVybiAwCiAgaWYgWyAiJCh3MjVfZnBfZ2V0IGZvcmNlZCkiID0gMSBdICYmIFsgLW4gIiRGUF9BViIgXTsgdGhlbgogICAgVkVSRElDVD1mb3JjZWQKICAgIENBTkZPUkNFPTEKICAgIFJFQVNPTj0ibm90IGEgdmVyaWZpZWQgVFYsIGJ1dCB5b3Ugb3B0ZWQgaW4gYW5kIG5vdGhpbmcgaGFzIGNoYW5nZWQgc2luY2UiCiAgICByZXR1cm4gMAogIGZpCiAgaWYgWyAiJHtGT1JDRTotMH0iID0gMSBdOyB0aGVuCiAgICBWRVJESUNUPWZvcmNlZAogICAgQ0FORk9SQ0U9MQogICAgUkVBU09OPSJub3QgYSB2ZXJpZmllZCBUVjsgYXBwbHlpbmcgYmVjYXVzZSB5b3UgZXhwbGljaXRseSBvcHRlZCBpbiIKICAgIHJldHVybiAwCiAgZmkKICBDQU5GT1JDRT0xCiAgUkVBU09OPSJ0aGlzIFRWJ3Mgc3RvY2sgR1N0cmVhbWVyIHBsdWdpbnMgbWF0Y2ggbm8gVFYgdGhpcyBwYXlsb2FkIHdhcyB2ZXJpZmllZCBvbiIKICByZXR1cm4gMAp9CiMgVmVyc2lvbiBndWFyZCArIGlkZW50aXR5IGdhdGUgYXMgb25lIGNhbGwsIGZvciB0aGUgcmVhZC1vbmx5IGNhbGxlcnMgKHRoZQojIGFwcCdzIHByb2JlIGFuZCBXMjVfQ0hFQ0s9MSkuIFRoZSBhcHBseSBwYXRoIGJlbG93IHJ1bnMgdGhlIHR3byBhcyBzZXBhcmF0ZQojIG9yZGVyZWQgc3RlcHMgc28gZWFjaCBnZXRzIGl0cyBvd24gbG9nIGxpbmUgYW5kIHRvYXN0Lgp3MjVfZ2F0ZSgpIHsKICB3MjVfZ3N0X29rICYmIHsgdzI1X3ZlcmRpY3Q7IHJldHVybiAwOyB9CiAgVkVSRElDVD1kcmlmdAogIENBTkZPUkNFPTAKICBMQUJFTD0KICBSRUFTT049IkdTdHJlYW1lciAkR1NUX01NX05PVyBpcyBub3QgdGhlICRFWFBFQ1RfR1NUIHRoaXMgcGF5bG9hZCB3YXMgYnVpbHQgZm9yOyBhIGZpcm13YXJlIHVwZGF0ZSBjaGFuZ2VkIHRoZSBwbHVnaW4gQUJJIgogIHJldHVybiAwCn0KdzI1X2xvYWRlcigpIHsKICBmb3IgZiBpbiAvbGliL2xkLWxpbnV4LnNvLjMgL2xpYi9sZC1saW51eC1hcm1oZi5zby4zIC9saWIvbGQtbGludXguc28uMiAvbGliL2xkLWxpbnV4Ki5zby4qIC9saWIvbGQtKi5zby4qOyBkbwogICAgWyAteCAiJGYiIF0gJiYgeyBwcmludGYgJyVzXG4nICIkZiI7IHJldHVybiAwOyB9CiAgZG9uZQogIHJldHVybiAxCn0KIyBHYXRlIGxheWVyIDJhIC0tIGxvYWRlciByZXNvbHV0aW9uLiBFdmVyeSBwYXlsb2FkIG9iamVjdCB3ZSBhcmUgYWJvdXQgdG8gYmluZAojIG9yIHJlZ2lzdGVyIG11c3QgaGF2ZSBBTEwgaXRzIGR5bmFtaWMgZGVwZW5kZW5jaWVzIHJlc29sdmFibGUgb24gVEhJUyBUVi4KIyBUaGUgYXNzZXJ0aW9uIGlzIHRoYXQgT1VSIGRlcHMgcmVzb2x2ZSwgTk9UIHRoYXQgb3VyIHNvbmFtZXMgbWF0Y2ggTEcnczoKIyBzdG9jayBsaWJhdiBvbiB0aGUgdmVyaWZpZWQgQzUgaXMgZmZtcGVnIDUueCAobGliYXZjb2RlYy5zby41OSwKIyBsaWJhdmZvcm1hdC5zby41OSwgbGliYXZ1dGlsLnNvLjU3LCBsaWJhdmZpbHRlci5zby44KSB3aGlsZSBvdXJzIGlzIGZmbXBlZyA0LjQKIyAoLjU4Ly41OC8uNTYvLjcpLCBzbyBhIHNvbmFtZS1lcXVhbGl0eSBjaGVjayBhZ2FpbnN0IHN0b2NrIHdvdWxkIHJlZnVzZSBhIFRWCiMgd2hlcmUgdGhlIHBheWxvYWQgZGVtb25zdHJhYmx5IHdvcmtzLiBPdXIgb2JqZWN0cyBjYXJyeQojIFJVTlBBVEg9L3Zhci9saWIvd2Vib3NicmV3L3RydWVoZC9saWJzOyAkTVlMSUJTIGlzIGtlcHQgZm9yIHRoZSBkdHMyNS9saWJzIGNhc2UuCiMgTE9BREVSX1NUQUdFRCBkaXN0aW5ndWlzaGVzICJ0aGVzZSBsaWJyYXJpZXMgY2Fubm90IGxvYWQgb24gdGhpcyBUViIgKGEgcmVhbAojIHJlZnVzYWwsIGFuZCBmb3JjaW5nIHdvdWxkIG5vdCBoZWxwKSBmcm9tICJ0aGUgY29yZSBwYXlsb2FkIGlzIG5vdCBzdGFnZWQiICh0aGUKIyBzdGF0ZSBiZWZvcmUgdGhlIGZpcnN0IEVuYWJsZSwgd2hlcmUgdGhlIGFuc3dlciBpcyBzaW1wbHkgbm90IGtub3duKS4gVGhlIGFwcAojIHVzZXMgdGhhdCB0byBkZWNpZGUgd2hldGhlciBvZmZlcmluZyAiVHJ5IGFueXdheSIgd291bGQgYmUgaG9uZXN0LgojCiMgT25seSB0aGUgQ09SRSBvYmplY3RzIGFyZSByZXF1aXJlZC4gVGhlIG9wdGlvbmFsIGRlbXV4ZXJzIGFyZSBjaGVja2VkIHdoZW4gdGhleQojIGFyZSBzdGFnZWQgYW5kIHNraXBwZWQgd2hlbiB0aGV5IGFyZSBub3QsIHNvIGEgY29yZS1vbmx5IGluc3RhbGwgaXMgYSBmaXJzdAojIGNsYXNzIGNvbmZpZ3VyYXRpb24gcmF0aGVyIHRoYW4gYSBmYWlsdXJlLgp3MjVfY29yZV9zdGFnZWQoKSB7IFsgLWYgIiRNWURUUyIgXSAmJiBbIC1mICIkTVlMSUJBViIgXTsgfQp3MjVfbG9hZGVyX29rKCkgewogIExPQURFUl9NSVNTPQogIExPQURFUl9TVEFHRUQ9MQogIExEX1NPPSQodzI1X2xvYWRlcikKICBpZiBbIC16ICIke0xEX1NPOi19IiBdOyB0aGVuIExPQURFUl9NSVNTPSJubyBkeW5hbWljIGxvYWRlciBmb3VuZCBvbiB0aGlzIFRWIjsgcmV0dXJuIDE7IGZpCiAgaWYgISB3MjVfY29yZV9zdGFnZWQ7IHRoZW4KICAgIExPQURFUl9TVEFHRUQ9MAogICAgTE9BREVSX01JU1M9InRoZSBjb3JlIHBheWxvYWQgaXMgbm90IHN0YWdlZCAoJE1ZRFRTIC8gJE1ZTElCQVYpIgogICAgcmV0dXJuIDEKICBmaQogIGZvciBzbyBpbiAiJE1ZRFRTIiAiJE1ZTElCQVYiICIkTVlJU08iICIkTVlUU0QiOyBkbwogICAgWyAtZiAiJHNvIiBdIHx8IGNvbnRpbnVlCiAgICBuPSQoTERfTElCUkFSWV9QQVRIPSIkTVlMSUJTIiBMRF9UUkFDRV9MT0FERURfT0JKRUNUUz0xICIkTERfU08iICIkc28iIDI+JjEgfCBncmVwIC1jICJub3QgZm91bmQiKQogICAgaWYgWyAiJG4iICE9IDAgXTsgdGhlbiBMT0FERVJfTUlTUz0iJHNvIGhhcyAkbiB1bnJlc29sdmVkIGRlcGVuZGVuY2llcyBvbiB0aGlzIFRWIjsgcmV0dXJuIDE7IGZpCiAgZG9uZQogIHJldHVybiAwCn0KIyBJcyB0aGUgbGl2ZSBtZWRpYSByZWdpc3RyeSBvbmUgV0Ugd3JvdGU/IEl0IGlzIGNvbW1pdHRlZCB3aXRoIGBjcCAtZmAsIG5vdAojIGJpbmQtbW91bnRlZCwgc28gdGhlcmUgaXMgbm8gbW91bnQgdG8gbG9vayBmb3IgLS0gYnV0IGEgcmVnaXN0cnkgd2UgZ2VuZXJhdGVkCiMgbmFtZXMgb3VyIHBsdWdpbiBkaXJlY3RvcmllcywgYW5kIGEgc3RvY2sgb25lIG5ldmVyIGRvZXMuIFRoaXMgaXMgdGhlIHNpZ25hbAojIGZvciAiYSByZWdpc3RyeSBvZiBvdXJzIGlzIGxpdmUiLCB3aGljaCBtYXR0ZXJzIHdoZW4gb3VyIGxpYnJhcmllcyBoYXZlIGdvbmUKIyBtaXNzaW5nIHVuZGVybmVhdGggaXQuCncyNV9yZWdfaXNfb3VycygpIHsgWyAtZiAiJFJFRyIgXSAmJiBncmVwIC1xICIvdmFyL2xpYi93ZWJvc2JyZXciICIkUkVHIiAyPi9kZXYvbnVsbDsgfQojIEdhdGUgbGF5ZXIgMmIgLS0gcG9zdC1iaW5kIHBpcGVsaW5lIHByb29mLiBUaGUgcmVnZW5lcmF0ZWQgcmVnaXN0cnkgbXVzdCBjYXJyeQojIEFMTCBGSVZFIGVsZW1lbnRzIHRoZSBEVFMvVHJ1ZUhEIHBhdGggbmVlZHM6IG91ciB0d28gZGVjb2RlcnMgQU5EIHRoZSB0aHJlZQojIGRlbXV4ZXJzIHdlIHNoYWRvdyAoYWxsIHRocmVlIGFyZSBwcmVzZW50IGluIHRoZSBtZWRpYSByZWdpc3RyeSB0b2RheSkuCiMgQSBtaXNzaW5nIGRlbXV4ZXIgbWVhbnMgb3VyIG92ZXJyaWRlIHByb2R1Y2VkIGEgcGx1Z2luIHRoZSByZWdpc3RyeSBjYW5ub3QKIyB1c2UsIGkuZS4gYSBicm9rZW4gbXA0L3RzL21rdiBwaXBlbGluZSAtLSBzbyB0aGUgY2FsbGVyIHJlZnVzZXMgdGhlIGNvbW1pdCBhbmQKIyBkcm9wcyB0aGUgYmluZHMsIHdoaWNoIHR1cm5zICJ0aGUgb3ZlcnJpZGUgZGlkbid0IG1hdGNoIiBpbnRvIGEgcGxhaW4gbm8tb3AuCncyNV9yZWdfaGFzX2FsbCgpIHsKICBSRUdfTUlTUz0KICBmb3IgZSBpbiBkdHNkZWMgYXZkZWNfdHJ1ZWhkIHF0ZGVtdXggdHNkZW11eCBtYXRyb3NrYWRlbXV4OyBkbwogICAgR1NUX1JFR0lTVFJZXzFfMD0iJDEiIEdTVF9SRUdJU1RSWV9VUERBVEU9bm8gR1NUX1JFR0lTVFJZX0ZPUks9bm8gL3Vzci9iaW4vZ3N0LWluc3BlY3QtMS4wICIkZSIgPi9kZXYvbnVsbCAyPiYxIHx8IHsgUkVHX01JU1M9JGU7IHJldHVybiAxOyB9CiAgZG9uZQogIHJldHVybiAwCn0KIyBSZWdlbmVyYXRlIGEgY2xlYW4gU1RPQ0sgcmVnaXN0cnkgZnJvbSB0aGUgcHJpc3RpbmUgb24tZGlzayBwbHVnaW5zIGFuZCB3cml0ZQojIGl0IG92ZXIgdGhlIG1lZGlhIHJlZ2lzdHJ5LiBUaGUgcmVnaXN0cnkgaXMgY29tbWl0dGVkIHdpdGggYGNwIC1mYCAoYQojIFBFUlNJU1RFTlQgb3ZlcndyaXRlKSwgbm90IGEgYmluZC1tb3VudCwgc28gbm8gdW1vdW50IGNhbiByZXZlcnQgaXQ7IGxlZnQKIyBhbG9uZSBpdCBrZWVwcyByZWZlcmVuY2luZyByZW1vdmVkIC92YXIvbGliL3dlYm9zYnJldyBwbHVnaW5zIGFuZCBicmVha3MKIyBtZWRpYS1waXBlbGluZSBhcHAgYXVkaW8gKHJvb3QtY2F1c2VkIG9uIGEgcmVhbCBDNSwgMjAyNi0wNy0yMykuIENhbGwgb25seQojIEFGVEVSIHRoZSBiaW5kcyBhcmUgZHJvcHBlZC4gU2FtZSByb3V0aW5lIGFzIHVuaW5zdGFsbC5zaCBzdGVwIDJiLgojCiMgUkVUVVJOUyAwIE9OTFkgSUYgTEcnUyBSRUdJU1RSWSBJUyBBQ1RVQUxMWSBCQUNLIElOIFBMQUNFLiBUaGlzIGlzIGEgY29sZC1jYWNoZQojIGZ1bGwgcGx1Z2luIHNjYW4gdW5kZXIgYHRpbWVvdXRgLCBhbmQgYXQgYm9vdCBpdCBydW5zIGF0IHRoZSBidXNpZXN0IG1vbWVudCBvbgojIHRoZSBib3gsIHNvIGl0IGdlbnVpbmVseSBjYW4gZmFpbCAtLSBjYWxsZXJzIHRoYXQgZ28gb24gdG8gREVMRVRFIG91ciBwbHVnaW5zCiMgbXVzdCBicmFuY2ggb24gdGhpcywgbmV2ZXIgYXNzdW1lIGl0IHdvcmtlZC4gVGhlIHNjYW4ncyBvd24gZXhpdCBzdGF0dXMgaXMgbm90CiMgc3VmZmljaWVudCBldmlkZW5jZSBlaXRoZXI6IGEgdHJ1bmNhdGVkIHJlZ2lzdHJ5IHdvdWxkIGJlIHdvcnNlIHRoYW4gbm9uZSwgc28KIyB0aGUgZmlsZSBoYXMgdG8gYmUgbm9uLWVtcHR5IGJlZm9yZSBpdCBpcyBjb21taXR0ZWQuCiMgQXJlIGFueSBvZiB0aGUgcGx1Z2luIGJpbmRzIHdlIG1hbmFnZSBzdGlsbCBtb3VudGVkPyB3MjVfc3RvY2tfcmVnaXN0cnkgaGFzIHRvCiMgcmVmdXNlIHdoaWxlIG9uZSBpcy4gVGhlIHNjYW4gd291bGQgdGhlbiBsb2FkIE9VUiBsaWJnc3RsaWJhdi5zbyBmcm9tIHRoZSBzdG9jawojIHBhdGggKGl0cyBSVU5QQVRIIHJlc29sdmVzIGZpbmUpLCBwcm9kdWNlIGEgc3ludGFjdGljYWxseSB2YWxpZCByZWdpc3RyeSB0aGF0CiMgaGFwcGVucyB0byBuYW1lIG5vIC92YXIvbGliL3dlYm9zYnJldyBwYXRoIGF0IGFsbCAtLSB3aGljaCBDTEVBUlMKIyB3MjVfcmVnX2lzX291cnMsIHRoZSB2ZXJ5IHNpZ25hbCBjYWxsZXJzIHVzZSB0byBkZWNpZGUgYSByZXBhaXIgaXMgbmVlZGVkIC0tIGFuZAojIHJlcG9ydCBzdWNjZXNzLiBBIGNhbGxlciB3b3VsZCB0YWtlIHRoYXQgYXMgcHJvb2YgdGhlIFRWIGlzIGJhY2sgb24gc3RvY2sgYW5kCiMgZGVsZXRlIHRoZSBwYXlsb2FkIG91dCBmcm9tIHVuZGVyIHRoZSBzdXJ2aXZpbmcgYmluZC4gUmVmdXNpbmcgaGVyZSBtYWtlcyB0aGlzCiMgZnVuY3Rpb24ncyBwb3N0Y29uZGl0aW9uICgiJFJFRyBpcyBhIHN0b2NrIHJlZ2lzdHJ5IikgdHJ1ZSBieSBjb25zdHJ1Y3Rpb24sIGFuZAojIGV2ZXJ5IGNhbGxlciBhbHJlYWR5IGhhbmRsZXMgYSByZXR1cm4gb2YgMSBieSBkZWZlcnJpbmcgaW5zdGVhZCBvZiBkZWxldGluZy4KdzI1X3BsdWdpbl9iaW5kc19wcmVzZW50KCkgewogIGdyZXAgLXEgIiAkTEdMSUJBViAiIC9wcm9jL21vdW50cyAyPi9kZXYvbnVsbCAmJiByZXR1cm4gMAogIGdyZXAgLXEgIiAkTEdJU08gIiAvcHJvYy9tb3VudHMgMj4vZGV2L251bGwgJiYgcmV0dXJuIDAKICBncmVwIC1xICIgJExHVFNEICIgL3Byb2MvbW91bnRzIDI+L2Rldi9udWxsICYmIHJldHVybiAwCiAgcmV0dXJuIDEKfQp3MjVfc3RvY2tfcmVnaXN0cnkoKSB7CiAgaWYgdzI1X3BsdWdpbl9iaW5kc19wcmVzZW50OyB0aGVuCiAgICB3MjVfbG9nICJXQVJOIHJlZnVzaW5nIHRvIHJlYnVpbGQgdGhlIHN0b2NrIHJlZ2lzdHJ5OiBhIHBsdWdpbiBiaW5kIG9mIG91cnMgaXMgc3RpbGwgbW91bnRlZCwgc28gdGhlIHNjYW4gd291bGQgbm90IGJlIHJlYWRpbmcgc3RvY2sgcGx1Z2lucyIKICAgIHJldHVybiAxCiAgZmkKICBDTEVBTl9SRUc9L3RtcC9nc3RfY2xlYW5fcmVnLmJpbgogIHJtIC1mICIkQ0xFQU5fUkVHIiAyPi9kZXYvbnVsbAogIGlmIEdTVF9SRUdJU1RSWV8xXzA9IiRDTEVBTl9SRUciIEdTVF9QTFVHSU5fUEFUSF8xXzA9L3Vzci9saWIvZ3N0cmVhbWVyLTEuMDovbW50L2xnL3Jlcy9sZ2xpYi9nc3RyZWFtZXItMS4wIEdTVF9SRUdJU1RSWV9GT1JLPW5vIEdTVF9SRUdJU1RSWV9VUERBVEU9eWVzIHRpbWVvdXQgNjAgL3Vzci9iaW4vZ3N0LWluc3BlY3QtMS4wID4vZGV2L251bGwgMj4mMSAmJiBbIC1zICIkQ0xFQU5fUkVHIiBdOyB0aGVuCiAgICBpZiBjcCAtZiAiJENMRUFOX1JFRyIgIiRSRUciIDI+L2Rldi9udWxsOyB0aGVuCiAgICAgIHcyNV9sb2cgInJlZ2VuZXJhdGVkIGNsZWFuIHN0b2NrIHJlZ2lzdHJ5IG92ZXIgJFJFRyIKICAgICAgcm0gLWYgIiRDTEVBTl9SRUciIDI+L2Rldi9udWxsCiAgICAgIHJldHVybiAwCiAgICBmaQogICAgdzI1X2xvZyAiV0FSTiBjb3VsZCBub3Qgd3JpdGUgdGhlIGNsZWFuIHN0b2NrIHJlZ2lzdHJ5IHRvICRSRUciCiAgZWxzZQogICAgdzI1X2xvZyAiV0FSTiBjbGVhbiBzdG9jayByZWdpc3RyeSByZWdlbiBmYWlsZWQgKHNjYW4gdGltZWQgb3V0LCBlcnJvcmVkLCBvciBwcm9kdWNlZCBub3RoaW5nKTsgbGVhdmluZyAkUkVHIHVudG91Y2hlZCIKICBmaQogIHJtIC1mICIkQ0xFQU5fUkVHIiAyPi9kZXYvbnVsbAogIHJldHVybiAxCn0KIyBSZWNvcmQgdGhlIFBSSVNUSU5FIHN0b2NrIGZpbmdlcnByaW50cyArIFRWIGlkZW50aXR5LiAkMT12ZXJpZmllZCwgJDI9Zm9yY2VkLgojIFdyaXR0ZW4gb25seSB3aGVuIHRoZSBnYXRlIGFsbG93cyBhcHBseWluZywgYW5kIG9ubHkgZnJvbSBoYXNoZXMgdGFrZW4gd2hpbGUKIyBubyBiaW5kIG9mIG91cnMgc2hhZG93ZWQgdGhlIHBsdWdpbnMgLS0gdGhhdCBpcyB3aGF0IGxhdGVyIGxldHMgYSBib290IHRlbGwKIyAidGhlIGZpcm13YXJlIGNoYW5nZWQiIGFwYXJ0IGZyb20gIndlIGFyZSBzaW1wbHkgZW5hYmxlZCIuCncyNV9mcF93cml0ZSgpIHsKICBta2RpciAtcCAvdmFyL2xpYi93ZWJvc2JyZXcvZHRzMjUgMj4vZGV2L251bGwKICB7IGVjaG8gImdzdF9tbT0kR1NUX01NX05PVyIKICAgIGVjaG8gInByb2R1Y3RfaWQ9JCh3MjVfcHJvZHVjdF9pZCkiCiAgICBlY2hvICJ3ZWJvc19yZWxlYXNlPSQodzI1X3dlYm9zX3JlbGVhc2UpIgogICAgZWNobyAibGliZ3N0bGliYXY9JE1fTElCQVYiCiAgICBlY2hvICJsaWJnc3Rpc29tcDQ9JE1fSVNPTVA0IgogICAgZWNobyAibGliZ3N0bXBlZ3RzZGVtdXg9JE1fTVBFR1RTIgogICAgZWNobyAiZGV2aWNlX2NvZGVjX2NhcGFiaWxpdHlfY29uZmlnPSRNX0NGRyIKICAgIGVjaG8gImdzdGNvb2w9JE1fR0MiCiAgICBlY2hvICJ2ZXJpZmllZD0kMSIKICAgIGVjaG8gImZvcmNlZD0kMiIKICAgIGVjaG8gIndyaXR0ZW49JChkYXRlIC11ICslWS0lbS0lZFQlSDolTTolU1opIgogIH0gPiAiJEZQLnRtcCIgMj4vZGV2L251bGwgJiYgbXYgLWYgIiRGUC50bXAiICIkRlAiIDI+L2Rldi9udWxsIFwKICAgICYmIHcyNV9sb2cgIndyb3RlICRGUCAodmVyaWZpZWQ9JDEgZm9yY2VkPSQyKSIgfHwgdzI1X2xvZyAiV0FSTiBjb3VsZCBub3Qgd3JpdGUgJEZQIgogIHJldHVybiAwCn0KIyA8PDwgVzI1LUNPTVBBVC1FTkQKIyBXMjVfQ0hFQ0s9MTogcmVhZC1vbmx5IHByZWZsaWdodCB1c2VkIGJ5IGluc3RhbGwuc2ggYW5kIHRoZSBhcHAncyBFbmFibGUgdG8KIyByZWZ1c2Ugd2l0aCBhIHJlYWRhYmxlIHJlYXNvbiBCRUZPUkUgdGhleSBsaW5rIHRoZSBib290IGhvb2suIFByaW50cyBvbmx5LgppZiBbICIke1cyNV9DSEVDSzotMH0iID0gMSBdOyB0aGVuCiAgdzI1X21lYXN1cmUKICB3MjVfZ2F0ZQogIGVjaG8gIkdTVF9NTT0kR1NUX01NX05PVyIKICBlY2hvICJWRVJESUNUPSRWRVJESUNUIgogIGVjaG8gIlJFQVNPTj0kUkVBU09OIgogIGVjaG8gIkxBQkVMPSRMQUJFTCIKICBlY2hvICJDQU5GT1JDRT0kQ0FORk9SQ0UiCiAgaWYgdzI1X2xvYWRlcl9vazsgdGhlbiBlY2hvICJMT0FERVI9b2siOyBlbHNlIGVjaG8gIkxPQURFUj0kTE9BREVSX01JU1MiOyBmaQogIGVjaG8gIkxPQURFUl9TVEFHRUQ9JHtMT0FERVJfU1RBR0VEOi0xfSIKICAjIFRoZSBzaXggdmFsdWVzIGEgbWFpbnRhaW5lciBuZWVkcyB0byBhZGQgdGhpcyBUViB0byB0aGUgdmVyaWZpZWQtc2V0cyB0YWJsZS4KICAjIEVtcHR5IG1kNXMgbWVhbiB0aGUgcGx1Z2luIGlzIGN1cnJlbnRseSBzaGFkb3dlZCBieSBvbmUgb2Ygb3VyIGJpbmRzLCBzbyB0aGUKICAjIFNUT0NLIGhhc2ggaXMgdW5tZWFzdXJhYmxlIHJpZ2h0IG5vdyAtLSBydW4gdGhpcyB3aXRoIHRoZSBvdmVycmlkZXMgZHJvcHBlZC4KICBlY2hvICJQUk9EVUNUX0lEPSQodzI1X3Byb2R1Y3RfaWQpIgogIGVjaG8gIldFQk9TX1JFTEVBU0U9JCh3MjVfd2Vib3NfcmVsZWFzZSkiCiAgZWNobyAiTUQ1X0xJQkdTVExJQkFWPSRTX0xJQkFWIgogIGVjaG8gIk1ENV9MSUJHU1RJU09NUDQ9JFNfSVNPTVA0IgogIGVjaG8gIk1ENV9MSUJHU1RNUEVHVFNERU1VWD0kU19NUEVHVFMiCiAgZWNobyAiTUQ1X0RFVklDRV9DT0RFQ19DQVBBQklMSVRZX0NPTkZJRz0kU19DRkciCiAgZWNobyAiTUQ1X0dTVENPT0w9JFNfR0MiCiAgIyBXaGljaCBnYXRlIHRoaXMgc2NyaXB0IGVuZm9yY2VzLCBhbmQgaXRzIG93biBmaW5nZXJwcmludC4gIiQwIiBpcyB0aGUKICAjIGluc3RhbGxlZCBwYXRoLCBzbyBhIGNhbGxlciBjYW4gdGVsbCB3aGV0aGVyIHRoZSBzY3JpcHQgaXQganVzdCB3cm90ZSBpcyB0aGUKICAjIG9uZSB0aGF0IHJhbi4KICBTRUxGX01ENT0kKHcyNV9tZDUgIiQwIikKICBlY2hvICJHQVRFX1ZFUlNJT049JFcyNV9HQVRFX1ZFUlNJT04iCiAgZWNobyAiU0NSSVBUX01ENT0kU0VMRl9NRDUiCiAgZXhpdCAwCmZpCiMgVzI1X1NUQU5EX0RPV049MTogcmV2ZXJ0IHRvIHN0b2NrIGFuZCBleGl0LiBEZWxpYmVyYXRlbHkgYSBtb2RlIG9mIGl0cyBvd24KIyByYXRoZXIgdGhhbiAianVzdCBydW4gdGhlIHNjcmlwdCBhbmQgbGV0IGl0IHJlZnVzZSI6IGEgbW9kZSBjYW5ub3QgYWNjaWRlbnRhbGx5CiMgQVBQTFkgaWYgdGhlIGdhdGUncyBpbnB1dHMgY2hhbmdlZCBiZXR3ZWVuIHRoZSBjYWxsZXIncyBwcmVmbGlnaHQgYW5kIHRoaXMgY2FsbC4KaWYgWyAiJHtXMjVfU1RBTkRfRE9XTjotMH0iID0gMSBdOyB0aGVuCiAgaWYgdzI1X3JlZ19pc19vdXJzOyB0aGVuIFdBU19PVVJTPTE7IGVsc2UgV0FTX09VUlM9MDsgZmkKICB3MjVfc3RhbmRfZG93bgogIHcyNV9sb2cgInN0YW5kLWRvd24gcmVxdWVzdGVkIGJ5IHRoZSBpbnN0YWxsZXIgKGEgcmVnaXN0cnkgb2Ygb3VycyB3YXMgbGl2ZTogJFdBU19PVVJTKSIKICBlY2hvICJTVE9PRF9ET1dOPSRXQVNfT1VSUyIKICBleGl0IDAKZmkKIyAtLS0gRykgc2VsZi1oZWFsIC8gc2VsZi11bmxpbmssIGV2YWx1YXRlZCBGSVJTVCAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQojIFRXTyBESUZGRVJFTlQgRkFVTFRTLCBUV08gRElGRkVSRU5UIEFOU1dFUlMuIERlbGV0aW5nIGlzIG9ubHkgZXZlciByaWdodCB3aGVuCiMgbm9ib2R5IG93bnMgdGhpcyBpbnN0YWxsIGFueSBtb3JlOyBhIG1lcmVseSBpbmNvbXBsZXRlIGluc3RhbGwgaXMgcmVjb3ZlcmFibGUsCiMgYW5kIGRlc3Ryb3lpbmcgaXQgd291bGQgYmUgd29yc2UgdGhhbiB0aGUgaGF6YXJkIHRoZSBndWFyZCBleGlzdHMgZm9yLgojCiMgICBVTk9XTkVEICB0aGUgYXBwIGRpciBpcyBnb25lIGZyb20gQk9USCBpbnN0YWxsIHRyZWVzIEFORCB0aGVyZSBpcyBubyBDTEkKIyAgICAgICAgICAgIG1hcmtlciAtPiBub2JvZHkgY2FuIG1hbmFnZSB0aGVzZSBzeXN0ZW0td2lkZSBvdmVycmlkZXMgYW55IG1vcmUuCiMgICAgICAgICAgICBGdWxsIGhlYWw6IGRyb3AgdGhlIGJpbmRzLCBwdXQgYSBjbGVhbiBzdG9jayByZWdpc3RyeSBiYWNrLCByZW1vdmUKIyAgICAgICAgICAgIG91ciBzdGF0ZSwgdW5saW5rIG91cnNlbHZlcy4KIyAgIElOQ09NUExFVEUgKGhhbmRsZWQgaW4gdGhlIG5leHQgYmxvY2ssIG5vdCBoZXJlKSB0aGUgaW5zdGFsbCBpcyBzdGlsbCBvd25lZAojICAgICAgICAgICAgYnV0IGEgQ09SRSBvYmplY3QgaXMgbWlzc2luZyAtPiBiaW5kIG5vdGhpbmcsIGRlbGV0ZSBub3RoaW5nLCBrZWVwCiMgICAgICAgICAgICB0aGUgaG9vaywgYW5kIHJlcGFpciB0aGUgcmVnaXN0cnkgaWYgYSBzdGFsZSBvbmUgb2Ygb3VycyBpcyBsaXZlLgojCiMgVGhlIGhvb2sgc3RheXMgYSBzeW1saW5rIHRvIFRISVMgZmlsZSB1bmRlciAvdmFyL2xpYi93ZWJvc2JyZXcvZHRzMjUgcmF0aGVyCiMgdGhhbiBpbnRvIHRoZSBhcHAgZGlyOiBhIHN5bWxpbmsgaW50byBhIHJlbW92ZWQgYXBwIGRpciBpcyBkYW5nbGluZyBhbmQKIyBleGVjdXRlcyBub3RoaW5nLCBzbyBpdCBjb3VsZCBuZXZlciBoZWFsIGFueXRoaW5nLgpBUFBESVJfREVWPS9tZWRpYS9kZXZlbG9wZXIvYXBwcy91c3IvcGFsbS9hcHBsaWNhdGlvbnMvaW8uZ2l0aHViLmpvc2lwcGFwZXouZHRzZW5hYmxlcgpBUFBESVJfU1lTPS91c3IvcGFsbS9hcHBsaWNhdGlvbnMvaW8uZ2l0aHViLmpvc2lwcGFwZXouZHRzZW5hYmxlcgpDTElfTUFSS0VSPS92YXIvbGliL3dlYm9zYnJldy9kdHMyNS8uY2xpLWluc3RhbGwKdzI1X3Vub3duZWQoKSB7CiAgSEVBTF9XSFk9CiAgaWYgWyAhIC1kICIkQVBQRElSX0RFViIgXSAmJiBbICEgLWQgIiRBUFBESVJfU1lTIiBdICYmIFsgISAtZiAiJENMSV9NQVJLRVIiIF07IHRoZW4KICAgIEhFQUxfV0hZPSJ0aGUgRFRTIEVuYWJsZXIgYXBwIGlzIGdvbmUgYW5kIHRoaXMgd2FzIG5vdCBhIENMSSBpbnN0YWxsIgogICAgcmV0dXJuIDAKICBmaQogIHJldHVybiAxCn0KIyBPUkRFUiBJUyBUSEUgV0hPTEUgUE9JTlQgSEVSRTogcmVnZW5lcmF0ZSBMRydzIHJlZ2lzdHJ5IEZJUlNUIGFuZCBkZWxldGUgb3VyCiMgcGx1Z2lucyBvbmx5IG9uY2UgdGhhdCBoYXMgYWN0dWFsbHkgc3VjY2VlZGVkLgojCiMgRGVsZXRpbmcgZmlyc3Qgd291bGQgbWVhbiB0aGF0IGEgcmVnZW4gd2hpY2ggdGltZXMgb3V0IC0tIGEgY29sZC1jYWNoZSBmdWxsCiMgcGx1Z2luIHNjYW4sIGF0IGJvb3QsIG9uIHRoZSBidXNpZXN0IG1vbWVudCB0aGUgYm94IGhhcyAtLSBsZWF2ZXMgdGhlIGxpdmUKIyByZWdpc3RyeSBuYW1pbmcgcGx1Z2lucyB0aGF0IG5vIGxvbmdlciBleGlzdCBBTkQgcmVtb3ZlcyB0aGUgaG9vayB0aGF0IGNvdWxkCiMgcmV0cnkuIFRoYXQgaXMgdGhlIHN0YWxlLXJlZ2lzdHJ5IHN0YXRlIHRoYXQgYnJva2Ugb3RoZXIgYXBwcycgYXVkaW8gb24gYSByZWFsCiMgQzUgKDIwMjYtMDctMjMpLCBhbmQgTEcncyBzdGFjayBkb2VzIG5vdCByZWNvdmVyIGZyb20gaXQgYnkgaXRzZWxmLgojCiMgU28gb24gZmFpbHVyZToga2VlcCB0aGUgYmluZHMgZHJvcHBlZCwga2VlcCB0aGUgc3RhdGUgZGlycywga2VlcCB0aGUgaG9vaywgYW5kCiMgbGV0IHRoZSBuZXh0IGJvb3QgdHJ5IGFnYWluLiBBIGhlYWwgdGhhdCByZXRyaWVzIGZvcmV2ZXIgaXMgc3RyaWN0bHkgYmV0dGVyCiMgdGhhbiBvbmUgdGhhdCBicmVha3MgYXVkaW8gb25jZS4gVW5jb25kaXRpb25hbCByZWdlbiAobm90IHcyNV9zdGFuZF9kb3duJ3MKIyBjb25kaXRpb25hbCBvbmUpIGJlY2F1c2UgdGhpcyBwYXRoIHJlbW92ZXMgb3VyIHBsdWdpbnMgb3V0cmlnaHQsIHNvIGFueQojIHJlZ2lzdHJ5IG5hbWluZyB0aGVtIG11c3QgYmUgcmVwbGFjZWQgd2hldGhlciBvciBub3QgaXQgbG9va3MgbGlrZSBvdXJzLgp3MjVfc2VsZl9oZWFsKCkgewogIHcyNV9sb2cgIlNFTEYtSEVBTDogJEhFQUxfV0hZIC0tIHJldmVydGluZyBldmVyeSBvdmVycmlkZSIKICB3MjVfZHJvcF9iaW5kcwogIGlmICEgdzI1X3N0b2NrX3JlZ2lzdHJ5OyB0aGVuCiAgICB3MjVfbG9nICJTRUxGLUhFQUwgREVGRVJSRUQ6IExHJ3MgcmVnaXN0cnkgY291bGQgbm90IGJlIHJlYnVpbHQsIHNvIG91ciBwbHVnaW5zIGFuZCB0aGUgYm9vdCBob29rIGFyZSBLRVBUIChkZWxldGluZyB0aGVtIG5vdyB3b3VsZCBsZWF2ZSB0aGUgbGl2ZSByZWdpc3RyeSBwb2ludGluZyBhdCBtaXNzaW5nIHBsdWdpbnMpLiBSZXRyeWluZyBhdCB0aGUgbmV4dCBib290LiIKICAgIHRvYXN0ICJEVFMgRW5hYmxlciBjbGVhbnVwIGRlZmVycmVkOiB0aGUgVFYgd2FzIHRvbyBidXN5IHRvIHJlYnVpbGQgaXRzIHBsdWdpbiBsaXN0LiBJdCB3aWxsIGZpbmlzaCBhdCB0aGUgbmV4dCByZXN0YXJ0LiIKICAgIHJldHVybiAxCiAgZmkKICBmb3IgZCBpbiAvdmFyL2xpYi93ZWJvc2JyZXcvZHRzMjUgL3Zhci9saWIvd2Vib3NicmV3L3RydWVoZCAvdmFyL2xpYi93ZWJvc2JyZXcvZGVtdXgyNTsgZG8KICAgIFsgLWQgIiRkIiBdICYmIHJtIC1yZiAiJGQiCiAgZG9uZQogIHJtIC1mICIkSE9PSyIKICB0b2FzdCAiRFRTIEVuYWJsZXIgaXMgZ29uZTogRFRTL1RydWVIRCBvdmVycmlkZXMgcmV2ZXJ0ZWQgYW5kIHRoZSBib290IGhvb2sgcmVtb3ZlZC4iCiAgcmV0dXJuIDAKfQojIE9uZSBjb21wb3VuZCBjb21tYW5kIG9uIHB1cnBvc2U6IHRoZSBzaGVsbCBoYXMgZmluaXNoZWQgcGFyc2luZyB0aGUgd2hvbGUKIyBgaWZgIChhbmQgYm90aCBmdW5jdGlvbiBib2RpZXMpIGJlZm9yZSB3MjVfc2VsZl9oZWFsIGRlbGV0ZXMgdGhlIGRpcmVjdG9yeQojIHRoaXMgdmVyeSBzY3JpcHQgaXMgcnVubmluZyBmcm9tLCBzbyB0aGVyZSBpcyBub3RoaW5nIGxlZnQgdG8gcmVhZCBhZnRlcndhcmRzLgppZiB3MjVfdW5vd25lZDsgdGhlbgogIGlmIHcyNV9zZWxmX2hlYWw7IHRoZW4gZWNobyAiSEVBTEVEPSRIRUFMX1dIWSI7IGVsc2UgZWNobyAiSEVBTF9ERUZFUlJFRD0kSEVBTF9XSFkiOyBmaQogIGV4aXQgMApmaQojIC0tLSBHMikgb3duZWQsIGJ1dCB0aGUgQ09SRSBwYXlsb2FkIGlzIGluY29tcGxldGUgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiMgUmVjb3ZlcmFibGUsIHNvIG5vdGhpbmcgaXMgZGVsZXRlZCBhbmQgdGhlIGhvb2sgc3RheXM6IHJlLW9wZW5pbmcgdGhlIGFwcCBvcgojIHJlLXJ1bm5pbmcgaW5zdGFsbC5zaCByZXN0YWdlcyB0aGUgcGF5bG9hZCBhbmQgdGhlIG5leHQgYm9vdCBhcHBsaWVzIG5vcm1hbGx5LgojIFdoYXQgRE9FUyBuZWVkIHJlcGFpcmluZyBpcyB0aGUgbWVkaWEgcmVnaXN0cnkgLS0gaXQgaXMgY29tbWl0dGVkIHdpdGggYGNwIC1mYCwKIyBzbyBhIHJlZ2lzdHJ5IHdlIHdyb3RlIGVhcmxpZXIgc3Vydml2ZXMgaW5kZXBlbmRlbnRseSBvZiBvdXIgZmlsZXMsIGFuZCBpZiBpdAojIGlzIHN0aWxsIGxpdmUgd2hpbGUgb3VyIGxpYnJhcmllcyBhcmUgZ29uZSBpdCBuYW1lcyBwbHVnaW5zIHRoYXQgbm8gbG9uZ2VyCiMgZXhpc3QgKHRoYXQgaXMgdGhlIGZhaWx1cmUgdGhhdCBicm9rZSBtZWRpYS1waXBlbGluZSBhcHAgYXVkaW8gb24gYSByZWFsIEM1LAojIDIwMjYtMDctMjMpLiBPbmx5IHRoZSBkZW11eGVycyBhcmUgb3B0aW9uYWw7IG1pc3NpbmcgdGhvc2UgaXMgYSBub3JtYWwKIyBNS1Ytb25seSBpbnN0YWxsLCBub3QgYSBmYXVsdC4KaWYgISB3MjVfY29yZV9zdGFnZWQ7IHRoZW4KICB3MjVfbG9nICJSRUZVU0VEOiBjb3JlIHBheWxvYWQgaW5jb21wbGV0ZSAoZHRzZGVjIHByZXNlbnQ9JChbIC1mICIkTVlEVFMiIF0gJiYgZWNobyAxIHx8IGVjaG8gMCksIGxpYmF2IHByZXNlbnQ9JChbIC1mICIkTVlMSUJBViIgXSAmJiBlY2hvIDEgfHwgZWNobyAwKSk7IGJpbmRpbmcgbm90aGluZywgaW5zdGFsbCBsZWZ0IGludGFjdCIKICB3MjVfc3RhbmRfZG93bgogIHRvYXN0ICJEVFMgRW5hYmxlcjogdGhlIGluc3RhbGxlZCBmaWxlcyBhcmUgaW5jb21wbGV0ZSwgc28gbm90aGluZyB3YXMgYXBwbGllZC4gUmUtb3BlbiBEVFMgRW5hYmxlciAob3IgcmUtcnVuIGluc3RhbGwuc2gpIHRvIHJlcGFpci4iCiAgZWNobyAiUkVGVVNFRD1wYXlsb2FkIgogIGVjaG8gIlJFQVNPTj10aGUgc3RhZ2VkIERUUy9UcnVlSEQgY29yZSBwYXlsb2FkIGlzIGluY29tcGxldGU7IG5vdGhpbmcgd2FzIGJvdW5kIGFuZCBub3RoaW5nIHdhcyByZW1vdmVkIgogIGV4aXQgMApmaQojIC0tLSBtZWFzdXJlIHRoZSBwcmlzdGluZSBzdG9jayBmaW5nZXJwcmludHMgKHJlYWQtb25seSkgLS0tLS0tLS0tLS0tLS0tLS0tLS0KdzI1X21lYXN1cmUKIyAtLS0gR0FURSAwKSBmaXJtd2FyZS11cGRhdGUgLyBBQkkgZ3VhcmQgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCmlmICEgdzI1X2dzdF9vazsgdGhlbgogIHcyNV9sb2cgIkFCT1JUOiBHU3RyZWFtZXIgJyRHU1RfTU1fTk9XJyAhPSBleHBlY3RlZCAkRVhQRUNUX0dTVCAoZmlybXdhcmUgdXBkYXRlPyk7IHN0YW5kaW5nIGRvd24iCiAgIyBUaGUgbGlrZWxpZXN0IHJlZnVzYWwgaW4gdGhlIHdpbGQsIGFuZCB0aGUgb25lIHdoZXJlIGxlYXZpbmcgYSByZWdpc3RyeSBvZgogICMgb3VycyBsaXZlIHdvdWxkIGJlIHdvcnN0OiBvdXIgcGx1Z2lucyBtYXkgbm90IGV2ZW4gZXhpc3QgYW55IG1vcmUgYWZ0ZXIgYQogICMgbWFqb3IgZmlybXdhcmUgY2hhbmdlLiB3MjVfc3RhbmRfZG93biBoYW5kbGVzIHRoYXQgLS0gaXQgcmVidWlsZHMgZnJvbSBMRydzCiAgIyBwbHVnaW4gZGlyZWN0b3JpZXMgb25seS4KICB3MjVfc3RhbmRfZG93bgogIHRvYXN0ICJEVFMvVHJ1ZUhEIHBhdXNlZDogVFYgZmlybXdhcmUgY2hhbmdlZCAoR1N0cmVhbWVyICRHU1RfTU1fTk9XKS4gUmUtb3BlbiBEVFMgRW5hYmxlciB0byB1cGRhdGUuIgogIGVjaG8gIlJFRlVTRUQ9ZHJpZnQiCiAgZWNobyAiUkVBU09OPUdTdHJlYW1lciAkR1NUX01NX05PVyBpcyBub3QgdGhlICRFWFBFQ1RfR1NUIHRoaXMgcGF5bG9hZCB3YXMgYnVpbHQgZm9yOyBhIGZpcm13YXJlIHVwZGF0ZSBjaGFuZ2VkIHRoZSBwbHVnaW4gQUJJIgogIGV4aXQgMApmaQojIC0tLSBHQVRFIDEpIGlkZW50aXR5IC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KdzI1X3ZlcmRpY3QKY2FzZSAiJFZFUkRJQ1QiIGluCiAgdmVyaWZpZWR8Zm9yY2VkKSB3MjVfbG9nICJnYXRlOiAkVkVSRElDVCAtLSAkUkVBU09OJHtMQUJFTDorIFskTEFCRUxdfSIgOzsKICBkcmlmdCkKICAgIHcyNV9sb2cgIlJFRlVTRUQ6IGRyaWZ0IC0tICRSRUFTT04iCiAgICB3MjVfc3RhbmRfZG93bgogICAgdG9hc3QgIkRUUy9UcnVlSEQgc3RvcHBlZDogdGhpcyBUViBjaGFuZ2VkIHNpbmNlIGl0IHdhcyBsYXN0IHZlcmlmaWVkLCBzbyBub3RoaW5nIHdhcyBhcHBsaWVkLiBVbmluc3RhbGwgdGhlbiBFbmFibGUgaW4gRFRTIEVuYWJsZXIgdG8gb3B0IGluIGFnYWluLiIKICAgIGVjaG8gIlJFRlVTRUQ9ZHJpZnQiCiAgICBlY2hvICJSRUFTT049JFJFQVNPTiIKICAgIGV4aXQgMCA7OwogICopCiAgICB3MjVfbG9nICJSRUZVU0VEOiAkVkVSRElDVCAtLSAkUkVBU09OIgogICAgdzI1X3N0YW5kX2Rvd24KICAgIHRvYXN0ICJEVFMgRW5hYmxlcjogdGhpcyBUViBpcyBub3Qgb24gdGhlIHZlcmlmaWVkIGxpc3QsIHNvIG5vdGhpbmcgd2FzIGNoYW5nZWQuIE9wZW4gRFRTIEVuYWJsZXIgdG8gdHJ5IGFueXdheS4iCiAgICBlY2hvICJSRUZVU0VEPSRWRVJESUNUIgogICAgZWNobyAiUkVBU09OPSRSRUFTT04iCiAgICBleGl0IDAgOzsKZXNhYwojIC0tLSBHQVRFIDJhKSBsb2FkZXIgcmVzb2x1dGlvbiAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KaWYgISB3MjVfbG9hZGVyX29rOyB0aGVuCiAgdzI1X2xvZyAiUkVGVVNFRDogbG9hZGVyIC0tICRMT0FERVJfTUlTUyIKICB3MjVfc3RhbmRfZG93bgogIHRvYXN0ICJEVFMgRW5hYmxlcjogdGhlIHBheWxvYWQgY2Fubm90IGxvYWQgb24gdGhpcyBUViAoJExPQURFUl9NSVNTKTsgbm90aGluZyB3YXMgY2hhbmdlZC4iCiAgZWNobyAiUkVGVVNFRD1sb2FkZXIiCiAgZWNobyAiUkVBU09OPSRMT0FERVJfTUlTUyIKICBleGl0IDAKZmkKIyAtLS0gcmVjb3JkIHRoZSBwcmlzdGluZSBmaW5nZXJwcmludHMgYmVmb3JlIGFueXRoaW5nIG9mIG91cnMgaXMgYm91bmQgLS0tLS0tCmNhc2UgIiRWRVJESUNUIiBpbgogIHZlcmlmaWVkKSBGUF9GT1JDRUQ9JCh3MjVfZnBfZ2V0IGZvcmNlZCk7IFsgLW4gIiRGUF9GT1JDRUQiIF0gfHwgRlBfRk9SQ0VEPTA7IHcyNV9mcF93cml0ZSAxICIkRlBfRk9SQ0VEIiA7OwogICopICAgICAgICB3MjVfZnBfd3JpdGUgMCAxIDs7CmVzYWMKIyAtLS0gQVBQTFkgMSkgY29kZWMtY2FwYWJpbGl0eSBvdmVycmlkZSAoYWRkcyBUUlVFSEQvTUxQIHNvIHVtZWRpYXNlcnZlciBhbGxvY2F0ZXMgYSBkZWNvZGVyIHJlc291cmNlKQpbIC1mICIkTVlDRkciIF0gJiYgISBncmVwIC1xICIgJENGRyAiIC9wcm9jL21vdW50cyAyPi9kZXYvbnVsbCAmJiBtb3VudCAtbiAtLWJpbmQgIiRNWUNGRyIgIiRDRkciIDI+PiRMT0cKIyAtLS0gQVBQTFkgMikgcmVwbGFjZSBMRy5zIHRydWVoZC1sZXNzIGxpYmF2IHdpdGggb3VycyAoaGFzIGF2ZGVjX3RydWVoZC9hdmRlY19tbHApClsgLWYgIiRNWUxJQkFWIiBdICYmICEgZ3JlcCAtcSAiICRMR0xJQkFWICIgL3Byb2MvbW91bnRzIDI+L2Rldi9udWxsICYmIG1vdW50IC1uIC0tYmluZCAtbyBybyAiJE1ZTElCQVYiICIkTEdMSUJBViIgMj4+JExPRwojIC0tLSBBUFBMWSAyYikgZ3N0Y29vbC5jb25mOiBnaXZlIGF2ZGVjX3RydWVoZCBhIGhpZ2ggU1cgcmFuayBzbyBMRyBhdXRvcGx1Z3MgaXQgKG5vdCB0aGUgSFcgcGF0aCkKWyAtZiAiJE1ZR0MiIF0gJiYgISBncmVwIC1xICIgJEdDICIgL3Byb2MvbW91bnRzIDI+L2Rldi9udWxsICYmIG1vdW50IC1uIC0tYmluZCAiJE1ZR0MiICIkR0MiIDI+PiRMT0cKIyAtLS0gQVBQTFkgMmMpIGNvbnRhaW5lciBkZW11eGVycyB3aXRoIERUUyByZS1lbmFibGVkIChtcDQvdHMvbTJ0cyBEVFMgLT4gYXVkaW8veC1kdHMpLgojICAgICAgICAgUGF0Y2hlZCBpc29tcDQvbXBlZ3RzZGVtdXggZGVmYXVsdCBkdHNfc3VwcG9ydD1UUlVFLiBCb3VuZCBCRUZPUkUgdGhlCiMgICAgICAgICByZWdlbiBiZWxvdyBzbyB0aGUgcmVnaXN0cnkgcGlja3MgdGhlbSB1cCBhdCB0aGVpciBub3JtYWwgcGF0aC4KWyAtZiAiJE1ZSVNPIiBdICYmICEgZ3JlcCAtcSAiICRMR0lTTyAiIC9wcm9jL21vdW50cyAyPi9kZXYvbnVsbCAmJiBtb3VudCAtbiAtLWJpbmQgLW8gcm8gIiRNWUlTTyIgIiRMR0lTTyIgMj4+JExPRwpbIC1mICIkTVlUU0QiIF0gJiYgISBncmVwIC1xICIgJExHVFNEICIgL3Byb2MvbW91bnRzIDI+L2Rldi9udWxsICYmIG1vdW50IC1uIC0tYmluZCAtbyBybyAiJE1ZVFNEIiAiJExHVFNEIiAyPj4kTE9HCiMgLS0tIEFQUExZIDMpIHJlZ2VuZXJhdGUgdGhlIG1lZGlhIHJlZ2lzdHJ5IChmcmVzaCkgd2l0aCBkdHNkZWMgKyBvdXIgbGliYXYsIHRoZW4gd3JpdGUgaXQgdG8gdGhlIG1lZGlhIHBhdGguCiMgICAgQm91bmRlZCBieSBgdGltZW91dGAgYW5kIHNjYW5uZWQgaW4tcHJvY2VzcyAoR1NUX1JFR0lTVFJZX0ZPUks9bm8pIHNvIGEgaGFuZyBjYW4ndCB0cmlwIEhCQwojICAgIGZhaWxzYWZlIGFuZCBubyBnc3QtcGx1Z2luLXNjYW5uZXIgY2hpbGQgbGluZ2VycyBwYXN0IHRoZSB0aW1lb3V0LgpSRUdfVE1QPS90bXAvZ3N0X2R0c19yZWcuYmluCnJtIC1mICIkUkVHX1RNUCIKTERfTElCUkFSWV9QQVRIPS92YXIvbGliL3dlYm9zYnJldy90cnVlaGQvbGlicyBcCkdTVF9SRUdJU1RSWV8xXzA9IiRSRUdfVE1QIiBcCkdTVF9QTFVHSU5fUEFUSF8xXzA9L3Vzci9saWIvZ3N0cmVhbWVyLTEuMDovbW50L2xnL3Jlcy9sZ2xpYi9nc3RyZWFtZXItMS4wOi92YXIvbGliL3dlYm9zYnJldy9kdHMyNSBcCkdTVF9SRUdJU1RSWV9GT1JLPW5vIEdTVF9SRUdJU1RSWV9VUERBVEU9eWVzIHRpbWVvdXQgMzAgL3Vzci9iaW4vZ3N0LWluc3BlY3QtMS4wID4vZGV2L251bGwgMj4+JExPRwojIC0tLSBHQVRFIDJiKSBwb3N0LWJpbmQgcGlwZWxpbmUgcHJvb2YsIHRoZW4gY29tbWl0OiBvdmVyd3JpdGUgdGhlIG1lZGlhCiMgICAgICAgICByZWdpc3RyeSBvbmx5IGlmIHRoZSByZWdlbiBzdXJ2aXZlZCB0aGUgYmluZHMgd2l0aCBhbGwgZml2ZSBlbGVtZW50cwojICAgICAgICAgaW50YWN0LiBPdGhlcndpc2UgZHJvcCBvdXIgb3duIGJpbmRzIC0tIHRoYXQgaXMgd2hhdCB0dXJucyAidGhlCiMgICAgICAgICBvdmVycmlkZSBkaWQgbm90IG1hdGNoIiBmcm9tIGEgYnJva2VuIG1lZGlhIHBpcGVsaW5lIGludG8gYSBuby1vcC4KaWYgdzI1X3JlZ19oYXNfYWxsICIkUkVHX1RNUCI7IHRoZW4KICBjcCAtZiAiJFJFR19UTVAiICIkUkVHIiAyPj4kTE9HICYmIGVjaG8gInJlZ2lzdHJ5IHVwZGF0ZWQgKGR0c2RlYythdmRlY190cnVlaGQrcXRkZW11eCt0c2RlbXV4K21hdHJvc2thZGVtdXgpIiA+PiRMT0cKICBlY2hvICJBUFBMSUVEPSRWRVJESUNUIgplbHNlCiAgdzI1X2xvZyAiUkVGVVNFRDogcmVnZW4gaXMgbWlzc2luZyAkUkVHX01JU1M7IG5vdCBjb21taXR0aW5nIGl0LCBhbmQgc3RhbmRpbmcgZG93biIKICB3MjVfc3RhbmRfZG93bgogIHRvYXN0ICJEVFMgRW5hYmxlcjogdGhlIHBsdWdpbiByZWdpc3RyeSBkaWQgbm90IHN1cnZpdmUgdGhlIG92ZXJyaWRlICgkUkVHX01JU1MgbWlzc2luZyksIHNvIG5vdGhpbmcgd2FzIGNoYW5nZWQuIgogIGVjaG8gIlJFRlVTRUQ9cGlwZWxpbmUiCiAgZWNobyAiUkVBU09OPXRoZSByZWdlbmVyYXRlZCBwbHVnaW4gcmVnaXN0cnkgaXMgbWlzc2luZyAkUkVHX01JU1MiCmZpCmV4aXQgMAo=
INIT_B64
chmod 0755 "$INIT_SCRIPT" && log "installed embedded init_dts25.sh -> $INIT_SCRIPT" || log "WARN: writing init_dts25.sh failed"

# --- 4b. Compatibility preflight (READ-ONLY) -------------------------------
# Run the gate that init_dts25.sh enforces, in its check mode: it fingerprints
# the three stock plugins we shadow (pristine, thanks to step 3), matches them
# against the verified-sets table, and confirms every payload object's dynamic
# dependencies resolve on THIS TV. Only one authored copy of that gate exists --
# this asks the installed script rather than duplicating it here.
#
# Nothing is bound until this passes and the boot hook is not linked at all, so a
# refusal never APPLIES anything (the staged files under /var/lib/webosbrew are
# inert without the binds). It is not a no-op on a TV that was already enabled,
# though: step 3 above has already detached the binds, and our `cp -f` registry
# would still be live. Every refusal branch below therefore stands the TV down --
# W25_STAND_DOWN=1 rebuilds LG's registry if one of ours is in place -- so the TV
# ends up on stock rather than half-way.
CHECK=$(W25_CHECK=1 FORCE="$FORCE" sh "$INIT_SCRIPT" 2>/dev/null)
GATE_VERDICT=$(printf '%s\n' "$CHECK" | sed -n 's/^VERDICT=//p' | head -n1)
GATE_REASON=$(printf '%s\n' "$CHECK" | sed -n 's/^REASON=//p' | head -n1)
GATE_LABEL=$(printf '%s\n' "$CHECK" | sed -n 's/^LABEL=//p' | head -n1)
GATE_CANFORCE=$(printf '%s\n' "$CHECK" | sed -n 's/^CANFORCE=//p' | head -n1)
GATE_LOADER=$(printf '%s\n' "$CHECK" | sed -n 's/^LOADER=//p' | head -n1)
GATE_STAGED=$(printf '%s\n' "$CHECK" | sed -n 's/^LOADER_STAGED=//p' | head -n1)
log "preflight: verdict=$GATE_VERDICT canforce=$GATE_CANFORCE loader=$GATE_LOADER staged=$GATE_STAGED reason=$GATE_REASON"

# Put the TV back on stock before reporting a refusal. Step 3 already detached the
# binds, so on a previously-enabled TV the only thing left applied is the `cp -f`
# registry -- which W25_STAND_DOWN=1 rebuilds from LG's own plugins. Prints
# STOOD_DOWN=1 when a registry of ours was actually live.
stand_down_now() {
  SD=$(W25_STAND_DOWN=1 sh "$INIT_SCRIPT" 2>/dev/null)
  log "stand-down: $(printf '%s' "$SD" | tr '\n' ' ')"
  case "$SD" in
    *STOOD_DOWN=1*)
      echo "This TV was previously enabled, so the overrides have been REVERTED:"
      echo "the bind-mounts are detached and LG's plugin registry has been restored." ;;
    *)
      echo "Nothing of ours was applied on this TV, and nothing was changed." ;;
  esac
}

if [ "$GATE_LOADER" != "ok" ]; then
  # LOADER_STAGED=0 means the CORE payload is not staged (out/ or truehd-out/
  # missing or not copied) -- a packaging problem, not an incompatible TV. A
  # demux-less staging is NOT this case: the gate skips optional objects.
  if [ "$GATE_STAGED" = 0 ]; then
    log "REFUSED: core payload incomplete -- $GATE_LOADER"
    echo "DTS + TrueHD install REFUSED: the core payload is incomplete."
    echo "  $GATE_LOADER"
    echo "Check that out/ and truehd-out/ are populated (see the header of this script)."
  else
    log "REFUSED: loader gate -- $GATE_LOADER"
    echo "DTS + TrueHD install REFUSED: the payload cannot load on this TV."
    echo "  $GATE_LOADER"
  fi
  stand_down_now
  echo "See $LOG for details."
  exit 0
fi

case "$GATE_VERDICT" in
  verified)
    log "gate: verified TV -- $GATE_LABEL"
    echo "Verified TV: $GATE_LABEL"
    ;;
  forced)
    log "gate: forced apply on an unverified TV -- $GATE_REASON"
    echo "WARNING: this TV is not on the verified list; applying anyway (FORCE=1)."
    ;;
  drift)
    # A firmware change that touches the plugins we shadow stands us down, full
    # stop -- FORCE=1 does not apply here, so it is not offered. What DOES work is
    # clearing the recorded baseline (uninstall.sh) and opting in through the
    # unverified flow, or getting this TV added to the verified table.
    log "REFUSED: drift -- $GATE_REASON"
    echo "DTS + TrueHD install REFUSED: this TV changed since it was last verified."
    echo "  $GATE_REASON"
    echo ""
    stand_down_now
    echo "FORCE=1 does not override this."
    echo "To opt in again explicitly:  sh uninstall.sh  &&  FORCE=1 sh install.sh"
    echo "Or report these fingerprints so this TV can be added to the verified table:"
    printf '%s\n' "$CHECK" | sed -n 's/^PRODUCT_ID=/    product_id=/p;s/^WEBOS_RELEASE=/    webos_release=/p;s/^GST_MM=/    gst_mm=/p;s/^MD5_LIBGSTLIBAV=/    libgstlibav=/p;s/^MD5_LIBGSTISOMP4=/    libgstisomp4=/p;s/^MD5_LIBGSTMPEGTSDEMUX=/    libgstmpegtsdemux=/p;s/^MD5_DEVICE_CODEC_CAPABILITY_CONFIG=/    device_codec_capability_config=/p;s/^MD5_GSTCOOL=/    gstcool=/p'
    echo "See $LOG for details."
    exit 0
    ;;
  *)
    log "REFUSED: $GATE_VERDICT -- $GATE_REASON"
    echo "DTS + TrueHD install REFUSED: $GATE_REASON"
    if [ "$GATE_CANFORCE" = 1 ]; then
      # unverified only -- drift is handled above and reports CANFORCE=0.
      echo "The payload's libraries DO resolve on this TV. To opt in anyway:"
      echo "    FORCE=1 sh install.sh"
    fi
    stand_down_now
    echo "See $LOG for details."
    exit 0
    ;;
esac

# --- 4c. Link the boot hook (only now that the gate has passed) -------------
mkdir -p "$INITD"
if [ -L "$HOOK" ] || [ -e "$HOOK" ]; then rm -f "$HOOK"; fi
ln -s "$INIT_SCRIPT" "$HOOK" && log "linked boot hook $HOOK -> $INIT_SCRIPT"

# --- 5. Apply now ----------------------------------------------------------
# The init script re-runs the same gate, writes stock.fp from the pristine
# fingerprints, binds, and commits the registry only if all five elements
# (dtsdec, avdec_truehd, qtdemux, tsdemux, matroskademux) survive the binds.
log "applying now (running $INIT_SCRIPT)"
APPLY=$(FORCE="$FORCE" sh "$INIT_SCRIPT" 2>/dev/null)
log "apply result: $(printf '%s' "$APPLY" | tr '\n' ' ')"

case "$APPLY" in
  *REFUSED=*)
    echo "DTS + TrueHD install did NOT apply:"
    printf '%s\n' "$APPLY" | sed -n 's/^REASON=/  /p'
    echo "The boot hook has been left in place; it re-checks on every boot and"
    echo "binds nothing until the TV passes. See $LOG for details."
    ;;
  *)
    if killall starfish-media-pipeline 2>>"$LOG"; then
      log "restarted starfish-media-pipeline"
    else
      log "note: starfish-media-pipeline not running (starts fresh on next playback)"
    fi
    echo "DTS + TrueHD install complete. See $LOG for details."
    ;;
esac

log "=== unified DTS+TrueHD install done ==="
exit 0
